### PR TITLE
manage-user-profile-edits

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Updates related to the frontend's manage user profile page

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/66)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/66)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 518 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/66#-N1iXPO77WUzAXHRUfKH:-N1iXPO83TGzoFuZrbLs:b8c1e69) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/722085a8c5117d51ca56259ca5022161589b27be/saltapi/repository/proposal_repository.py#L518)):*
> ```Python
>        P.Partner_Code          AS partner_code,
>        P.Partner_Name          AS partner_name,
>        `IN`.InstituteName_Name AS institution,
> ```

institution > institution_name
___
*[`saltapi/repository/proposal_repository.py` line 554 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/66#-N1iWsp640mksG2Sds4p:-N1iWsp640mksG2Sds4q:bxgo0wc) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/722085a8c5117d51ca56259ca5022161589b27be/saltapi/repository/proposal_repository.py#L554)):*
> ```Python
>             del investigator["partner_code"]
>             del investigator["partner_name"]
>             del investigator["name"]
> ```

Shouldn't that be

`del investigator["institution"]`

?
___
*[`saltapi/web/schema/institution.py` line 26 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/66#-N1iXCTxDpSsY_J6tFw2:-N1iXCTxDpSsY_J6tFw3:b-hzbi2j) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/722085a8c5117d51ca56259ca5022161589b27be/saltapi/web/schema/institution.py#L26)):*
> ```Python
>         description="Name of the SALT Partner",
>     )
>     name: str = Field(..., title="Institution", description="Institution")
> ```

name: str = Field(..., title="Institution", description="Institution") > name: str = Field(..., title="Name", description="Name of the institution")

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/66)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 518 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/66#-N1iXPO77WUzAXHRUfKH:-N1j22Et4oG_DekOa1pS:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/722085a8c5117d51ca56259ca5022161589b27be/saltapi/repository/proposal_repository.py#L518)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

institution > institution_name
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 554 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/66#-N1iWsp640mksG2Sds4p:-N1j1VHBB7A6cp6dq8Lt:b6foy1b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/722085a8c5117d51ca56259ca5022161589b27be/saltapi/repository/proposal_repository.py#L554)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't that be

`del investigator["institution"]`

?
</blockquote></details>

You're right but it is actually affiliation
___
*[`saltapi/web/schema/institution.py` line 26 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/66#-N1iXCTxDpSsY_J6tFw2:-N1j1qE532KR7iz_RMWq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/722085a8c5117d51ca56259ca5022161589b27be/saltapi/web/schema/institution.py#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

name: str = Field(..., title="Institution", description="Institution") > name: str = Field(..., title="Name", description="Name of the institution")
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/66)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 554 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/66#-N1iWsp640mksG2Sds4p:-N1j4qvc7fnjzGaSZnoQ:bhsqu9z) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/722085a8c5117d51ca56259ca5022161589b27be/saltapi/repository/proposal_repository.py#L554)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

You're right but it is actually affiliation
</blockquote></details>

I'd doubt that. The code was removing the values from the investigator dict which had been added to the affiliation dict, but now it is removing the affiliation again...

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/66)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 554 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/66#-N1iWsp640mksG2Sds4p:-N1lz_cG3zYumQT52olo:bvxug1v) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/722085a8c5117d51ca56259ca5022161589b27be/saltapi/repository/proposal_repository.py#L554)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd doubt that. The code was removing the values from the investigator dict which had been added to the affiliation dict, but now it is removing the affiliation again...
</blockquote></details>

Oh, I see. My bad, I have added the code back again.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/66)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
