### PR TITLE
Verify user

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
Check the code inconsistent use of activation and verification

> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282#-:-NsrprOOCd3zmm_URMXW:bkqm6hs)* status: 1 of 8 files reviewed, 16 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/user_repository.py` line 1059 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrog__-X3kup9QoE7o:-Nsrog__-X3kup9QoE7p:bifefut) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/repository/user_repository.py#L1059)):*
> ```Python
>         )
> 
>     def verify_user(self, user_id: int, verify: bool = True) -> None:
> ```

Are you testing this method anywhere?
___
*[`saltapi/repository/user_repository.py` line 1061 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrhdN-Boi2p8rXW2PS:-NsrhdN-Boi2p8rXW2PT:b-yqzfat) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/repository/user_repository.py#L1061)):*
> ```Python
>     def verify_user(self, user_id: int, verify: bool = True) -> None:
>         """
>         Method to change user's verification statatus.
> ```

How about "Update user's verification status"? 

Also, the function raises an exception if certain condition is met. May be worth adding this information to the docstring for consistency?
___
*[`saltapi/repository/user_repository.py` line 1076 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrorJ88Zctw56j3_hS:-NsrorJ88Zctw56j3_hT:bifefut) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/repository/user_repository.py#L1076)):*
> ```Python
>         self.connection.execute(stmt, {"user_id": user_id, "verify": verify})
> 
>     def activate_user(self, user_id: int, active: bool = True) -> None:
> ```

Are you testing this method anywhere?
___
*[`saltapi/repository/user_repository.py` line 1078 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsriLRjDnVLCB8Oph3x:-NsriLRk8pveMNQjlms_:b-ghm9ev) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/repository/user_repository.py#L1078)):*
> ```Python
>     def activate_user(self, user_id: int, active: bool = True) -> None:
>         """
>         Method to activate or deactivate a user.
> ```

How about "Update user's activation status"? 

Also, the function raises an exception if certain condition is met. May be worth adding this information to the docstring for consistency
___
*[`saltapi/service/authentication_service.py` line 72 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsriuB45GGRPVqNqtQ6:-NsriuB45GGRPVqNqtQ7:b-7xd8v3) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/service/authentication_service.py#L72)):*
> ```Python
>             payload: Dict[str, Any], expires_delta: Optional[timedelta] = None
>     ) -> str:
>         """Create a JWT token."""
> ```

May be  "Create a temporary JWT token."
___
*[`saltapi/service/authentication_service.py` line 188 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrkXvP2hx_cwnobTPH:-NsrkXvP2hx_cwnobTPI:b-igc8w2) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/service/authentication_service.py#L188)):*
> ```Python
> 
>             return user
>         raise ValidationError("Failed to validate user.")
> ```

For readability, how about the following?



_Code snippet:_
```Python
if not authorization:
    raise ValidationError("Failed to validate user.")

user = _user_from_auth_header(authorization, verification=True)
if not user:
    raise NotFoundError("User not found")

return user
```
___
*[`saltapi/service/permission_service.py` line 528 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrlKGlBnNspeG1CaKP:-NsrlKGlBnNspeG1CaKQ:b1z9pij) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/service/permission_service.py#L528)):*
> ```Python
>             return
>         if user_id != user.id:
>             raise ValidationError(f"You cannot user id {user_id}")
> ```

Error message incomplete?
___
*[`saltapi/service/user_service.py` line 213 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrlad89IUSZOO_4y0I:-Nsrlad89IUSZOO_4y0J:b-yeh1b6) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/service/user_service.py#L213)):*
> ```Python
>     <p>Alternatively, you can copy the link and paste it into the address bar of your browser.</p>
>     <p>Please note that this verification link will expire in 3 hours.</p>
>     <p>IIf you did not intend to register to the SALT Web Manager, please disregard this email.</p>
> ```

Iif > If
___
*[`saltapi/service/user_service.py` line 224 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrlm_D-5lKQEss9yaO:-Nsrlm_D-5lKQEss9yaP:b-2nthhp) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/service/user_service.py#L224)):*
> ```Python
>             html_body=html_body,
>             plain_body=plain_body,
>             subject="User Activation",
> ```

How about this subject "SALT Web Manager User Activation"?
___
*[`saltapi/web/api/users.py` line 121 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrgkOr36YyfiVPu7y2:-NsrgkOr36YyfiVPu7y3:bn1tyd2) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L121)):*
> ```Python
> 
> @router.post(
>     "/send-verification-link", summary="Send an activation Link", response_model=Message
> ```

activation >> verification
___
*[`saltapi/web/api/users.py` line 130 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrgrWY-4nJGyZw5eJ9:-NsrgrWY-4nJGyZw5eJA:bn1tyd2) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L130)):*
> ```Python
> ) -> Message:
>     """
>     Send activation link.
> ```

activation >> verification
___
*[`saltapi/web/api/users.py` line 138 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrmej-ELlALv6TPJgN:-Nsrmej-ELlALv6TPJgO:b-vdbv8l) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L138)):*
> ```Python
>             user = user_service.get_user_by_username(username_email.username_email)
>         except NotFoundError:
>             user = user_service.get_user_by_email(username_email.username_email)
> ```

You're not handling an exception raise from this line when the user still doesn't exist, in which case this line will raise a NotFoundError.
___
*[`saltapi/web/api/users.py` line 333 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrn5Gz-pgk8MB4wEvZ:-Nsrn5Gz-pgk8MB4wEv_:b6tpmpd) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L333)):*
> ```Python
> 
> @router.post(
>     "/{user_id}/verify-user", summary="Activate user", response_model=User
> ```

verify-user or activate-user?
___
*[`saltapi/web/api/users.py` line 335 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrpWlo9owAaVamZYmN:-NsrpWlo9owAaVamZYmO:b-aid2rf) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L335)):*
> ```Python
>     "/{user_id}/verify-user", summary="Activate user", response_model=User
> )
> def activate_user(
> ```

Activate > verification
___
*[`saltapi/web/api/users.py` line 345 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrpa125lNBypP5iy54:-Nsrpa125lNBypP5iy55:b-aid2rf) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L345)):*
> ```Python
> ) -> _User:
>     """
>     Activate user
> ```

Activate > verification
___
*[`tests/integration/users/test_user_activation.py` line 23 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrnO2sBJcjMXM9VgxP:-NsrnO2sBJcjMXM9VgxQ:bebxelc) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/tests/integration/users/test_user_activation.py#L23)):*
> ```Python
> 
> 
> def test_password_update_requires_valid_user_id(
> ```

This might be a typo? This doesn't deal with password update right?

**Review by Eb-Zeero — COMMENTED** [review]
all should be done

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282#-:-NssB9_L61hhpZTSP1VT:b-x1591m)* status: 1 of 8 files reviewed, 16 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/user_repository.py` line 1059 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrog__-X3kup9QoE7o:-NssBe6d419q6o61kVsh:b-45b1tz) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/repository/user_repository.py#L1059)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Are you testing this method anywhere?
</blockquote></details>

I have added this test to issue 281.

I am still waiting on PR 272 it will have the correct status code and the correct way for fetching  and authenticating users
___
*[`saltapi/repository/user_repository.py` line 1061 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrhdN-Boi2p8rXW2PS:-Nss4sF_8OtYKXDJXjkA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/repository/user_repository.py#L1061)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

How about "Update user's verification status"? 

Also, the function raises an exception if certain condition is met. May be worth adding this information to the docstring for consistency?
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1076 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrorJ88Zctw56j3_hS:-NssCTSuCar8f6CIRALk:b-45b1tz) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/repository/user_repository.py#L1076)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Are you testing this method anywhere?
</blockquote></details>

I have added this test to issue 281.

I am still waiting on PR 272 it will have the correct status code and the correct way for fetching  and authenticating users
___
*[`saltapi/repository/user_repository.py` line 1078 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsriLRjDnVLCB8Oph3x:-Nss4yx67XYbyBRib0zq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/repository/user_repository.py#L1078)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

How about "Update user's activation status"? 

Also, the function raises an exception if certain condition is met. May be worth adding this information to the docstring for consistency
</blockquote></details>

Done.
___
*[`saltapi/service/authentication_service.py` line 72 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsriuB45GGRPVqNqtQ6:-Nss58u09nY1K-zvEVTu:b-wtd3qh) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/service/authentication_service.py#L72)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

May be  "Create a temporary JWT token."
</blockquote></details>

Method wasn't used it was a code duplication
___
*[`saltapi/service/authentication_service.py` line 188 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrkXvP2hx_cwnobTPH:-Nss5sKg1x3s0SCveyKz:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/service/authentication_service.py#L188)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

For readability, how about the following?
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 528 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrlKGlBnNspeG1CaKP:-Nss6UOY4je89itc1Wa3:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/service/permission_service.py#L528)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Error message incomplete?
</blockquote></details>

Done.
___
*[`saltapi/service/user_service.py` line 213 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrlad89IUSZOO_4y0I:-Nss6_5V1VbaZPPrRZEi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/service/user_service.py#L213)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Iif > If
</blockquote></details>

Done.
___
*[`saltapi/service/user_service.py` line 224 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrlm_D-5lKQEss9yaO:-Nss3eyCAGBe6ZCoQ7YP:b-ue02sa) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/service/user_service.py#L224)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

How about this subject "SALT Web Manager User Activation"?
</blockquote></details>

yes sir but "verification"
___
*[`saltapi/web/api/users.py` line 121 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrgkOr36YyfiVPu7y2:-Nss6wfS57_3IblhEcAD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L121)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

activation >> verification
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 130 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrgrWY-4nJGyZw5eJ9:-Nss6x5J9ZtQ2XYFh4c4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L130)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

activation >> verification
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 138 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrmej-ELlALv6TPJgN:-Nss7IiiBg7aaxOfnMrx:b-e804mk) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L138)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

You're not handling an exception raise from this line when the user still doesn't exist, in which case this line will raise a NotFoundError.
</blockquote></details>

Correct Sir, code slipped in due to branches mix-up from one of the PRs,

This is fixed by another PR
___
*[`saltapi/web/api/users.py` line 333 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrn5Gz-pgk8MB4wEvZ:-Nss82Fa0E62hC941dMH:b-jadd8i) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L333)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

verify-user or activate-user?
</blockquote></details>

verify
___
*[`saltapi/web/api/users.py` line 335 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrpWlo9owAaVamZYmN:-Nss83d82nZHN-ct-v7F:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L335)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Activate > verification
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 345 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrpa125lNBypP5iy54:-Nss86Rh45PAY763ywdP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L345)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Activate > verification
</blockquote></details>

Done.
___
*[`tests/integration/users/test_user_activation.py` line 23 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NsrnO2sBJcjMXM9VgxP:-Nss9a388B5uLkHJPmdE:bhpq8lm) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/tests/integration/users/test_user_activation.py#L23)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

This might be a typo? This doesn't deal with password update right?
</blockquote></details>

correct 
changed -> activation to verification and filename > renamed

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282)* status: 1 of 8 files reviewed, 17 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`tests/integration/users/test_user_activation.py` line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-NssCYc14BW4_051NKeq:-NssCYc14BW4_051NKer:b-tb0ras) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/tests/integration/users/test_user_activation.py#L1)):*
> ```Python
> import pytest
> ```

These tests are all failing PR 272 will ensure they pass

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 2 of 6 files at r2, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/users.py` line 138 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrmej-ELlALv6TPJgN:-Nt1E4hn7szvggS9c0Tb:b8pibup) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L138)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Correct Sir, code slipped in due to branches mix-up from one of the PRs,

This is fixed by another PR
</blockquote></details>

Still not addressed? I don't see where the other exception is handled.
___
*[`tests/integration/users/test_user_verification.py` line 39 at r4](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nt1F-p65CLWAZ0kfdmD:-Nt1F-p65CLWAZ0kfdmE:b-mrq3e) ([raw file](https://github.com/saltastroops/salt-api/blob/fdb74529cc3f4536e0ae6aaabe0bfd58b1619422/tests/integration/users/test_user_verification.py#L39)):*
> ```Python
> 
> 
> def test_user_cannot_validate_user_with_authentication_token(
> ```

test_user_cannot_validate_user_with_authentication_token >> test_user_cannot_validate_user_without_authentication_token?
___
*[`tests/integration/users/test_user_verification.py` line 76 at r4](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nt1EZiV7tgDOwKrbQtR:-Nt1EZiV7tgDOwKrbQtS:b-kgfmik) ([raw file](https://github.com/saltastroops/salt-api/blob/fdb74529cc3f4536e0ae6aaabe0bfd58b1619422/tests/integration/users/test_user_verification.py#L76)):*
> ```Python
> 
> 
> def test_admins_can_other_users(
> ```

test_admins_can_other_users > test_admins_can_verify_other_users?

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/users.py` line 142 at r5](https://reviewable.io/reviews/saltastroops/salt-api/282#-NtGEB4E4WiZWdLZPbdP:-NtGEB4E4WiZWdLZPbdQ:b-gm5r99) ([raw file](https://github.com/saltastroops/salt-api/blob/cfd57773f3bacef3fa6708c1919796cd1319c6c3/saltapi/web/api/users.py#L142)):*
> ```Python
>         if not user:
>             user = user_service.get_user_by_email(username_email.username_email)
>         if not user:
> ```

How about the following to remove code duplication?



_Code snippet:_
```Python
user = (
            user_service.get_user_by_username(username_email.username_email)
            or user_service.get_user_by_email(username_email.username_email)
        )
if not user:
    raise NotFoundError()
```

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282)* status: all files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/web/api/users.py` line 138 at r1](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nsrmej-ELlALv6TPJgN:-NtFqxPM12Jq7bXvonZm:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8160f0cee01cd81ef85eb6c03f6a92ef3cb7c3d2/saltapi/web/api/users.py#L138)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Still not addressed? I don't see where the other exception is handled.
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 142 at r5](https://reviewable.io/reviews/saltastroops/salt-api/282#-NtGEB4E4WiZWdLZPbdP:-NtGJ41K0i5_Oz6sccOd:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cfd57773f3bacef3fa6708c1919796cd1319c6c3/saltapi/web/api/users.py#L142)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

How about the following to remove code duplication?
</blockquote></details>

Done.
___
*[`tests/integration/users/test_user_verification.py` line 39 at r4](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nt1F-p65CLWAZ0kfdmD:-NtFr8cRAWLoK25EzpIm:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/fdb74529cc3f4536e0ae6aaabe0bfd58b1619422/tests/integration/users/test_user_verification.py#L39)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

test_user_cannot_validate_user_with_authentication_token >> test_user_cannot_validate_user_without_authentication_token?
</blockquote></details>

Done.
___
*[`tests/integration/users/test_user_verification.py` line 76 at r4](https://reviewable.io/reviews/saltastroops/salt-api/282#-Nt1EZiV7tgDOwKrbQtR:-NtFrD6j6IzUPy3-15h6:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/fdb74529cc3f4536e0ae6aaabe0bfd58b1619422/tests/integration/users/test_user_verification.py#L76)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

test_admins_can_other_users > test_admins_can_verify_other_users?
</blockquote></details>

Done.

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282)* status: all files reviewed, 1 unresolved discussion

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`tests/integration/authentication/test_authentication.py` line 47 at r7](https://reviewable.io/reviews/saltastroops/salt-api/282#-NtGM4TEE8veztPKwUOg:-NtGM4TEE8veztPKwUOh:b-te6urk) ([raw file](https://github.com/saltastroops/salt-api/blob/b2fad242daf6a14cccd07cc5e8b726d874c5b5bf/tests/integration/authentication/test_authentication.py#L47)):*
> ```Python
> 
> @pytest.mark.parametrize("endpoint", [TOKEN_URL, LOGIN_URL])
> @pytest.mark.skip(reason="User needs to be active and not veried")
> ```

veried > verified
___
*[`tests/integration/authentication/test_authentication.py` line 56 at r7](https://reviewable.io/reviews/saltastroops/salt-api/282#-NtGMGN_6-gpX7ZAsBi2:-NtGMGNaAYriqP7YFvOb:but9xjl) ([raw file](https://github.com/saltastroops/salt-api/blob/b2fad242daf6a14cccd07cc5e8b726d874c5b5bf/tests/integration/authentication/test_authentication.py#L56)):*
> ```Python
>     )
>     assert response.status_code == status.HTTP_403_FORBIDDEN
>     # TODO activate user and not verified the user to Do this test
> ```

not verified > not verify?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`tests/integration/authentication/test_authentication.py` line 47 at r7](https://reviewable.io/reviews/saltastroops/salt-api/282#-NtGM4TEE8veztPKwUOg:-NtGMhM82T_nV8Js6h43:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b2fad242daf6a14cccd07cc5e8b726d874c5b5bf/tests/integration/authentication/test_authentication.py#L47)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

veried > verified
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 56 at r7](https://reviewable.io/reviews/saltastroops/salt-api/282#-NtGMGN_6-gpX7ZAsBi2:-NtGMn8p-OpOagh-xuIL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b2fad242daf6a14cccd07cc5e8b726d874c5b5bf/tests/integration/authentication/test_authentication.py#L56)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

not verified > not verify?
</blockquote></details>

Done.

**Review by mofokeng-chaka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282)* status: all files reviewed, 1 unresolved discussion

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/282)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
