### PR TITLE
Fix status comment

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/173)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/173)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 481 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJBF_d415vkuMbXsRH:-NOJBF_eEyqp2pAMFxPc:b6v0gi4) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/repository/proposal_repository.py#L481)):*
> ```Python
>             "summary_for_night_log": row.summary_for_night_log,
>             "submission_number": row.submission_number,
>             "status": self.get_proposal_status(proposal_code),
> ```

It might be more efficient to query the status in this rather than in an extra query.
___
*[`saltapi/web/api/proposals.py` line 345 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJCphZ5Vjy207gekuZ:-NOJCph_7a_ipGspAL3B:b75mc9y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/proposals.py#L345)):*
> ```Python
>         ...,
>         alias="status",
>         title="Proposal status and (optional) status reason",
> ```

reason > comment
___
*[`saltapi/web/api/proposals.py` line 346 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJCtWJ2YNKWi5XVhG2:-NOJCtWJ2YNKWi5XVhG3:b75mc9y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/proposals.py#L346)):*
> ```Python
>         alias="status",
>         title="Proposal status and (optional) status reason",
>         description="New proposal status and (optional) status reason."
> ```

reason > comment
___
*[`saltapi/web/api/proposals.py` line 355 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJD2tO-8eGagMRCJ7S:-NOJD2tO-8eGagMRCJ7T:by1gq84) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/proposals.py#L355)):*
> ```Python
>     """
>     with UnitOfWork() as unit_of_work:
>         proposal_service = services.proposal_service(unit_of_work.connection)
> ```

Is there a reason why you moved this line up?
___
*[`saltapi/web/api/proposals.py` line 366 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJDYl0CC5o3I9f3ZWp:-NOJDYl0CC5o3I9f3ZWq:b-l1bw3y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/proposals.py#L366)):*
> ```Python
>         )
> 
>         unit_of_work.connection.commit()
> ```

I wonder why you would need the commit here?
___
*[`saltapi/web/api/user.py` line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJDnyX0kfOvdwTW3N8:-NOJDnyX0kfOvdwTW3N9:b69svqq) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/user.py#L1)):*
> ```Python
> 
> ```

There might be a unnecessary empty line here?
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 13 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEpi_4f_XaJQa6Ey4:-NOJEpi_4f_XaJQa6Ey5:b-i14ec1) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L13)):*
> ```Python
>     client: TestClient,
> ) -> None:
>     proposal_code = "2021-2-LSP-001"
> ```

Throughout this file `proposal_inactive_reason` should be replaced with `status_comment`.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 19 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJDzyG5tyOR_PP1NQO:-NOJDzyG5tyOR_PP1NQP:b75mc9y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L19)):*
> ```Python
>     response = client.put(
>         PROPOSALS_URL + "/" + proposal_code + "/status",
>         json={"value": proposal_status_value, "reason": None},
> ```

reason > comment
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 48 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJE24i29ub8uJ4fA8s:-NOJE24i29ub8uJ4fA8t:b75mc9y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L48)):*
> ```Python
>     response = client.put(
>         PROPOSALS_URL + "/" + proposal_code + "/status",
>         json={ "value": proposal_status_value, "reason": None},
> ```

reason > comment
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 74 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJE8qI2YNf6Txnu3vn:-NOJE8qI2YNf6Txnu3vo:b75mc9y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L74)):*
> ```Python
>     response = client.put(
>         PROPOSALS_URL + "/" + proposal_code + "/status",
>         json={"value": proposal_status_value, "reason": None},
> ```

reason > comment
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 96 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEE4A2hSYHiyNka9w:-NOJEE4A2hSYHiyNka9x:b75mc9y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L96)):*
> ```Python
>     response = client.put(
>         PROPOSALS_URL + "/" + proposal_code + "/status",
>         json={"value": proposal_status_value, "reason": None},
> ```

reason > comment
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 118 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEIE_91jYp-2UHan2:-NOJEIE_91jYp-2UHan3:b75mc9y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L118)):*
> ```Python
>     response = client.put(
>         PROPOSALS_URL + "/" + proposal_code + "/status",
>         json={"value": proposal_status_value, "reason": None},
> ```

reason > comment
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 140 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJELkh2dWeejBcAFTO:-NOJELkh2dWeejBcAFTP:b75mc9y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L140)):*
> ```Python
>     response = client.put(
>         PROPOSALS_URL + "/" + proposal_code + "/status",
>         json={"value": proposal_status_value, "reason": None},
> ```

reason > comment
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 144 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJESnO3-EcMdGnkXbi:-NOJESnP8eziax058xtq:b-ve8hv1) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L144)):*
> ```Python
>     assert response.status_code == status.HTTP_200_OK
> 
> def test_proposal_status_update_requires_valid_proposal_inactive_reason(
> ```

This test has become obsolete.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 186 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEZ4F2ZvDac5eoiqw:-NOJEZ4F2ZvDac5eoiqx:b75mc9y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L186)):*
> ```Python
>     response = client.put(
>         PROPOSALS_URL + "/" + proposal_code + "/status",
>         json={"value": proposal_status_value, "reason": proposal_inactive_reason},
> ```

reason > comment
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 192 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEerc5VtkcG6SdrdY:-NOJEerc5VtkcG6SdrdZ:b75mc9y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L192)):*
> ```Python
>     proposal_status = response.json()
>     assert proposal_status["value"] == proposal_status_value
>     assert proposal_status["reason"] == proposal_inactive_reason
> ```

reason > comment
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 215 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEcDl7N-KshExX2g6:-NOJEcDl7N-KshExX2g7:b75mc9y) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L215)):*
> ```Python
>     response = client.put(
>         PROPOSALS_URL + "/" + proposal_code + "/status",
>         json={"value": proposal_status_value, "reason": proposal_inactive_reason},
> ```

reason > comment

**Review by Eb-Zeero — COMMENTED** [review]
Tests are fixed

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/173#-:-NOJVcN_3ESGEO5pj-Vp:b-v01z6k)* status: all files reviewed, 17 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 481 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJBF_d415vkuMbXsRH:-NOJPQRJ46-BSGKrFSnE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/repository/proposal_repository.py#L481)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be more efficient to query the status in this rather than in an extra query.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 345 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJCphZ5Vjy207gekuZ:-NOJPgnw0PoRIO5kvAiM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/proposals.py#L345)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reason > comment
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 346 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJCtWJ2YNKWi5XVhG2:-NOJPh4_7ypTkRLBFMJE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/proposals.py#L346)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reason > comment
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 355 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJD2tO-8eGagMRCJ7S:-NOJPzzB3BiKFlMnsG5z:bndo0gb) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/proposals.py#L355)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is there a reason why you moved this line up?
</blockquote></details>

no reason I just read it wrong  I thought it was a permission_service
___
*[`saltapi/web/api/proposals.py` line 366 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJDYl0CC5o3I9f3ZWp:-NOJQDZiDT8j06mDy77n:b-b8d0sd) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/proposals.py#L366)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wonder why you would need the commit here?
</blockquote></details>

I am running an update
___
*[`saltapi/web/api/user.py` line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJDnyX0kfOvdwTW3N8:-NOJQPEh0BYFwSRRHYuL:b-522gxx) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/user.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There might be a unnecessary empty line here?
</blockquote></details>

REmoved
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 13 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEpi_4f_XaJQa6Ey4:-NOJVemz2HQfA3W-qC2R:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Throughout this file `proposal_inactive_reason` should be replaced with `status_comment`.
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 19 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJDzyG5tyOR_PP1NQO:-NOJRR4P3_EKT00T4OsI:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reason > comment
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 48 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJE24i29ub8uJ4fA8s:-NOJRTOX5FtaZTYV-sNG:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reason > comment
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 74 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJE8qI2YNf6Txnu3vn:-NOJRVPODt2lhy6YVAeH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L74)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reason > comment
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 96 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEE4A2hSYHiyNka9w:-NOJRXwjC0pBBjcomG6j:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L96)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reason > comment
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 118 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEIE_91jYp-2UHan2:-NOJR_Cs6LqN7C__NvAp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L118)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reason > comment
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 140 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJELkh2dWeejBcAFTO:-NOJRb1FE2pN5ie_2zOi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L140)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reason > comment
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 144 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJESnO3-EcMdGnkXbi:-NOJRiw1-yau-lvAhp9v:b-l6mwxj) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L144)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This test has become obsolete.
</blockquote></details>

remove
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 186 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEZ4F2ZvDac5eoiqw:-NOJRtD35ZO_XXH2_W2b:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L186)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reason > comment
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 192 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEerc5VtkcG6SdrdY:-NOJRvSd8o0x22e-yOcr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L192)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reason > comment
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 215 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJEcDl7N-KshExX2g6:-NOJRy8Z0U8EddcvSiVy:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/tests/integration/proposals/test_update_proposal_status.py#L215)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reason > comment
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/173)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/proposals.py` line 366 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJDYl0CC5o3I9f3ZWp:-NOKJztFDWTp9B6aNDxV:bb8v6i9) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/proposals.py#L366)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I am running an update
</blockquote></details>

Yes, I was wrong there. (I thought the context manager commits, but it rolls back.)

But why do you need the `.connection`?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/173)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/web/api/proposals.py` line 366 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJDYl0CC5o3I9f3ZWp:-NOKjSd_9b_qVpROwo5j:bw1s0dj) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/proposals.py#L366)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes, I was wrong there. (I thought the context manager commits, but it rolls back.)

But why do you need the `.connection`?
</blockquote></details>

Sorry no need for a connection

**Review by hettlage — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/173)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/173)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/proposals.py` line 366 at r1](https://reviewable.io/reviews/saltastroops/salt-api/173#-NOJDYl0CC5o3I9f3ZWp:-NOKmcmwAymRrs2SlA_F:b-ucfknh) ([raw file](https://github.com/saltastroops/salt-api/blob/e772420c56363a1730d762e7805b88104717d7c2/saltapi/web/api/proposals.py#L366)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Sorry no need for a connection
</blockquote></details>

Thanks!

**Pull request merged**
