### PR TITLE
Role changing

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)* status: all files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/user_repository.py` line 1090 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M4OQKAkn5IbZ4-alH:-O-M4OQKAkn5IbZ4-alI:blbplem) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/repository/user_repository.py#L1090)):*
> ```Python
>         self.connection.execute(stmt, {"user_id": user_id, "active": active})
> 
>     def _get_right_setting_id(self, right_setting: str):
> ```

You don't need this function, I think. Instead you can include the SQL query directly in the INSERT query. Something like:

```
INSERT INTO PiptUserSetting (PiptUser_Id, PiptSetting_Id, Value)
VALUES (
     :user_id,
    (SELECT PiptSetting_Id FROM PipSetting WHERE PiptSetting_Name = :right_setting),
    :value)
ON DUPLICATE KEY UPDATE Value = :value
```
___
*[`saltapi/repository/user_repository.py` line 1101 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M8pXD5sy1TFiuCvyk:-O-M8pXD5sy1TFiuCvyl:b-cng2g2) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/repository/user_repository.py#L1101)):*
> ```Python
>         return cast(int, result.scalar_one())
> 
>     def update_right(self, user_id: int, right_setting: str, value: int):
> ```

Shouldn't you rather have a function for updating _roles_?
___
*[`saltapi/service/user_service.py` line 231 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M7q7xC7p25NjdK9za:-O-M7q7y8B-VaQXHNnTk:b-v7fitb) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/service/user_service.py#L231)):*
> ```Python
>         self.repository.verify_user(user_id)
> 
>     def get_right_setting(self, right) -> str:
> ```

This probably should be a private function, used by the user repository?

Also, shouldn't the parameter be `role`, not `right?
___
*[`saltapi/service/user_service.py` line 247 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M9BeHErZaUT4adL_N:-O-M9BeHErZaUT4adL_O:buge265) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/service/user_service.py#L247)):*
> ```Python
>         raise ValidationError("Unknown user right: " + right)
> 
>     def update_user_rights(self, user_id: int, rights: List[UserRights]) -> None:
> ```

Shouldn't you update roles rather than rights?
___
*[`saltapi/service/user_service.py` line 255 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M6dgrEFWnrEvl43qB:-O-M6dgrEFWnrEvl43qC:b-793ah9) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/service/user_service.py#L255)):*
> ```Python
>             if right.level == RightLevel.ALL:
>                 value = 2
>             if right.right == Role.LIBRARIAN and right.level != RightLevel.NONE:
> ```

Why do you specifically rule this out for librarians? And what if (hypothetically) Encarni happened to be a librarian as well?
___
*[`saltapi/web/api/users.py` line 370 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M8GI01ogG0OC30kSo:-O-M8GI01ogG0OC30kSp:b-6ngrcy) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/web/api/users.py#L370)):*
> ```Python
> 
> @router.post("/{user_id}/update-rights", summary="Update user rights", response_model=User)
> def update_user_rights(
> ```

Are you updating rights or roles?
___
*[`saltapi/web/api/users.py` line 384 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M8P1uAI7iqKXdA5YZ:-O-M8P1uAI7iqKXdA5Y_:b-lcc8r1) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/web/api/users.py#L384)):*
> ```Python
> ) -> User:
>     """
>    Update user's password.
> ```

Wrong docstring... :-)
___
*[`saltapi/web/schema/user.py` line 196 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M6I8q9qauiR3VzSYT:-O-M6I8q9qauiR3VzSYU:b239tcf) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/web/schema/user.py#L196)):*
> ```Python
> 
> 
> class RightLevel(str, Enum):
> ```

Didn't we want to get rid of these levels?
___
*[`saltapi/web/schema/user.py` line 202 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M6NLu59TYcVKaVQZ3:-O-M6NLu59TYcVKaVQZ4:b-kccm22) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/web/schema/user.py#L202)):*
> ```Python
> 
> 
> class UserRights(BaseModel):
> ```

UserRights > UserRight

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)* status: 1 of 8 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/user_repository.py` line 1090 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M4OQKAkn5IbZ4-alH:-O-eFiGg7MCdt__MQY38:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/repository/user_repository.py#L1090)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You don't need this function, I think. Instead you can include the SQL query directly in the INSERT query. Something like:

```
INSERT INTO PiptUserSetting (PiptUser_Id, PiptSetting_Id, Value)
VALUES (
     :user_id,
    (SELECT PiptSetting_Id FROM PipSetting WHERE PiptSetting_Name = :right_setting),
    :value)
ON DUPLICATE KEY UPDATE Value = :value
```
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1101 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M8pXD5sy1TFiuCvyk:-O-e9J-C35uOPqDysA4k:b-xvppa6) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/repository/user_repository.py#L1101)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't you rather have a function for updating _roles_?
</blockquote></details>

Roles are given by the rights you have, roles can't updated until we have new ways of handling user roles 
___
*[`saltapi/service/user_service.py` line 231 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M7q7xC7p25NjdK9za:-O-eGBpKACB-GoCH4wMa:b8e1vh8) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/service/user_service.py#L231)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This probably should be a private function, used by the user repository?

Also, shouldn't the parameter be `role`, not `right?
</blockquote></details>

yes it is Role and making it private
it is only used here by service, not repository
___
*[`saltapi/service/user_service.py` line 247 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M9BeHErZaUT4adL_N:-O-eGW08C8ra4kaQYv9Y:b-h7wdj6) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/service/user_service.py#L247)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't you update roles rather than rights?
</blockquote></details>

at this level yes this are role I need to get rights
___
*[`saltapi/service/user_service.py` line 255 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M6dgrEFWnrEvl43qB:-O-eGiDYBdkVVORkXtc9:b-ysv9ht) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/service/user_service.py#L255)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you specifically rule this out for librarians? And what if (hypothetically) Encarni happened to be a librarian as well?
</blockquote></details>

removed the level stuffs
___
*[`saltapi/web/api/users.py` line 370 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M8GI01ogG0OC30kSo:-O-eH64X7IFaREPg6YTK:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/web/api/users.py#L370)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are you updating rights or roles?
</blockquote></details>

fixed
___
*[`saltapi/web/api/users.py` line 384 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M8P1uAI7iqKXdA5YZ:-O-eH7lp850Oy5hDf_2F:b-8tfzmv) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/web/api/users.py#L384)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wrong docstring... :-)
</blockquote></details>

fixed... 😂 copy and paste
___
*[`saltapi/web/schema/user.py` line 196 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M6I8q9qauiR3VzSYT:-O-eELLF7ms0DfRZpYf1:ba3dfob) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/web/schema/user.py#L196)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Didn't we want to get rid of these levels?
</blockquote></details>

Removed
___
*[`saltapi/web/schema/user.py` line 202 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M6NLu59TYcVKaVQZ3:-O-eEP6W5VUYtu8IJVAA:b-2twtv4) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/web/schema/user.py#L202)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

UserRights > UserRight
</blockquote></details>

Removed this was supposed to be role with level and we are getting rid of right level

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/user_repository.py` line 1101 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M8pXD5sy1TFiuCvyk:-O-emXICAXSrb8UU9KLb:bhiw5t7) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/repository/user_repository.py#L1101)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Roles are given by the rights you have, roles can't updated until we have new ways of handling user roles
</blockquote></details>

Let's discuss this in person, if possible?
___
*[`saltapi/service/user_service.py` line 231 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M7q7xC7p25NjdK9za:-O-en2m5EQ2lTfMa8wBu:btxt374) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/service/user_service.py#L231)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

yes it is Role and making it private
it is only used here by service, not repository
</blockquote></details>

I'm still not convinced the function should be here. Let's discuss in person.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/user_repository.py` line 1101 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M8pXD5sy1TFiuCvyk:-O-oWs87BoKA1bjF2XJe:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/repository/user_repository.py#L1101)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Let's discuss this in person, if possible?
</blockquote></details>

Done.
___
*[`saltapi/service/user_service.py` line 231 at r1](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-M7q7xC7p25NjdK9za:-O-oWy9KAmwaq2e_4ucH:b-djhqwc) ([raw file](https://github.com/saltastroops/salt-api/blob/36a1d6ef6e6a2e81d978d9cdfd088bb46bab7188/saltapi/service/user_service.py#L231)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm still not convinced the function should be here. Let's discuss in person.
</blockquote></details>

CODE MOVED TO REPOSITORY

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/user_repository.py` line 1121 at r3](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-oY-164ASAJz9xS575:-O-oY-164ASAJz9xS576:b-xlav33) ([raw file](https://github.com/saltastroops/salt-api/blob/9f15730d86d28c7ff60c8fd53a03a90ad846fcc1/saltapi/repository/user_repository.py#L1121)):*
> ```Python
>             return "RightLibrarian"
> 
>         raise ValidationError("Unknown user right: " + role)
> ```

right > role
___
*[`saltapi/repository/user_repository.py` line 1127 at r3](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-oYAWZ5caJf3h4eCcY:-O-oYAWZ5caJf3h4eCcZ:bl98q0m) ([raw file](https://github.com/saltastroops/salt-api/blob/9f15730d86d28c7ff60c8fd53a03a90ad846fcc1/saltapi/repository/user_repository.py#L1127)):*
From the role I assume everyone has the full rights of their roles.

>

The setting is set to 2 as that value indicates having full rights.
___
*[`saltapi/repository/user_repository.py` line 1132 at r3](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-oZelD7_4G7aXMGBFe:-O-oZelD7_4G7aXMGBFf:b-93xxfq) ([raw file](https://github.com/saltastroops/salt-api/blob/9f15730d86d28c7ff60c8fd53a03a90ad846fcc1/saltapi/repository/user_repository.py#L1132)):*
> ```Python
>             if role not in new_roles:
>                 right_setting = self._get_right_setting(role)
>                 self._update_right(user_id, right_setting, 0)
> ```

It might be even safer to delete the setting.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/user_repository.py` line 1121 at r3](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-oY-164ASAJz9xS575:-O-p1x5QCPAtVXSPmRdh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/9f15730d86d28c7ff60c8fd53a03a90ad846fcc1/saltapi/repository/user_repository.py#L1121)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

right > role
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1127 at r3](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-oYAWZ5caJf3h4eCcY:-O-p21Mi9yDYymaH3JIZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/9f15730d86d28c7ff60c8fd53a03a90ad846fcc1/saltapi/repository/user_repository.py#L1127)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

From the role I assume everyone has the full rights of their roles.

>

The setting is set to 2 as that value indicates having full rights.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1132 at r3](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-oZelD7_4G7aXMGBFe:-O-p4n1L09Wy5CtCkOZL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/9f15730d86d28c7ff60c8fd53a03a90ad846fcc1/saltapi/repository/user_repository.py#L1132)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be even safer to delete the setting.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/users.py` line 368 at r4](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-q-1s30gKFoJDqAT_Q:-O-q-1s30gKFoJDqAT_R:b-s02zs5) ([raw file](https://github.com/saltastroops/salt-api/blob/59e6fda2ee1d3d4781634fc868c059a12398e2e2/saltapi/web/api/users.py#L368)):*
> ```Python
> 
> 
> @router.patch("/{user_id}/update-roles", summary="Update user roles", response_model=User)
> ```

You can make a case for either POST or PATCH, but POST seems more consistent with other endpoints own this file.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/users.py` line 368 at r4](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-q-1s30gKFoJDqAT_Q:-O-q-GJo72WB6RVX8ljn:b-8ev1i2) ([raw file](https://github.com/saltastroops/salt-api/blob/59e6fda2ee1d3d4781634fc868c059a12398e2e2/saltapi/web/api/users.py#L368)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You can make a case for either POST or PATCH, but POST seems more consistent with other endpoints own this file.
</blockquote></details>

own > in

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)* status: all files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/user_repository.py` line 1124 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QOND41rY4yXq7k3rh:-O0QOND41rY4yXq7k3ri:b-lz81bw) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1124)):*
> ```Python
>         })
> 
>     def get_investigato_id(self, user_id) -> int:
> ```

investigato > investigator

Also, this can be a private method.
___
*[`saltapi/repository/user_repository.py` line 1126 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QOi9jAG-VKMI6fA-0:-O0QOi9jAG-VKMI6fA-1:b-xwk2cn) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1126)):*
> ```Python
>     def get_investigato_id(self, user_id) -> int:
>         stmt = text("""
> SELECT  Investigator_Id from Investigator WHERE PiptUser_Id = :user_id      
> ```

If there are two Investigator entries for a PiptUser, you will get an error, as there are two entries (and `result.scalar_one` below will fail).

The correct SQL should be:

```
SELECT Investigator_Id FROM PiptUser WHERE PiptUser_Id = :user_id
```
___
*[`saltapi/repository/user_repository.py` line 1143 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QRpQm2sZrlriscPuf:-O0QRpQm2sZrlriscPug:bz13lqn) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1143)):*
> ```Python
>     def _remove_salt_astronomer(self, user_id: int):
>         stmt = text("""
> DELETE FROM  SaltAstronomer
> ```

Too much whitespace after FROM
___
*[`saltapi/repository/user_repository.py` line 1150 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QRstv-Q4j33ZqLNjt:-O0QRstv-Q4j33ZqLNju:btixyc9) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1150)):*
> ```Python
>         })
> 
>     def _add_salt_oparator(self, user: User) -> None:
> ```

oparator > operator
___
*[`saltapi/repository/user_repository.py` line 1162 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QReTq-yVvT42tqHRt:-O0QReTr55Mj1EnNz8TU:btixyc9) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1162)):*
> ```Python
>         })
> 
>     def _remove_salt_oparator(self, user: User) -> None:
> ```

oparator > operator
___
*[`saltapi/repository/user_repository.py` line 1164 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QRkI32qOtL5P8enMp:-O0QRkI32qOtL5P8enMq:bz13lqn) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1164)):*
> ```Python
>     def _remove_salt_oparator(self, user: User) -> None:
>         stmt = text("""
> DELETE FROM  SaltOperator
> ```

Too much whitespace after FROM
___
*[`saltapi/repository/user_repository.py` line 1190 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QSpbQ2UuSRxDmYcEV:-O0QSpbQ2UuSRxDmYcEW:bt4c8sv) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1190)):*
> ```Python
>         user = self.get(user_id)
>         new_roles_set = set(new_roles)
>         current_roles = set(user.roles)
> ```

For consistency this should be perhaps be called current_roles_set.
___
*[`saltapi/repository/user_repository.py` line 1196 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QTZEn6pTxOBRd_oJa:-O0QTZEn6pTxOBRd_oJb:b-kjsx6b) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1196)):*
> ```Python
>         for role in roles_to_add:
>             if role == Role.SALT_ASTRONOMER:
>                 self._add_salt_astronomer(user.id)
> ```

Passing the user for the case of an SO and a user id for the case of an SA is somewhat inconsistent.
___
*[`saltapi/repository/user_repository.py` line 1203 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QT-xB4SeeO_iUmf-W:-O0QT-xB4SeeO_iUmf-X:b-hkisum) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1203)):*
> ```Python
>             self._update_right(user_id, right_setting, 2)
>         for role in roles_to_remove:
>             if role not in new_roles:
> ```

The condition `role not in new_roles` is always true.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)* status: all files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/user_repository.py` line 1124 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QOND41rY4yXq7k3rh:-O0nY5b8-CgGsVAmFnge:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

investigato > investigator

Also, this can be a private method.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1126 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QOi9jAG-VKMI6fA-0:-O0nYN22BWWng_R-RbeN:b-ar0drg) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1126)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If there are two Investigator entries for a PiptUser, you will get an error, as there are two entries (and `result.scalar_one` below will fail).

The correct SQL should be:

```
SELECT Investigator_Id FROM PiptUser WHERE PiptUser_Id = :user_id
```
</blockquote></details>

thank you forgot about this
Done.
___
*[`saltapi/repository/user_repository.py` line 1143 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QRpQm2sZrlriscPuf:-O0nYTve5W83cdCvinsu:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1143)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Too much whitespace after FROM
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1150 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QRstv-Q4j33ZqLNjt:-O0nYZ6g69_VfaACoi2C:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1150)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

oparator > operator
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1162 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QReTq-yVvT42tqHRt:-O0nYhY60XuKiU7Afncm:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

oparator > operator
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1164 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QRkI32qOtL5P8enMp:-O0nYiyg3rl3iBlEVVrr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1164)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Too much whitespace after FROM
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1190 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QSpbQ2UuSRxDmYcEV:-O0nYsTGCEIrDSyUBfHx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1190)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency this should be perhaps be called current_roles_set.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1196 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QTZEn6pTxOBRd_oJa:-O0nZAWrCmAQ5bYmyf1c:b-bt5mlz) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1196)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Passing the user for the case of an SO and a user id for the case of an SA is somewhat inconsistent.
</blockquote></details>

The requirements are different for both tables, And I don't want to query the user again
___
*[`saltapi/repository/user_repository.py` line 1203 at r5](https://reviewable.io/reviews/saltastroops/salt-api/306#-O0QT-xB4SeeO_iUmf-W:-O0nZjoJ5pqV3bESfcfB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f0c57671510668e4d1311f8b8b54d5e5843ecbdf/saltapi/repository/user_repository.py#L1203)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The condition `role not in new_roles` is always true.
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 368 at r4](https://reviewable.io/reviews/saltastroops/salt-api/306#-O-q-1s30gKFoJDqAT_Q:-O0NeqSU-Hxv8dpIZwy2:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/59e6fda2ee1d3d4781634fc868c059a12398e2e2/saltapi/web/api/users.py#L368)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

own > in
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/306)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
