### PR TITLE
Proposal submission

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/59)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
please run isort and bandit

> Reviewed 17 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-:-N1IKPEB-EAFPaYLJQW-:bjridjc)* status: 16 of 22 files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/settings.py` line 69 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IMKD70J9JlJIPDTFX:-N1IMKD93pqCnliznKHd:b-fz6y58) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/saltapi/settings.py#L69)):*
> ```Python
> 
>     # Python interpreter
>     python_interpreter: str
> ```

Do you really need this a environment variable
___
*[`saltapi/service/submission_service.py` line 3 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IJWN73fJ_sVpk-dPv:-N1IJWN73fJ_sVpk-dPw:bot11a0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/saltapi/service/submission_service.py#L3)):*
> ```Python
> import pathlib
> import re
> import subprocess
> ```

subprocess has possible security implications bandit sudgest so.
___
*[`saltapi/web/api/submissions.py` line 194 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IBv7l9XvhZyDg14Qe:-N1IBv7l9XvhZyDg14Qf:b4xutrw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/saltapi/web/api/submissions.py#L194)):*
> ```Python
>             return
> 
>         while True:
> ```

This loop should have a try count or try limit in case the code is stuck it can't  write the failed or accepeted somehow?
___
*[`tests/integration/submissions/test_submission_progress.py` line 86 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IEDG84KJlRPAx2uyb:-N1IEDG84KJlRPAx2uyc:btojjdp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/tests/integration/submissions/test_submission_progress.py#L86)):*
> dbconnection
I believe thisis two words 
dbconnection -> db_connection 
___
*[`tests/integration/submissions/test_submission_progress.py` line 104 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IGjnL0ANpo77kJF2d:-N1IGjnO9zSOvspEUQts:b-s0v9in) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/tests/integration/submissions/test_submission_progress.py#L104)):*
> ```Python
> 
> def test_submission_log_requires_existing_identifier(
>     dbconnection: Connection, client: TestClient, monkeypatch: pytest.MonkeyPatch
> ```

dbconnection -> db_connection 
___
*[`tests/integration/submissions/test_submission_progress.py` line 124 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IGl-BCpS9Fcauh0eP:-N1IGl-BCpS9Fcauh0eQ:b-s0v9in) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/tests/integration/submissions/test_submission_progress.py#L124)):*
> ```Python
> 
> def test_submission_log_can_only_be_accessed_by_submitter(
>     dbconnection: Connection, client: TestClient, monkeypatch: pytest.MonkeyPatch
> ```

dbconnection -> db_connection 
___
*[`tests/integration/submissions/test_submission_progress.py` line 178 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IGn0aCjSQLOPy66K_:-N1IGn0aCjSQLOPy66Ka:blv4et0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/tests/integration/submissions/test_submission_progress.py#L178)):*
> ```Python
>         Tuple[SubmissionStatus, List[Tuple[int, SubmissionMessageType]]]
>     ],
>     dbconnection: Connection,
> ```

dbconnection -> db_connection 
the same goes to every one

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/59)* status: 15 of 31 files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/settings.py` line 69 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IMKD70J9JlJIPDTFX:-N1Jfxvk7jf1tpPOeW9Z:b-7eg42o) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/saltapi/settings.py#L69)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Do you really need this a environment variable
</blockquote></details>

Yes. There is no guarantee that the required Python interpreter is the system one, and hence just assuming "python" might be wrong.
___
*[`saltapi/service/submission_service.py` line 3 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IJWN73fJ_sVpk-dPv:-N1JgGUo8UWZ3JIeiZFx:b6ae0l8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/saltapi/service/submission_service.py#L3)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

subprocess has possible security implications bandit sudgest so.
</blockquote></details>

Yes, but there is no way round launching a subprocess here. But in fact at least for the proposal code and username there should be some sanity check, which I have added now.
___
*[`saltapi/web/api/submissions.py` line 194 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IBv7l9XvhZyDg14Qe:-N1KUp8wEM8awgV3vkTe:b-jmqe3c) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/saltapi/web/api/submissions.py#L194)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

This loop should have a try count or try limit in case the code is stuck it can't  write the failed or accepeted somehow?
</blockquote></details>

I've added a five hour timeout.
___
*[`tests/integration/submissions/test_submission_progress.py` line 86 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IEDG84KJlRPAx2uyb:-N1KUuKKAEXeFTbuNTFX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/tests/integration/submissions/test_submission_progress.py#L86)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

> dbconnection
I believe thisis two words 
dbconnection -> db_connection 
</blockquote></details>

Done.
___
*[`tests/integration/submissions/test_submission_progress.py` line 104 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IGjnL0ANpo77kJF2d:-N1KUflJ40ZGEDOXx1dG:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/tests/integration/submissions/test_submission_progress.py#L104)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

dbconnection -> db_connection 
</blockquote></details>

Done.
___
*[`tests/integration/submissions/test_submission_progress.py` line 124 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IGl-BCpS9Fcauh0eP:-N1KUg9o-yW5u7kFewt2:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/tests/integration/submissions/test_submission_progress.py#L124)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

dbconnection -> db_connection 
</blockquote></details>

Done.
___
*[`tests/integration/submissions/test_submission_progress.py` line 178 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1IGn0aCjSQLOPy66K_:-N1KUh7Y-eI0NHsjRtjM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6ad033b73a7f1adeb4ad942e0d907e96c7715a41/tests/integration/submissions/test_submission_progress.py#L178)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

dbconnection -> db_connection 
the same goes to every one
</blockquote></details>

Done.

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1, 1 of 4 files at r4, 13 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/59)* status: 30 of 31 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/service/submission_service.py` line 184 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/59#-N1NN1HB47ps3JLABJ60:-N1NN1HC2ray_3CzSm-c:b-krb4x2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/033975bbf99397effbd4d8289a28a1bf1e80339d/saltapi/service/submission_service.py#L184)):*
> ```Python
>                 "The proposal code must only contain word characters and " "dashes."
>             )
>         if not re.match(r"^[\w-]+$", submitter.username):
> ```

I think you are missing the underscore

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/59)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
