### PR TITLE
Tests updates

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/226)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/226)* status: all files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`tests/integration/proposals/test_get_proposals.py` line 84 at r1](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV-gClz7ZkAcS9waeMH:-NV-gClz7ZkAcS9waeMI:benzvnq) ([raw file](https://github.com/saltastroops/salt-api/blob/29369365d8ca48249f26712071952baf1f389732/tests/integration/proposals/test_get_proposals.py#L84)):*
> ```Python
>             8,
>             (
>                 "2018-1-SCI-012, 2018-1-SCI-041, 2021-1-MLT-007, 2021-1-SCI-012, "
> ```

You've updated the number of proposals, but not the list of proposals. 
___
*[`tests/integration/proposals/test_get_proposals.py` line 94 at r1](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV-gRcH0qtoI3Wwgb9G:-NV-gRcH0qtoI3Wwgb9H:benzvnq) ([raw file](https://github.com/saltastroops/salt-api/blob/29369365d8ca48249f26712071952baf1f389732/tests/integration/proposals/test_get_proposals.py#L94)):*
> ```Python
>             9,
>             (
>                 "2018-2-LSP-001, 2018-2-MLT-005, 2020-1-MLT-005, 2020-1-MLT-009, "
> ```

You've updated the number of proposals, but not the list of proposals. 
___
*[`tests/repository/test_proposal_repository.py` line 565 at r1](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV-h9kE5FWLAExOVyVe:-NV-h9kE5FWLAExOVyVf:bn0ksnt) ([raw file](https://github.com/saltastroops/salt-api/blob/29369365d8ca48249f26712071952baf1f389732/tests/repository/test_proposal_repository.py#L565)):*
> ```Python
>     "proposal_code,proprietary_period,block_visits,expected_date",
>     [
>         ("2020-2-SCI-005", 0, [], date(2023, 11, 1)),
> ```

Just double-checking...: Have you double-checked these changes are genuine and not due to a bug?
___
*[`tests/repository/test_user_repository.py` line 336 at r1](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV-hT0ZErLX1rJv8T_C:-NV-hT0ZErLX1rJv8T_D:b5x7iic) ([raw file](https://github.com/saltastroops/salt-api/blob/05fec42d929d2cfcb14412b2dde504b88858f03e/tests/repository/test_user_repository.py#L336)):*
> ```Python
>         proposal_code=proposal_code,
>     )
>     non_grantee_username = find_usernames("proposal_view_grantee", True, proposal_code)[
> ```

I don't think that code should have been removed?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/226)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`tests/integration/proposals/test_get_proposals.py` line 84 at r1](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV-gClz7ZkAcS9waeMH:-NV2wx9X-njXtcyckrGK:bu4g7eh) ([raw file](https://github.com/saltastroops/salt-api/blob/29369365d8ca48249f26712071952baf1f389732/tests/integration/proposals/test_get_proposals.py#L84)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You've updated the number of proposals, but not the list of proposals. 
</blockquote></details>

Oh, I see. And it appears the repository function returns a duplicate entry/row for all the tests I altered the `proposal_count`.

This is weird because the SQL statement used in the repository function uses a select clause that uses a distinct keyword.

However, I am trying to investigate this.
___
*[`tests/integration/proposals/test_get_proposals.py` line 94 at r1](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV-gRcH0qtoI3Wwgb9G:-NV33cGZDsC0Zss3sSwv:b-apayz0) ([raw file](https://github.com/saltastroops/salt-api/blob/29369365d8ca48249f26712071952baf1f389732/tests/integration/proposals/test_get_proposals.py#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You've updated the number of proposals, but not the list of proposals. 
</blockquote></details>

See my comment above.
___
*[`tests/repository/test_proposal_repository.py` line 565 at r1](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV-h9kE5FWLAExOVyVe:-NV33rJ1AyX4eqdxN3RO:b7cvty1) ([raw file](https://github.com/saltastroops/salt-api/blob/29369365d8ca48249f26712071952baf1f389732/tests/repository/test_proposal_repository.py#L565)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Just double-checking...: Have you double-checked these changes are genuine and not due to a bug?
</blockquote></details>

No, I haven't but I am on it now and I found out that the repository function returns a duplicate entry.
___
*[`tests/repository/test_user_repository.py` line 336 at r1](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV-hT0ZErLX1rJv8T_C:-NV35Iw_CQOQMLe6tvIH:b-wle1hi) ([raw file](https://github.com/saltastroops/salt-api/blob/05fec42d929d2cfcb14412b2dde504b88858f03e/tests/repository/test_user_repository.py#L336)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that code should have been removed?
</blockquote></details>

Maybe let's discuss this.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/226)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 2546 at r2](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV8i4AF1Dzn4_nm8Ieq:-NV8i4AF1Dzn4_nm8Ier:b-tzncy3) ([raw file](https://github.com/saltastroops/salt-api/blob/bea8f9c8e5ea63a4cf0444f45c7535d3b3316b83/saltapi/repository/proposal_repository.py#L2546)):*
> ```Python
>         return cast(int, investigator_id[0])
> 
>     def _is_user_an_investigator(self, username: str, proposal_code: str) -> bool:
> ```

Moving the investigator check into a separate function leads to a significant increase in SQL queries - from what I can see you'd make an extra 1000 queries if you have a list of 1000 proposals...
___
*[`tests/repository/test_user_repository.py` line 334 at r2](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV8iy9F8G14pJ9nffhZ:-NV8iy9F8G14pJ9nffh_:b-v7e2ta) ([raw file](https://github.com/saltastroops/salt-api/blob/bea8f9c8e5ea63a4cf0444f45c7535d3b3316b83/tests/repository/test_user_repository.py#L334)):*
> ```Python
>     )
> 
>     non_grantee_username = find_usernames("proposal_view_grantee", True, proposal_code)[
> ```

From what I can see, this second test is same as the first one...

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/226)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2546 at r2](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV8i4AF1Dzn4_nm8Ieq:-NV9EOxh0FG2CBCDyS-v:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bea8f9c8e5ea63a4cf0444f45c7535d3b3316b83/saltapi/repository/proposal_repository.py#L2546)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Moving the investigator check into a separate function leads to a significant increase in SQL queries - from what I can see you'd make an extra 1000 queries if you have a list of 1000 proposals...
</blockquote></details>

Done.
___
*[`tests/repository/test_user_repository.py` line 334 at r2](https://reviewable.io/reviews/saltastroops/salt-api/226#-NV8iy9F8G14pJ9nffhZ:-NV9EQPaCqceW-d6dP7T:b-ad2dmm) ([raw file](https://github.com/saltastroops/salt-api/blob/bea8f9c8e5ea63a4cf0444f45c7535d3b3316b83/tests/repository/test_user_repository.py#L334)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

From what I can see, this second test is same as the first one...
</blockquote></details>

I have updated it.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/226)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 188 at r3](https://reviewable.io/reviews/saltastroops/salt-api/226#-NVE2fSr7W_3sg5i93Lk:-NVE2fSsDE47V8Kgl3Y-:bvwlb9z) ([raw file](https://github.com/saltastroops/salt-api/blob/243cc08f7072fd4f782f53d3ec69c7b95e75ac94/saltapi/repository/proposal_repository.py#L188)):*
> ```Python
>         ]
> 
>         unique_proposals = [
> ```

Wouldn't something like the following be easier?:

```
        # The list of proposals returned may contain proposals twice, once with
        # is_user_an_investigator=0 and once with is_user_an_investigator=1. In this
        # case only one of the two should be retained, and it should be the one with
        # is_user_an_investigator=1.
        unique_proposals_dict: Dict[str, Dict[str, Any]] = dict()
        for p in proposals:
            if p["id"] not in unique_proposals_dict or p["is_user_an_investigator"] == 1:
                unique_proposals_dict[p["id"]] = p
       unique_proposals = unique_proposals_dict.values()
```

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/226)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 188 at r3](https://reviewable.io/reviews/saltastroops/salt-api/226#-NVE2fSr7W_3sg5i93Lk:-NVE4tb-EHs0Mho_Gv6n:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/243cc08f7072fd4f782f53d3ec69c7b95e75ac94/saltapi/repository/proposal_repository.py#L188)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't something like the following be easier?:

```
        # The list of proposals returned may contain proposals twice, once with
        # is_user_an_investigator=0 and once with is_user_an_investigator=1. In this
        # case only one of the two should be retained, and it should be the one with
        # is_user_an_investigator=1.
        unique_proposals_dict: Dict[str, Dict[str, Any]] = dict()
        for p in proposals:
            if p["id"] not in unique_proposals_dict or p["is_user_an_investigator"] == 1:
                unique_proposals_dict[p["id"]] = p
       unique_proposals = unique_proposals_dict.values()
```
</blockquote></details>

Done.

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/226)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
