### PR TITLE
github-workflow

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Test Github Actions workflow

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/91)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/91)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`.github/workflows/test.yml` line 83 at r1](https://reviewable.io/reviews/saltastroops/salt-api/91#-NDSBruGBvnwbVwI6c-C:-NDSBruGBvnwbVwI6c-D:bcnn6gh) ([raw file](https://github.com/saltastroops/salt-api/blob/043c326c5f1669781bba4cfe21cbb2a4b53e81c1/.github/workflows/test.yml#L83)):*
> ```YAML
>           MAPPING_TOOL_PIPT_DIR: ''
>           MAPPING_TOOL_WEB_MANAGER_URL: https://www.salt.ac.za/wm/
>           MAPPING_TOOL_EPHEMERIS_URL: http://pysalt.salt.ac.za/finder_chart/ephemerides.cgi
> ```

Does this have to be the real value?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/91)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`.github/workflows/test.yml` line 83 at r1](https://reviewable.io/reviews/saltastroops/salt-api/91#-NDSBruGBvnwbVwI6c-C:-NDSS-BQ7a7ObkPMEIAM:bs37f9w) ([raw file](https://github.com/saltastroops/salt-api/blob/043c326c5f1669781bba4cfe21cbb2a4b53e81c1/.github/workflows/test.yml#L83)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Does this have to be the real value?
</blockquote></details>

Not really. However, one can't use an empty string or any string because they are type protected. Anyway, it does no harm to have them there, right?

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/91)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`.github/workflows/test.yml` line 83 at r1](https://reviewable.io/reviews/saltastroops/salt-api/91#-NDSBruGBvnwbVwI6c-C:-NDiHUA0A8ZPpZv_doA-:bvhfhdn) ([raw file](https://github.com/saltastroops/salt-api/blob/043c326c5f1669781bba4cfe21cbb2a4b53e81c1/.github/workflows/test.yml#L83)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Not really. However, one can't use an empty string or any string because they are type protected. Anyway, it does no harm to have them there, right?
</blockquote></details>

Probably not... But on the other hand, it does no harm to have fake values, and this would minimise the risk of inadvertently accessing real data...

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/91)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`.github/workflows/test.yml` line 83 at r1](https://reviewable.io/reviews/saltastroops/salt-api/91#-NDSBruGBvnwbVwI6c-C:-NDiHUA0A8ZPpZv_doA-:bvhfhdn) ([raw file](https://github.com/saltastroops/salt-api/blob/043c326c5f1669781bba4cfe21cbb2a4b53e81c1/.github/workflows/test.yml#L83)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Not really. However, one can't use an empty string or any string because they are type protected. Anyway, it does no harm to have them there, right?
</blockquote></details>

Probably not... But on the other hand, it does no harm to have fake values, and this would minimise the risk of inadvertently accessing real data...

**Comment by mofokeng-chaka** [comment]
Done.

**Pull request merged**
