### PR TITLE
Downloading proposal progress PDF

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/99)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/99)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/util.py` line 153 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGpp8k9GRwhfBmmqK7:-NEGpp8k9GRwhfBmmqK8:bk2j8k5) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/util.py#L153)):*
> ```Python
> 
> 
> def proposal_progress_clean_up():
> ```

I think you could omit this function and use a lambda function instead where required.
___
*[`saltapi/service/proposal_service.py` line 231 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGuAHA3mzM9mGqJ_C8:-NEGuAHBCK7wn6-unxR3:bc9wipg) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/service/proposal_service.py#L231)):*
> ```Python
>         }
>         with PdfFileMerger(strict=False) as merger:
>             if progress_report_pdfs["proposal_progress_pdf"]:
> ```

Even if it is allowed to call this function if there is no pdf, shouldn't you return even before the `with` in this case. avoiding to create a file at all? (Admittedly this might be a bit more painful, as you cannot use `FileResponse` then; but you could still use `Response` with a `content` attribute and sent the relevant HTTP header yourself...)
___
*[`saltapi/service/proposal_service.py` line 235 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGqHUKAQPeCmxODyeY:-NEGqHUKAQPeCmxODyeZ:bpe0274) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/service/proposal_service.py#L235)):*
> ```Python
>                 if progress_report_pdfs["additional_pdf"]:
>                     merger.append(progress_report_pdfs["additional_pdf"])
>                 merger.write("tmp_proposal_progress.pdf")
> ```

This is likely to fail, as the web server won't be allowed to write the temporary file. Also, you run there risk of two processes trying to access the same file.

So I'd suggest you use `tempfile.mkstemp` to create the temporary file.

Alternatively, can't you use a `BytesIO` with the `write` method (and rewind it with `seek(0)` afterwards)?
___
*[`saltapi/web/api/proposal_progress.py` line 159 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGvvPs1dXulPLe8tAR:-NEGvvPt5iPguYQh_Sd9:b-b70vkt) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/web/api/proposal_progress.py#L159)):*
> ```Python
>     semester: Semester = Path(..., title="Semester", description="Semester"),
>     user: User = Depends(get_current_user),
> ) -> Optional[FileResponse]:
> ```

I don't think this should be optional. If there is no pdf, a 404 error might be more appropriate.
___
*[`saltapi/web/api/proposal_progress.py` line 172 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGubJZ-kn1ovNThoYX:-NEGubJZ-kn1ovNThoYY:b-dllxps) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/web/api/proposal_progress.py#L172)):*
> ```Python
>             )
>         filename = f"ProposalProgressReport-{semester}.pdf"
>         if exists("tmp_proposal_progress.pdf"):
> ```

I'd suggest the return value of the `create_proposal_progress_pdf` function should indicate whether a pdf was created.
___
*[`saltapi/web/api/proposal_progress.py` line 196 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGwp7x1BEBi9BORUfI:-NEGwp7x1BEBi9BORUfJ:b-b70vkt) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/web/api/proposal_progress.py#L196)):*
> ```Python
>     semester: Semester = Path(..., title="Semester", description="Semester"),
>     user: User = Depends(get_current_user),
> ) -> Optional[FileResponse]:
> ```

I don't think this should be optional. If there is no pdf, a 404 error might be more appropriate.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/99)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/proposal_service.py` line 231 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGuAHA3mzM9mGqJ_C8:-NEfSbaP6ikju083mN2E:bgpxg56) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/service/proposal_service.py#L231)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Even if it is allowed to call this function if there is no pdf, shouldn't you return even before the `with` in this case. avoiding to create a file at all? (Admittedly this might be a bit more painful, as you cannot use `FileResponse` then; but you could still use `Response` with a `content` attribute and sent the relevant HTTP header yourself...)
</blockquote></details>

Discussed
___
*[`saltapi/service/proposal_service.py` line 235 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGqHUKAQPeCmxODyeY:-NEfSdfSE1pwyznqkuGI:bgpxg56) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/service/proposal_service.py#L235)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is likely to fail, as the web server won't be allowed to write the temporary file. Also, you run there risk of two processes trying to access the same file.

So I'd suggest you use `tempfile.mkstemp` to create the temporary file.

Alternatively, can't you use a `BytesIO` with the `write` method (and rewind it with `seek(0)` afterwards)?
</blockquote></details>

Discussed
___
*[`saltapi/web/api/proposal_progress.py` line 159 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGvvPs1dXulPLe8tAR:-NEeh6TN-MOipzY6xfAv:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/web/api/proposal_progress.py#L159)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this should be optional. If there is no pdf, a 404 error might be more appropriate.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 172 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGubJZ-kn1ovNThoYX:-NEfE_jk8yM_iOlhQ1EM:bmva9jk) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/web/api/proposal_progress.py#L172)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest the return value of the `create_proposal_progress_pdf` function should indicate whether a pdf was created.
</blockquote></details>

it will raise error if nothing is created.
___
*[`saltapi/web/api/proposal_progress.py` line 196 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGwp7x1BEBi9BORUfI:-NEfFcmm-_V9-dkXVA8w:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/web/api/proposal_progress.py#L196)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this should be optional. If there is no pdf, a 404 error might be more appropriate.
</blockquote></details>

Done.
___
*[`saltapi/util.py` line 153 at r1](https://reviewable.io/reviews/saltastroops/salt-api/99#-NEGpp8k9GRwhfBmmqK7:-NEfSLZb-K_HuUjgmx2k:b-cqr6t5) ([raw file](https://github.com/saltastroops/salt-api/blob/deb9de2ad6d70e9e1ce33fb1bcd1fb8e2c28ae1a/saltapi/util.py#L153)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you could omit this function and use a lambda function instead where required.
</blockquote></details>


Method no longer needed. Removed

**Review by hettlage — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/99)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/99)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
