### PR TITLE
Fixed listing issues

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/31)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/31)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[saltapi/main.py, line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-MlyVVVsARj79BuvWmGP:-MlyVVVtBDKITgpCTtaQ:b5a5om9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/14eb2febdaab73b821ed23e789dae759010ef039/saltapi/main.py#L1)):*
> ```Python
> from fastapi import FastAPI, Request, Response
> ```

Sorry, but it seems flake8 is still failing (not necessarily for main.py).

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/31)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[saltapi/main.py, line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-MlyVVVsARj79BuvWmGP:-Mlytff6AcJh45vjX1_P:bdq77a) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/14eb2febdaab73b821ed23e789dae759010ef039/saltapi/main.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, but it seems flake8 is still failing (not necessarily for main.py).
</blockquote></details>

I am not sure how I missed it. It must be fine now

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/31)* status: all files reviewed, 6 unresolved discussions (waiting on @mofokeng-chaka)

___
*[tests/conftest.py, line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-ARvf70ARwsaSQrBM:-Mm-ARvf70ARwsaSQrBN:b-f47eol) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/14eb2febdaab73b821ed23e789dae759010ef039/tests/conftest.py#L1)):*
> ```Python
> import os
> ```

Now flake8 is failing for this file.
___
*[tests/conftest.py, line 5 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-BsieCHZHKDvWsSeF:-Mm-BsieCHZHKDvWsSeG:ba0vis5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/14eb2febdaab73b821ed23e789dae759010ef039/tests/conftest.py#L5)):*
> ```Python
> import dotenv
> 
> # Make sure that the test database etc. are used.
> ```

There seem to be quite a few failing tests,..
___
*[tests/conftest.py, line 7 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-B4xQAaG1GW_C3cyL:-Mm-B4xQAaG1GW_C3cyM:bik2m7p) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6b36e45e1384b245617afc4a81711d788de784d/tests/conftest.py#L7)):*
> ```Python
> # Make sure that the test database etc. are used.
> # IMPORTANT: These lines must be executed before any server-related package is imported.
> os.environ["DOTENV_FILE"] = "tests/.env.test"
> ```

The value was `.env.test` before, and I think it should stay that way. It makes sense to have all `.env` files at roost level.
___
*[tests/repository/test_block_repository.py, line 15 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-5eMT85lgXk3lNM8u:-Mm-5eMT85lgXk3lNM8v:b30nq83) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6b36e45e1384b245617afc4a81711d788de784d/tests/repository/test_block_repository.py#L15)):*
> ```Python
> from tests.markers import nodatabase
> 
> TEST_DATA = "../saltapi-testdata/repository/block_repository.yaml"
> ```

"../saltapi-testdata" should not be part of the value. This directory should be set in the TEST_DATA_DIR environment variable.
___
*[tests/repository/test_block_repository.py, line 432 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-8Dm3BL1znvx2p-vA:-Mm-8Dm429dd-qw0slnK:bq2u5ad) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6b36e45e1384b245617afc4a81711d788de784d/tests/repository/test_block_repository.py#L432)):*
> ```Python
>     dbconnection: Connection, testdata: Callable[[str], Any]
> ) -> None:
>     data = testdata(TEST_DATA)["block_visit"]
> ```

I think one should arguably have dedicated test data for the block visit status, not least because the block visit test data does not cover the status "in queue".

It might also be worth having a test showing that deleted block visits are not found in a block visit search, and cannot be updated.
___
*[tests/repository/test_user_repository.py, line 17 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-9fCT6aAcZpNjlvFo:-Mm-9fCT6aAcZpNjlvFp:bl824po) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6b36e45e1384b245617afc4a81711d788de784d/tests/repository/test_user_repository.py#L17)):*
> ```Python
> 
> 
> def create_block_repository(connection: Connection) -> BlockRepository:
> ```

This function doesn't seem to be used.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/31)* status: 6 of 16 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[tests/conftest.py, line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-ARvf70ARwsaSQrBM:-Mm1h89f2Cx5-yFb8isp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/14eb2febdaab73b821ed23e789dae759010ef039/tests/conftest.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Now flake8 is failing for this file.
</blockquote></details>

Done.
___
*[tests/conftest.py, line 5 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-BsieCHZHKDvWsSeF:-Mm27RrOBwr7CjUDoxBg:bv0ujuz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/14eb2febdaab73b821ed23e789dae759010ef039/tests/conftest.py#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There seem to be quite a few failing tests,..
</blockquote></details>

I have fixed them now, and they are passing now except for BDD tests
___
*[tests/conftest.py, line 7 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-B4xQAaG1GW_C3cyL:-Mm27v844kgWTqtU7yy_:b-qe8jjp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6b36e45e1384b245617afc4a81711d788de784d/tests/conftest.py#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The value was `.env.test` before, and I think it should stay that way. It makes sense to have all `.env` files at roost level.
</blockquote></details>

By root level, you mean tests/ directory, right? If so, that is where I have put it, but for some reason, it is not being picked up unless I add tests/ to the path.
___
*[tests/repository/test_block_repository.py, line 15 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-5eMT85lgXk3lNM8u:-Mm27OGu8dPgzGSbuCuq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6b36e45e1384b245617afc4a81711d788de784d/tests/repository/test_block_repository.py#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"../saltapi-testdata" should not be part of the value. This directory should be set in the TEST_DATA_DIR environment variable.
</blockquote></details>

Done.
___
*[tests/repository/test_block_repository.py, line 432 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-8Dm3BL1znvx2p-vA:-Mm26yiR1ED7esMs9tmC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6b36e45e1384b245617afc4a81711d788de784d/tests/repository/test_block_repository.py#L432)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think one should arguably have dedicated test data for the block visit status, not least because the block visit test data does not cover the status "in queue".

It might also be worth having a test showing that deleted block visits are not found in a block visit search, and cannot be updated.
</blockquote></details>

Done.
___
*[tests/repository/test_user_repository.py, line 17 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-9fCT6aAcZpNjlvFo:-Mm1y35r3xVSDJsnFsl-:ba3dfob) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6b36e45e1384b245617afc4a81711d788de784d/tests/repository/test_user_repository.py#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This function doesn't seem to be used.
</blockquote></details>

Removed

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/31)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[tests/conftest.py, line 5 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-BsieCHZHKDvWsSeF:-Mm2PlS_EQsiyfFproJP:b-hu2z7e) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/14eb2febdaab73b821ed23e789dae759010ef039/tests/conftest.py#L5)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have fixed them now, and they are passing now except for BDD tests
</blockquote></details>

I still get failing tests for tests/repository/test_proposal_repository.py
___
*[tests/conftest.py, line 7 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-B4xQAaG1GW_C3cyL:-Mm2PzMODwUo3HEeFD5R:b-9xifa5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6b36e45e1384b245617afc4a81711d788de784d/tests/conftest.py#L7)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

By root level, you mean tests/ directory, right? If so, that is where I have put it, but for some reason, it is not being picked up unless I add tests/ to the path.
</blockquote></details>

No, I mean the root level of the project, i.e. the directory containing the tests directory.
___
*[tests/repository/test_block_repository.py, line 479 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm2ys-Y6cmD4ECWmRNF:-Mm2ys-Z5FOT9esriz6J:b1g36a) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5c4031bc6ef7cd46f1b284b9c4c25be3c894089a/tests/repository/test_block_repository.py#L479)):*
> ```Python
> 
> @nodatabase
> def test_update_block_visit_status_raises_error_for_wrong_block_status(
> ```

I think you should say "deleted" rather than "wrong".

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/31)* status: 11 of 17 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[tests/conftest.py, line 5 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-BsieCHZHKDvWsSeF:-MmBzPXOAWMlrgQuzYyp:ba93qnz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/14eb2febdaab73b821ed23e789dae759010ef039/tests/conftest.py#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I still get failing tests for tests/repository/test_proposal_repository.py
</blockquote></details>

In my case, the error(s) I am getting from that script (and some from tests/repository/test_block_repository), all have to do with the "UPDATE" command tests because the user "piptwebmanager" is not permitted to do updates on the database
___
*[tests/conftest.py, line 7 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm-B4xQAaG1GW_C3cyL:-MmBz5Zp2IzTQ12fafg0:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6b36e45e1384b245617afc4a81711d788de784d/tests/conftest.py#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No, I mean the root level of the project, i.e. the directory containing the tests directory.
</blockquote></details>

Done.
___
*[tests/repository/test_block_repository.py, line 479 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/31#-Mm2ys-Y6cmD4ECWmRNF:-MmBy3Ci0cQEXygsbq41:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5c4031bc6ef7cd46f1b284b9c4c25be3c894089a/tests/repository/test_block_repository.py#L479)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you should say "deleted" rather than "wrong".
</blockquote></details>

Done.

**Comment by mofokeng-chaka** [comment]
:lgtm:

**Review by hettlage — APPROVED** [review]
> Reviewed 5 of 6 files at r4, 2 of 2 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
