### PR TITLE
Add proposal approval repository function

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/204)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/204)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 132 at r3](https://reviewable.io/reviews/saltastroops/salt-api/204#-NQf2Fdl6kHsHY_cy-bL:-NQf2Fdl6kHsHY_cy-bM:bcj0612) ([raw file](https://github.com/saltastroops/salt-api/blob/28d9bbe1440a0daa5da84c51fda0b27606b826e0/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L132)):*
> ```Python
> 
> 
> def test_investigator_approval_proposal_status_update_for_an_administrator(
> ```

Can't you combine `test_investigator_approval_proposal_status_update_for_an_administrator` and `test_investigator_approval_proposal_status_update_for_an_investigator`? It looks like a case for parametrisation to me... :-)
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 154 at r3](https://reviewable.io/reviews/saltastroops/salt-api/204#-NQf26vAE8Bw1VS5okEG:-NQf26vAE8Bw1VS5okEH:bpko2hi) ([raw file](https://github.com/saltastroops/salt-api/blob/28d9bbe1440a0daa5da84c51fda0b27606b826e0/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L154)):*
> ```Python
>     proposal = resp.json()
> 
>     investigator = [i for i in proposal["investigators"] if i["id"] == user_id]
> ```

investigator > investigators
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 183 at r3](https://reviewable.io/reviews/saltastroops/salt-api/204#-NQf2-wu9b6I6bblSwKP:-NQf2-wy7BP6R293gkcU:bpko2hi) ([raw file](https://github.com/saltastroops/salt-api/blob/28d9bbe1440a0daa5da84c51fda0b27606b826e0/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L183)):*
> ```Python
>     proposal = resp.json()
> 
>     investigator = [i for i in proposal["investigators"] if i["id"] == user_id]
> ```

investigator > investigators

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/204)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 132 at r3](https://reviewable.io/reviews/saltastroops/salt-api/204#-NQf2Fdl6kHsHY_cy-bL:-NQzTUu00guzNttQFRSm:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/28d9bbe1440a0daa5da84c51fda0b27606b826e0/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L132)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can't you combine `test_investigator_approval_proposal_status_update_for_an_administrator` and `test_investigator_approval_proposal_status_update_for_an_investigator`? It looks like a case for parametrisation to me... :-)
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 154 at r3](https://reviewable.io/reviews/saltastroops/salt-api/204#-NQf26vAE8Bw1VS5okEG:-NQzTVZdEKZQI534h4qt:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/28d9bbe1440a0daa5da84c51fda0b27606b826e0/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L154)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

investigator > investigators
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 183 at r3](https://reviewable.io/reviews/saltastroops/salt-api/204#-NQf2-wu9b6I6bblSwKP:-NQzThT_DXKxCxmcjwxD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/28d9bbe1440a0daa5da84c51fda0b27606b826e0/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L183)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

investigator > investigators
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/204)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 151 at r5](https://reviewable.io/reviews/saltastroops/salt-api/204#-NR-8TlK52QdXxXa63bW:-NR-8TlL4_Zi-rJQqARp:b4cx5m) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdc4e8d75744914168613815441f9e8f14438cb/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L151)):*
> ```Python
> 
>     response = client.put(
>         f"{PROPOSALS_URL}/{proposal_code}/approvals/{investigator_id}",
> ```

"investigator_id" should probably be "user_id"
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 166 at r5](https://reviewable.io/reviews/saltastroops/salt-api/204#-NR-8iBf3siQojID6021:-NR-8iBf3siQojID6022:b-x3n5ft) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdc4e8d75744914168613815441f9e8f14438cb/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L166)):*
> ```Python
>     has_approved_proposal = investigators[0]["has_approved_proposal"]
> 
>     assert has_approved_proposal if approved else not has_approved_proposal
> ```

There is an issue, though: The initial status might be equal to the final one, and then you haven't tested that you can actually change it. So it might nee a good idea to add another status update to `not approved` and check that this second update worked as well.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/204)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 151 at r5](https://reviewable.io/reviews/saltastroops/salt-api/204#-NR-8TlK52QdXxXa63bW:-NR6b1AI5BhtMmruXNjl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdc4e8d75744914168613815441f9e8f14438cb/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L151)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"investigator_id" should probably be "user_id"
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 166 at r5](https://reviewable.io/reviews/saltastroops/salt-api/204#-NR-8iBf3siQojID6021:-NR6b2b54FLfwy9H_70x:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdc4e8d75744914168613815441f9e8f14438cb/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L166)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is an issue, though: The initial status might be equal to the final one, and then you haven't tested that you can actually change it. So it might nee a good idea to add another status update to `not approved` and check that this second update worked as well.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
