### PR TITLE
Switch user

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/171)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r2, 2 of 6 files at r3, 13 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/171)* status: 16 of 19 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 328 at r4](https://reviewable.io/reviews/saltastroops/salt-api/171#-NOE24Sf2YzzTwzzmhDp:-NOE24Sg5GX5JvTXJzAU:b4cn16g) ([raw file](https://github.com/saltastroops/salt-api/blob/923abdc68068cdcce62cad929a1f17ba6a81f74a/saltapi/service/permission_service.py#L328)):*
> ```Python
>             )
> 
>     def check_permission_to_switch_user(self, user: User) -> None:
> ```

This and the below method ` check_permission_to_view_users`  are doing the exact same thing can't we reuse the other one?
___
*[`saltapi/web/schema/user.py` line 108 at r4](https://reviewable.io/reviews/saltastroops/salt-api/171#-NOE41nx2YGSdMLqZoaK:-NOE41nx2YGSdMLqZoaL:b-uymjz0) ([raw file](https://github.com/saltastroops/salt-api/blob/923abdc68068cdcce62cad929a1f17ba6a81f74a/saltapi/web/schema/user.py#L108)):*
> ```Python
>     """Username of the user to switch to."""
> 
>     username: str = Field(
> ```

wouldn't it help if we could use an email together with the username in case you do not know the username

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 1 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/171)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @hettlage)

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/171)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/service/permission_service.py` line 328 at r4](https://reviewable.io/reviews/saltastroops/salt-api/171#-NOE24Sf2YzzTwzzmhDp:-NOE8R8n-sGg2abZoEVA:b-kgrbcc) ([raw file](https://github.com/saltastroops/salt-api/blob/923abdc68068cdcce62cad929a1f17ba6a81f74a/saltapi/service/permission_service.py#L328)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

This and the below method ` check_permission_to_view_users`  are doing the exact same thing can't we reuse the other one?
</blockquote></details>

No, I don't think so. There is no reason why the permission for viewing users and switching users should be the same.
___
*[`saltapi/web/schema/user.py` line 108 at r4](https://reviewable.io/reviews/saltastroops/salt-api/171#-NOE41nx2YGSdMLqZoaK:-NOE8z5T5CF4R4I6zk-u:bd6uw0o) ([raw file](https://github.com/saltastroops/salt-api/blob/923abdc68068cdcce62cad929a1f17ba6a81f74a/saltapi/web/schema/user.py#L108)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

wouldn't it help if we could use an email together with the username in case you do not know the username
</blockquote></details>

I don't think so. I think you'd have to look up either of the two anyway...

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 2 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
