### PR TITLE
Adding MOS slit mask

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/334)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/334)* status: all files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/downloads.py` line 15 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAtg6W6RqgzYgsSu18:-OBAtg6W6RqgzYgsSu19:bwhdwl6) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/api/downloads.py#L15)):*
> ```Python
> 
> @router.get("/slit-mask-xml/{proposal_code}/{filename}", summary="Get a slit mask XML")
> async def download_xml_file(
> ```

I'm not so convinced about the `/downloads` prefix.
___
*[`saltapi/web/api/downloads.py` line 35 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAuGVY-tfm1Oe6ZiUC:-OBAuGVY-tfm1Oe6ZiUD:bz6al9) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/api/downloads.py#L35)):*
> ```Python
>         download_services = services.download_service(unit_of_work.connection)
>         file_path = download_services.get_slit_mask_xml_path(proposal_code) / filename
> ```

You aren't checking permissions.
___
*[`saltapi/web/api/downloads.py` line 63 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAuiPgDckz5EWGAW6a:-OBAuiPgDckz5EWGAW6b:bz6al9) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/api/downloads.py#L63)):*
> ```Python
> 
>     with UnitOfWork() as unit_of_work:
>         download_services = services.download_service(unit_of_work.connection)
> ```

You aren't checking permissions.
___
*[`saltapi/web/api/downloads.py` line 77 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAuyODBIGdEr56TliJ:-OBAuyODBIGdEr56TliK:b-zdyj9s) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/api/downloads.py#L77)):*
> ```Python
>         elif filename.endswith(".svg"):
>             media_type = "image/svg+xml"
>         elif filename.endswith(".bmp"):
> ```

There is an easier way of doing this: https://docs.python.org/3/library/mimetypes.html

Also, this belongs into the service class rather.
___
*[`saltapi/repository/download_repository.py` line 4 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAsIPr6aCE1g0PO94F:-OBAsIPr6aCE1g0PO94G:b-3ov3cq) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/repository/download_repository.py#L4)):*
> ```Python
> 
> 
> class DownloadRepository:
> ```

Does this class do anything? :-)
___
*[`saltapi/service/download_service.py` line 11 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAtTat8tCXd10GSioQ:-OBAtTat8tCXd10GSioR:b-3raeu7) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/service/download_service.py#L11)):*
> ```Python
> class DownloadService:
>     def __init__(self, download_repository: DownloadRepository):
>         self.download_repository = download_repository
> ```

There is no need for the download repository, is there?
___
*[`saltapi/service/download_service.py` line 14 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAsly4DrY03K1Tnm4h:-OBAsly4DrY03K1Tnm4i:bibsix8) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/service/download_service.py#L14)):*
> ```Python
> 
>     @staticmethod
>     def get_slit_mask_xml_path(proposal_code: str) -> pathlib.Path:
> ```

Both methods return the same, and they have nothing to do with masks as such. It's rather a method `get_propoal_attachments_dir` or something like that.
___
*[`saltapi/web/schema/rss.py` line 146 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAvd3lBgWy2cpViyUC:-OBAvd3lBgWy2cpViyUD:b-ue4hso) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/schema/rss.py#L146)):*
> ```Python
>         description="Comment regarding the production and handling of the mask",
>     )
>     plot_filename: Optional[str] = Field(
> ```

Wouldn't it be better to return the URL for the plot file?
___
*[`saltapi/web/schema/rss.py` line 151 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAvn_B7AO8OszLsGW6:-OBAvn_B7AO8OszLsGW7:b-ue4hso) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/schema/rss.py#L151)):*
> ```Python
>         description="The filename of the Slit Mask plot file.",
>     )
>     xml_filename: Optional[str] = Field(
> ```

Wouldn't it be better to return the URL for the plot file?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/334)* status: 1 of 9 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/schema/rss.py` line 146 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAvd3lBgWy2cpViyUC:-OC7Yj5W3ZsKUznChhqN:b2wjwcr) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/schema/rss.py#L146)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't it be better to return the URL for the plot file?
</blockquote></details>

This change will complicate the code for downloading a file.

please see current changes 
___
*[`saltapi/web/schema/rss.py` line 151 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAvn_B7AO8OszLsGW6:-OC7_FSdAnlXtyTtyBcN:b-5y8vqy) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/schema/rss.py#L151)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't it be better to return the URL for the plot file?
</blockquote></details>

his change will complicate the code for downloading a file.

please see current changies
___
*[`saltapi/repository/download_repository.py` line 4 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAsIPr6aCE1g0PO94F:-OCCdETf5nEoCSbtcswP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/repository/download_repository.py#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Does this class do anything? :-)
</blockquote></details>

Done.
___
*[`saltapi/service/download_service.py` line 11 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAtTat8tCXd10GSioQ:-OCCdIQM4DkUCePXiR8r:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/service/download_service.py#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is no need for the download repository, is there?
</blockquote></details>

Done.
___
*[`saltapi/service/download_service.py` line 14 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAsly4DrY03K1Tnm4h:-OCCdInt7eFsIllYpUdR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/service/download_service.py#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Both methods return the same, and they have nothing to do with masks as such. It's rather a method `get_propoal_attachments_dir` or something like that.
</blockquote></details>

Done.
___
*[`saltapi/web/api/downloads.py` line 15 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAtg6W6RqgzYgsSu18:-OCCqrpw4ho2N_jm5EEO:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/api/downloads.py#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not so convinced about the `/downloads` prefix.
</blockquote></details>

removed
___
*[`saltapi/web/api/downloads.py` line 35 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAuGVY-tfm1Oe6ZiUC:-OCCqteYD6ZgKFkdWzqp:b-k0bkwn) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/api/downloads.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You aren't checking permissions.
</blockquote></details>

now checking
___
*[`saltapi/web/api/downloads.py` line 63 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAuiPgDckz5EWGAW6a:-OCCqwGy-CbSpj4KkDii:b-k0bkwn) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/api/downloads.py#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You aren't checking permissions.
</blockquote></details>

now checking
___
*[`saltapi/web/api/downloads.py` line 77 at r2](https://reviewable.io/reviews/saltastroops/salt-api/334#-OBAuyODBIGdEr56TliJ:-OCCqyOy2QzyVZl531Po:bxmkmrw) ([raw file](https://github.com/saltastroops/salt-api/blob/40ca79f3fb4b37c9a7b2b21a48cbb77626801e03/saltapi/web/api/downloads.py#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is an easier way of doing this: https://docs.python.org/3/library/mimetypes.html

Also, this belongs into the service class rather.
</blockquote></details>

using it

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/334)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/proposals.py` line 696 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEBASO12s9HF7KVv2_:-OCEBASO12s9HF7KVv2a:bu0dkcn) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L696)):*
> ```Python
>         unit_of_work.commit()
> 
> @router.get("/{proposal_code}/attached/{filename}", summary="Download the attached files of a proposal")
> ```

It might be more consistent to use a noun instead of "attached":

"/{proposal_code}/attachments/{filename}"
___
*[`saltapi/web/api/proposals.py` line 697 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEBPr_8qbG2FIBdFlO:-OCEBPr_8qbG2FIBdFlP:b-yl2gsk) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L697)):*
> ```Python
> 
> @router.get("/{proposal_code}/attached/{filename}", summary="Download the attached files of a proposal")
> async def download_attached_files(
> ```

The name should be `download_attachment` or `download_attached_file`, as only one file is downloaded.

And I'm not convinced the `download_` part -- the method isn't downloading anything, after all. :-)
___
*[`saltapi/web/api/proposals.py` line 708 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEC3Jk8o-dmdNDTNSW:-OCEC3Jk8o-dmdNDTNSX:bs7p94t) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L708)):*
> ```Python
>             description=(
>                     "Name of the file to download, as a unique identifier and a "
>                     "suffix, such as 1234.jpg."
> ```

I don't think the description of the filename is correct?
___
*[`saltapi/web/api/proposals.py` line 727 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCECVpj3UvDsFs2c_xk:-OCECVpj3UvDsFs2c_xl:bfwkmb8) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L727)):*
> ```Python
> 
>         if not media_type:
>             raise HTTPException(status_code=400, detail="Unsupported image format")
> ```

image format > file format -- it might not be an image
___
*[`saltapi/web/api/proposals.py` line 729 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEChSw-ArLhvL0EiVw:-OCEChSw-ArLhvL0EiVx:b-olsqyk) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L729)):*
> ```Python
>             raise HTTPException(status_code=400, detail="Unsupported image format")
> 
>         # Serve the file as a response for download
> ```

Maybe just "Serve the file"?
___
*[`saltapi/web/schema/rss.py` line 147 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEDAkY4JeMBfcRSkaJ:-OCEDAkY4JeMBfcRSkaK:by1wuex) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/schema/rss.py#L147)):*
> ```Python
>         title="Plot filename",
>         description=(
>             "The filename of the Slit Mask plot file. "
> ```

Slit Mask > slit mask

'. "' > '."'
___
*[`saltapi/web/schema/rss.py` line 148 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCECzJh81iStOwS1SGS:-OCECzJh81iStOwS1SGT:b-d9cpte) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/schema/rss.py#L148)):*
> ```Python
>         description=(
>             "The filename of the Slit Mask plot file. "
>             "This file is downloadable on /PROPOSAL_CODE/attached/THIS_FILENAME"
> ```

on > from ?

The URL might have to be updated (see my comment elsewhere).
___
*[`saltapi/web/schema/rss.py` line 155 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEDWAfB35a3Vz_Lzgb:-OCEDWAg3Dh7SjHvbHbl:by1wuex) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/schema/rss.py#L155)):*
> ```Python
>         title="XML filename",
>         description=(
>             "The filename of the Slit Mask XML file. "
> ```

Slit Mask > slit mask

'. "' > '."'
___
*[`saltapi/web/schema/rss.py` line 156 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEDcSMCBO02ish7HgF:-OCEDcSMCBO02ish7HgG:bictkrr) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/schema/rss.py#L156)):*
> ```Python
>         description=(
>             "The filename of the Slit Mask XML file. "
>             "This file is downloadable on /PROPOSAL_CODE/attached/THIS_FILENAME"
> ```

on > from ?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/334)* status: all files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/api/proposals.py` line 696 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEBASO12s9HF7KVv2_:-OCXqXDx8XW9ksj9QcoR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L696)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be more consistent to use a noun instead of "attached":

"/{proposal_code}/attachments/{filename}"
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 697 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEBPr_8qbG2FIBdFlO:-OCXfQvLEva7vasV7X9Z:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L697)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name should be `download_attachment` or `download_attached_file`, as only one file is downloaded.

And I'm not convinced the `download_` part -- the method isn't downloading anything, after all. :-)
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 708 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEC3Jk8o-dmdNDTNSW:-OCXrvjI3l8kSOLzPzJo:b-qssebl) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L708)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the description of the filename is correct?
</blockquote></details>

fixed.
___
*[`saltapi/web/api/proposals.py` line 727 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCECVpj3UvDsFs2c_xk:-OCXqvF64etFrJD1AqwA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L727)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

image format > file format -- it might not be an image
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 729 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEChSw-ArLhvL0EiVw:-OCXqzpq8EDGqU0vyHHH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L729)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe just "Serve the file"?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/rss.py` line 147 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEDAkY4JeMBfcRSkaJ:-OCXrPWO92fyKFb_vxnU:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/schema/rss.py#L147)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Slit Mask > slit mask

'. "' > '."'
</blockquote></details>

Done.
___
*[`saltapi/web/schema/rss.py` line 148 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCECzJh81iStOwS1SGS:-OCXrPs-9k7zmtcMRjfr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/schema/rss.py#L148)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

on > from ?

The URL might have to be updated (see my comment elsewhere).
</blockquote></details>

Done.
___
*[`saltapi/web/schema/rss.py` line 155 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEDWAfB35a3Vz_Lzgb:-OCXreKvBwVKLiEosB5e:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/schema/rss.py#L155)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Slit Mask > slit mask

'. "' > '."'
</blockquote></details>

Done.
___
*[`saltapi/web/schema/rss.py` line 156 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEDcSMCBO02ish7HgF:-OCXrdo97tYQ3qNkiEWT:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/schema/rss.py#L156)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

on > from ?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/334)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/proposals.py` line 697 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEBPr_8qbG2FIBdFlO:-OCcEgEe5vb0z-KJ7PVP:b9s0qm1) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L697)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm still not convinced about the `download_`.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/334)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/web/api/proposals.py` line 697 at r3](https://reviewable.io/reviews/saltastroops/salt-api/334#-OCEBPr_8qbG2FIBdFlO:-OCcJ-6QBQEFFfKeANq8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/03ad9c7028cef9d199fb02392aa4938b2405312d/saltapi/web/api/proposals.py#L697)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm still not convinced about the `download_`.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/334)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
