### PR TITLE
Updating proposal status

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/161)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/161)* status: all files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1266 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfc2tX1A3h9Dv-hqOX:-NNfc2tX1A3h9Dv-hqOY:b-h2un4o) ([raw file](https://github.com/saltastroops/salt-api/blob/34c981aa729be583ae2626f26b6133c504823b99/saltapi/repository/proposal_repository.py#L1266)):*
> ```Python
>             raise NotFoundError()
> 
>     def _proposal_inactive_reason_id(self, inactive_reason: str) -> int:
> ```

Should not be removed; see comment below.
___
*[`saltapi/repository/proposal_repository.py` line 1284 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfbQss3OI_qab5VbBn:-NNfbQss3OI_qab5VbBo:bep57k0) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/repository/proposal_repository.py#L1284)):*
> ```Python
> SET 
>     PGI.ProposalStatus_Id = :status_id,
>     PGI.ProposalInactiveReason_Id = (
> ```

I would advocate against this change. If you pass a non-existing reason, you will not get a meaningful error. Chances are it would be a Not Found error which would be confusing, So, ax in the case von the proposal status you should get the id separately and raise an error if the reason is incorrect.
___
*[`saltapi/service/permission_service.py` line 190 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfci-B1HX5rYeLXV-W:-NNfci-B1HX5rYeLXV-X:b-fvfljh) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/service/permission_service.py#L190)):*
> ```Python
>             user: User,
>             proposal_code: str,
>             is_self_activatable: bool,
> ```

I don't think you should pass is_self_activatable. The method should figure this out itself (see the check_permission_to_activate_proposal method).

Which, by the way, might have to be removed, as well as the check_permission_to_deactivate method?
___
*[`saltapi/service/permission_service.py` line 199 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfdTu9-x45dfKz9swo:-NNfdTu9-x45dfKz9swp:b-q1oy0q) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/service/permission_service.py#L199)):*
> ```Python
> 
>         * a SALT Astronomer
>         * an administrator
> ```

The comment does not cover all cases. You might add:

* a Principal Investigator or Principal Contact (if the proposal is deactivated or if it is activated self-activation is allowed)
___
*[`saltapi/web/api/proposals.py` line 345 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfegxm5h4buiP-BCzg:-NNfegxm5h4buiP-BCzh:beh6oe5) ([raw file](https://github.com/saltastroops/salt-api/blob/34c981aa729be583ae2626f26b6133c504823b99/saltapi/web/api/proposals.py#L345)):*
> ```Python
>     ),
>     proposal_status: ProposalStatusValue = Body(
>         ..., alias="status", title="Proposal status", description="New proposal status."
> ```

Proposal status and (optional) status reason

New proposal status and (optional) status reason
___
*[`saltapi/web/api/proposals.py` line 359 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfjZlw1J3pmNoLXay_:-NNfjZlw1J3pmNoLXaya:bpmqk4t) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/web/api/proposals.py#L359)):*
> ```Python
>         )
> 
>         proposal_service.update_proposal_status(proposal_code, proposal_status.status.value, proposal_status.status.reason)
> ```

I think there is one level too many here. `proposal_status.status.value` should rather be `proposal_status.value`, for example. So the schema types should be updated; ProposalStatusContent seems unnecessary.
___
*[`saltapi/web/api/proposals.py` line 362 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfnHlM7xGHhaMZnI58:-NNfnHlM7xGHhaMZnI59:b-2afomk) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/web/api/proposals.py#L362)):*
> ```Python
> 
>         unit_of_work.connection.commit()
>         return proposal_status
> ```

I'd suggest *not* to return the user input. Yes it saes a database query, but it comes at the cost of returning a value which may or may not reflect what is actually in the database now.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 99 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfpC1z2O1bSO8Y5Q5e:-NNfpC1z2O1bSO8Y5Q5f:b-bz1el6) ([raw file](https://github.com/saltastroops/salt-api/blob/34c981aa729be583ae2626f26b6133c504823b99/tests/integration/proposals/test_update_proposal_status.py#L99)):*
> ```Python
> 
> 
> def test_proposal_status_update(
> ```

It might perhaps be worth testing that SALT Astronomers and administrator may make any change? So maybe test for a few status values with admin and SA?
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 107 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfnsu48Vp2euk2yBkw:-NNfnsu48Vp2euk2yBkx:b-ksrx5h) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/tests/integration/proposals/test_update_proposal_status.py#L107)):*
> ```Python
>     ],
> )
> def test_pi_and_pc_can_not_set_proposal_status_to_active(
> ```

They cannot set it to other status values either (apart from Inactive); so you might want to test this as well.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 129 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfoSlH2PU1VYhkoDaT:-NNfoSlH2PU1VYhkoDaU:b2c8gc3) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/tests/integration/proposals/test_update_proposal_status.py#L129)):*
> ```Python
>     ],
> )
> def test_pi_and_pc_can_set_proposal_status_to_active_is_self_activatable(
> ```

Maybe better: test_pi_and_pc_can_activate_self_activatable_proposal

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/161)* status: all files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1266 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfc2tX1A3h9Dv-hqOX:-NO8n2sg6AzZSOrhtkpP:b-tu5avz) ([raw file](https://github.com/saltastroops/salt-api/blob/34c981aa729be583ae2626f26b6133c504823b99/saltapi/repository/proposal_repository.py#L1266)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should not be removed; see comment below.
</blockquote></details>

returened



_Code quote:_
```Python
    def _proposal_inactive_reason_id(self, inactive_reason: str) -> int:
        stmt = text(
            """
SELECT PIR.ProposalInactiveReason_Id AS id
FROM ProposalInactiveReason PIR
WHERE PIR.InactiveReason = :inactive_reason
        """
        )
        result = self.connection.execute(stmt, {"inactive_reason": inactive_reason})
        return cast(int, result.scalar_one())
```
___
*[`saltapi/repository/proposal_repository.py` line 1284 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfbQss3OI_qab5VbBn:-NO8nf3c6rsJIc_0YH0X:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/repository/proposal_repository.py#L1284)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would advocate against this change. If you pass a non-existing reason, you will not get a meaningful error. Chances are it would be a Not Found error which would be confusing, So, ax in the case von the proposal status you should get the id separately and raise an error if the reason is incorrect.
</blockquote></details>

Done.



_Code quote:_
```Python
            proposal_inactive_reason_id = (
                self._proposal_inactive_reason_id(reason) if reason else None
            )
```
___
*[`saltapi/service/permission_service.py` line 190 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfci-B1HX5rYeLXV-W:-NO8oLawC9haRE5dppc2:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/service/permission_service.py#L190)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you should pass is_self_activatable. The method should figure this out itself (see the check_permission_to_activate_proposal method).

Which, by the way, might have to be removed, as well as the check_permission_to_deactivate method?
</blockquote></details>

removed
___
*[`saltapi/service/permission_service.py` line 199 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfdTu9-x45dfKz9swo:-NO8oiL81VarsgU9Wnv-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/service/permission_service.py#L199)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The comment does not cover all cases. You might add:

* a Principal Investigator or Principal Contact (if the proposal is deactivated or if it is activated self-activation is allowed)
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 345 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfegxm5h4buiP-BCzg:-NO8pNHKE7H7o8mNLDid:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/34c981aa729be583ae2626f26b6133c504823b99/saltapi/web/api/proposals.py#L345)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Proposal status and (optional) status reason

New proposal status and (optional) status reason
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 359 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfjZlw1J3pmNoLXay_:-NO8q-5gCxoKJ4GdGHnc:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/web/api/proposals.py#L359)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think there is one level too many here. `proposal_status.status.value` should rather be `proposal_status.value`, for example. So the schema types should be updated; ProposalStatusContent seems unnecessary.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 362 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfnHlM7xGHhaMZnI58:-NO8qo40DlRVmVd6kArE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/web/api/proposals.py#L362)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest *not* to return the user input. Yes it saes a database query, but it comes at the cost of returning a value which may or may not reflect what is actually in the database now.
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 99 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfpC1z2O1bSO8Y5Q5e:-NO8wNV9C1qdFnNuNtoH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/34c981aa729be583ae2626f26b6133c504823b99/tests/integration/proposals/test_update_proposal_status.py#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might perhaps be worth testing that SALT Astronomers and administrator may make any change? So maybe test for a few status values with admin and SA?
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 107 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfnsu48Vp2euk2yBkw:-NO8sSbd41y1lUA8SHZU:bv9w2cz) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/tests/integration/proposals/test_update_proposal_status.py#L107)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

They cannot set it to other status values either (apart from Inactive); so you might want to test this as well.
</blockquote></details>

tested above
___
*[`tests/integration/proposals/test_update_proposal_status.py` line 129 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfoSlH2PU1VYhkoDaT:-NO8sbFOA0h-wCJBTdPa:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/tests/integration/proposals/test_update_proposal_status.py#L129)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: test_pi_and_pc_can_activate_self_activatable_proposal
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/161)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1282 at r3](https://reviewable.io/reviews/saltastroops/salt-api/161#-NO94lTg4zX6IOg8_uss:-NO94lTg4zX6IOg8_ust:bhv1kbx) ([raw file](https://github.com/saltastroops/salt-api/blob/9bf89c2226c9ab7fa20e3796ca63101ed681967c/saltapi/repository/proposal_repository.py#L1282)):*
> ```Python
>         """
> 
>         # We could query for the status id within the UPDATE query, but then it would
> ```

status id  > status and reason ids
___
*[`saltapi/repository/proposal_repository.py` line 1284 at r3](https://reviewable.io/reviews/saltastroops/salt-api/161#-NO94u-X4JF-06ED6vW4:-NO94u-X4JF-06ED6vW5:bl0zd7i) ([raw file](https://github.com/saltastroops/salt-api/blob/9bf89c2226c9ab7fa20e3796ca63101ed681967c/saltapi/repository/proposal_repository.py#L1284)):*
> ```Python
>         # We could query for the status id within the UPDATE query, but then it would
>         # not be clear whether a failing query is due to a wrong proposal code or a
>         # wrong status value.
> ```

status > status or reason
___
*[`saltapi/service/permission_service.py` line 190 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfci-B1HX5rYeLXV-W:-NO96mKlDeYHZjUsx9im:b-tqvxex) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/service/permission_service.py#L190)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

removed
</blockquote></details>

What about the part of removing the `check_permission_to_activate_proposal` and `check_permission_to_deactivate` methods?
___
*[`saltapi/web/api/proposals.py` line 346 at r3](https://reviewable.io/reviews/saltastroops/salt-api/161#-NO95ic17vWZFEIG-gvp:-NO95ic17vWZFEIG-gvq:bpagvjp) ([raw file](https://github.com/saltastroops/salt-api/blob/9bf89c2226c9ab7fa20e3796ca63101ed681967c/saltapi/web/api/proposals.py#L346)):*
> ```Python
>         alias="status",
>         title="Proposal status and (optional) status reason",
>         description="Nwe proposal status and (optional) status reason."
> ```

Nwe > New

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/161)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1282 at r3](https://reviewable.io/reviews/saltastroops/salt-api/161#-NO94lTg4zX6IOg8_uss:-NOBBRYc9pWf1tZEhw9P:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/9bf89c2226c9ab7fa20e3796ca63101ed681967c/saltapi/repository/proposal_repository.py#L1282)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

status id  > status and reason ids
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1284 at r3](https://reviewable.io/reviews/saltastroops/salt-api/161#-NO94u-X4JF-06ED6vW4:-NOBBUN27iX__8T7Ak2p:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/9bf89c2226c9ab7fa20e3796ca63101ed681967c/saltapi/repository/proposal_repository.py#L1284)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

status > status or reason
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 190 at r2](https://reviewable.io/reviews/saltastroops/salt-api/161#-NNfci-B1HX5rYeLXV-W:-NODvwdiAv3VDv7w9mnn:bkpe8h9) ([raw file](https://github.com/saltastroops/salt-api/blob/b584a8a4fb3a2844ccf595112f856aa8ba97cede/saltapi/service/permission_service.py#L190)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about the part of removing the `check_permission_to_activate_proposal` and `check_permission_to_deactivate` methods?
</blockquote></details>

I had to sleep to understand this comment...
removed
___
*[`saltapi/web/api/proposals.py` line 346 at r3](https://reviewable.io/reviews/saltastroops/salt-api/161#-NO95ic17vWZFEIG-gvp:-NOBBe_f3E1NZzGei6AI:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/9bf89c2226c9ab7fa20e3796ca63101ed681967c/saltapi/web/api/proposals.py#L346)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nwe > New
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/161)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
