### PR TITLE
block-visits-updates

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Patch block visit updates

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/172)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/172)* status: all files reviewed, 7 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/block_service.py` line 57 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOJKnKx8bOYsrF1Cr9w:-NOJKnKyDrpJ64e4Lhqj:bdjzde1) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/saltapi/service/block_service.py#L57)):*
> ```Python
>         """
>         if status == "Rejected" and reason is None:
>             raise AuthorizationError()
> ```

I don't think this is the right error, as this isn't an authorisation issue. It might make more sense to raise a `saltapi.exceptions.ValidationError` (not a Pydantic ValidationError).

Also, you should rule out the case that the status is not Rejected and there is nonetheless a reason.
___
*[`saltapi/web/api/block_visits.py` line 43 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKEHvw3dsXplPYuorH:-NOKEHvw3dsXplPYuorI:b-ww5fi2) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/saltapi/web/api/block_visits.py#L43)):*
> ```Python
> 
> 
> @router.patch("/{block_visit_id}/status", summary="Update the status of a block visit")
> ```

Hmmm.... Given that this endpoint is specifically for updating the status (rather than the whole block visit) and that the status is fully defined by the status value and reason, shouldn't this endpoint use PUT rather than PATCH?
___
*[`saltapi/web/api/proposals.py` line 365 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKDhAi56wCtv-JXQZ4:-NOKDhAi56wCtv-JXQZ5:b-iri7mv) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/saltapi/web/api/proposals.py#L365)):*
> ```Python
>         )
> 
>         unit_of_work.connection.commit()
> ```

The `.connection` should be unnecessary?
___
*[`tests/integration/block_visits/test_patch_block_visit_status.py` line 113 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKF8Hk82WhtHXHjZQS:-NOKF8Hk82WhtHXHjZQT:b-cpj3b8) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/tests/integration/block_visits/test_patch_block_visit_status.py#L113)):*
> ```Python
> 
> 
> def test_patch_block_visit_status(
> ```

You haven't tested that a status value other than Rejected need not and even must not have a rejection reason, have you?
___
*[`tests/integration/block_visits/test_patch_block_visit_status.py` line 122 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKFUYV0bPtQqssh_HW:-NOKFUYV0bPtQqssh_HX:bswpeu0) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/tests/integration/block_visits/test_patch_block_visit_status.py#L122)):*
> ```Python
> 
>     block_visit_status = "Rejected"
>     rejection_rejection = "Observing conditions not met"
> ```

I guess you meant `rejection_reason`? :-)
___
*[`tests/service/test_block_service.py` line 68 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKGACG-GAOURtF_bPF:-NOKGACG-GAOURtF_bPG:b3utpaq) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/tests/service/test_block_service.py#L68)):*
> ```Python
>             ]:
>                 raise NotFoundError(f"Unknown block visit status: {status}")
>             if status == "Rejected" and rejection_reason is None:
> ```

I don't think this is the right error, as this isn't an authorisation issue. It might make more sense to raise a `saltapi.exceptions.ValidationError` (not a Pydantic ValidationError).

Also, you should also rule out the case that there is a rejection reason although the block is not rejected.

And I wonder whether there isn't too much logic in this fake block repository now... As a point in case 
___
*[`tests/service/test_block_service.py` line 203 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKIodU5takMY7eqGXs:-NOKIodV9ALhlWOvabzz:bfxfs0h) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/tests/service/test_block_service.py#L203)):*
> ```Python
>     block_service = create_block_service()
>     status = "Wrong status"
>     with pytest.raises(NotFoundError):
> ```

A not found error would IMHO suggest that the block visit could not be found. So this rather looks like validation error to me.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/172)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/block_service.py` line 57 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOJKnKx8bOYsrF1Cr9w:-NOKbnLlB-InORnj-nUo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/saltapi/service/block_service.py#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this is the right error, as this isn't an authorisation issue. It might make more sense to raise a `saltapi.exceptions.ValidationError` (not a Pydantic ValidationError).

Also, you should rule out the case that the status is not Rejected and there is nonetheless a reason.
</blockquote></details>

Done.
___
*[`saltapi/web/api/block_visits.py` line 43 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKEHvw3dsXplPYuorH:-NOKbpnnBtIB7g6MSGkV:b-yfc4eg) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/saltapi/web/api/block_visits.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Hmmm.... Given that this endpoint is specifically for updating the status (rather than the whole block visit) and that the status is fully defined by the status value and reason, shouldn't this endpoint use PUT rather than PATCH?
</blockquote></details>

Yes, that makes sense. I will take care of this on my next commit on this PR.
___
*[`saltapi/web/api/proposals.py` line 365 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKDhAi56wCtv-JXQZ4:-NOKX3R68P2mthH5slp8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/saltapi/web/api/proposals.py#L365)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The `.connection` should be unnecessary?
</blockquote></details>

Done.
___
*[`tests/integration/block_visits/test_patch_block_visit_status.py` line 113 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKF8Hk82WhtHXHjZQS:-NOKauP3CbeueoY_JhmV:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/tests/integration/block_visits/test_patch_block_visit_status.py#L113)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You haven't tested that a status value other than Rejected need not and even must not have a rejection reason, have you?
</blockquote></details>

Done.
___
*[`tests/integration/block_visits/test_patch_block_visit_status.py` line 122 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKFUYV0bPtQqssh_HW:-NOKXPtM-buqmOunXqO1:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/tests/integration/block_visits/test_patch_block_visit_status.py#L122)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess you meant `rejection_reason`? :-)
</blockquote></details>

Done.
___
*[`tests/service/test_block_service.py` line 68 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKGACG-GAOURtF_bPF:-NOKavig8oJBMHmxew1I:b-8b9l76) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/tests/service/test_block_service.py#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this is the right error, as this isn't an authorisation issue. It might make more sense to raise a `saltapi.exceptions.ValidationError` (not a Pydantic ValidationError).

Also, you should also rule out the case that there is a rejection reason although the block is not rejected.

And I wonder whether there isn't too much logic in this fake block repository now... As a point in case 
</blockquote></details>

I have ruled out the case that there is a rejection reason although the block is not rejected.

And I agree with you, the logic in this repository is too much now. Maybe should be removed since most of these test cases are also covered in the integrations test?
___
*[`tests/service/test_block_service.py` line 203 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKIodU5takMY7eqGXs:-NOKSrfZ0tURqvvJqLlZ:b-jiskf8) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/tests/service/test_block_service.py#L203)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A not found error would IMHO suggest that the block visit could not be found. So this rather looks like validation error to me.
</blockquote></details>

Agreed, it is a validation error.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/172)* status: all files reviewed, 6 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/block_service.py` line 59 at r4](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOLTK5K6yYkiFCCFXOo:-NOLTK5L4mCgaTK-YZgF:b-q86mjd) ([raw file](https://github.com/saltastroops/salt-api/blob/3560bf02c20a741fdc6261efa756760259aec81f/saltapi/service/block_service.py#L59)):*
> ```Python
>             status != "Rejected" and reason is not None
>         ):
>             raise ValidationError()
> ```

You should pass a meaningful error message to the `ValidationError`.
___
*[`saltapi/web/api/block_visits.py` line 94 at r4](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOLTcev8_3sXGqyoe-c:-NOLTcev8_3sXGqyoe-d:b-9ct17p) ([raw file](https://github.com/saltastroops/salt-api/blob/3560bf02c20a741fdc6261efa756760259aec81f/saltapi/web/api/block_visits.py#L94)):*
> ```Python
>             unit_of_work.commit()
>         except ValidationError:
>             raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST)
> ```

This is not necessary. The ValidationError is handled by an exception handler in `exceptions_handling.py`. (And if it isn't, it should.)
___
*[`tests/integration/block_visits/test_patch_block_visit_status.py` line 87 at r4](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOLU7drBABywvSMGIub:-NOLU7dsDy6vuTlF6JyJ:b-niodz6) ([raw file](https://github.com/saltastroops/salt-api/blob/3560bf02c20a741fdc6261efa756760259aec81f/tests/integration/block_visits/test_patch_block_visit_status.py#L87)):*
> ```Python
> 
> 
> def test_patch_block_visit_status_requires_no_rejection_reason_for_block_visit_status_not_rejected(
> ```

Nit-picking, but: "must_have" might be more precise than "requires".
___
*[`tests/service/test_block_service.py` line 68 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKGACG-GAOURtF_bPF:-NOLUcHSAt-qJmkV8Wyr:b-97hr5d) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/tests/service/test_block_service.py#L68)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have ruled out the case that there is a rejection reason although the block is not rejected.

And I agree with you, the logic in this repository is too much now. Maybe should be removed since most of these test cases are also covered in the integrations test?
</blockquote></details>

Yes, I agree.
___
*[`tests/service/test_block_service.py` line 72 at r4](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOLUe164yQxKPlTJ3yB:-NOLUe164yQxKPlTJ3yC:b-u79sze) ([raw file](https://github.com/saltastroops/salt-api/blob/3560bf02c20a741fdc6261efa756760259aec81f/tests/service/test_block_service.py#L72)):*
> ```Python
>             ]:
>                 raise ValidationError(f"Unknown block visit status: {status}")
>             if (status == "Rejected" and rejection_reason is None) and (
> ```

One of the "and" probably should be an "or".

But hey, you suggested to remove all this anyway... ;-)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/172)* status: all files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/block_service.py` line 59 at r4](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOLTK5K6yYkiFCCFXOo:-NONmLvb9hTZ3ZrCNLgD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3560bf02c20a741fdc6261efa756760259aec81f/saltapi/service/block_service.py#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should pass a meaningful error message to the `ValidationError`.
</blockquote></details>

Done.
___
*[`saltapi/web/api/block_visits.py` line 94 at r4](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOLTcev8_3sXGqyoe-c:-NONj-Z-3hDAlIxiNgnv:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3560bf02c20a741fdc6261efa756760259aec81f/saltapi/web/api/block_visits.py#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is not necessary. The ValidationError is handled by an exception handler in `exceptions_handling.py`. (And if it isn't, it should.)
</blockquote></details>

Done.
___
*[`tests/service/test_block_service.py` line 68 at r2](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOKGACG-GAOURtF_bPF:-NONik8T80_hi8ev9_q8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/da5c31604f6416b5a928e80a9a55cb9ad76d94c4/tests/service/test_block_service.py#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes, I agree.
</blockquote></details>

Done.
___
*[`tests/service/test_block_service.py` line 72 at r4](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOLUe164yQxKPlTJ3yB:-NONiliV1Oe7eqj6HPQ6:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3560bf02c20a741fdc6261efa756760259aec81f/tests/service/test_block_service.py#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

One of the "and" probably should be an "or".

But hey, you suggested to remove all this anyway... ;-)
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/172)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/block_service.py` line 60 at r5](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOO4d7574o_9dyzsMzz:-NOO4d7574o_9dyzsN--:b-nzj7ct) ([raw file](https://github.com/saltastroops/salt-api/blob/711161486599ca409c123035ed75443ea4ba8d60/saltapi/service/block_service.py#L60)):*
> ```Python
>         ):
>             raise ValidationError(
>                 "Incorrect block visit status and/or block rejection reason"
> ```

My suggestion would be something like:

```
if status == "Rejected" and reason is None:
    raise ValidationError("A reason is required for the block status value`"Rejected\".")
if status != "Rejected" and reason is not None:
    raise ValidationError("No reason must be given for a block status other than \"Rejected\
".")
```

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/172)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/block_service.py` line 60 at r5](https://reviewable.io/reviews/saltastroops/salt-api/172#-NOO4d7574o_9dyzsMzz:-NOOAnKuDZUfXadNBTu_:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/711161486599ca409c123035ed75443ea4ba8d60/saltapi/service/block_service.py#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

My suggestion would be something like:

```
if status == "Rejected" and reason is None:
    raise ValidationError("A reason is required for the block status value`"Rejected\".")
if status != "Rejected" and reason is not None:
    raise ValidationError("No reason must be given for a block status other than \"Rejected\
".")
```
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
