### PR TITLE
Dependency check

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/122)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/122)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`pyproject.toml` line 53 at r2](https://reviewable.io/reviews/saltastroops/salt-api/122#-NGwyxp99fqLMjC7RJx_:-NGwyxpA7YZ3-mVvPJEM:b-8q586k) ([raw file](https://github.com/saltastroops/salt-api/blob/374f0bde05f903f792acdde187ecae2b7bd5e137/pyproject.toml#L53)):*
> ```TOML
> httpx = "^0.23.0"
> 
> [tool.poetry.group.dev.dependencies]
> ```

What is the difference between `tool.poetry.group.dev.dependencies` and `tool.poetry.dev.dependencies`?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/122)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`pyproject.toml` line 53 at r2](https://reviewable.io/reviews/saltastroops/salt-api/122#-NGwyxp99fqLMjC7RJx_:-NGykTal3Cj67TDnLQN3:bbkx6eg) ([raw file](https://github.com/saltastroops/salt-api/blob/374f0bde05f903f792acdde187ecae2b7bd5e137/pyproject.toml#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What is the difference between `tool.poetry.group.dev.dependencies` and `tool.poetry.dev.dependencies`?
</blockquote></details>

Poetry was raising a warning that the `dev` flag would be replaced with the `group` flag

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/122)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`pyproject.toml` line 53 at r2](https://reviewable.io/reviews/saltastroops/salt-api/122#-NGwyxp99fqLMjC7RJx_:-NGzm0c06A2FyKZVh9G0:b-qb9ri1) ([raw file](https://github.com/saltastroops/salt-api/blob/374f0bde05f903f792acdde187ecae2b7bd5e137/pyproject.toml#L53)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Poetry was raising a warning that the `dev` flag would be replaced with the `group` flag
</blockquote></details>

Noted. But then you should move all the other dev dependencies to that section as well...

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/122)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`pyproject.toml` line 53 at r2](https://reviewable.io/reviews/saltastroops/salt-api/122#-NGwyxp99fqLMjC7RJx_:-NGzpWHD93OJI7CSYa0d:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/374f0bde05f903f792acdde187ecae2b7bd5e137/pyproject.toml#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Noted. But then you should move all the other dev dependencies to that section as well...
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
