### PR TITLE
Hendling SSDA Errors

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/305)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/305)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/exceptions_handling.py` line 141 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5PRMLB2-XlJbWB8zZ:-O-5PRMLB2-XlJbWB8z_:b-1f6u1x) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/exceptions_handling.py#L141)):*
> ```Python
> 
>     @app.exception_handler(SSDAError)
>     async def authentication_error_handler(
> ```

Wrong function name
___
*[`saltapi/exceptions_handling.py` line 147 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5PlIu6gjDcI69An75:-O-5PlIu6gjDcI69An76:b-gdeyio) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/exceptions_handling.py#L147)):*
> ```Python
>         log_message(request.method, request.url, exc)
>         return JSONResponse(
>             status_code=status.HTTP_207_MULTI_STATUS, content={
> ```

Wrong HTTP code. (Why don't you use the status code 500?) 
___
*[`saltapi/service/proposal_service.py` line 387 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5S3czDdcOtZzaYFU6:-O-5S3czDdcOtZzaYFU7:b-up79nc) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/service/proposal_service.py#L387)):*
> ```Python
>             if ssda_response['errors']:
>                 raise SSDAError()
>         except:
> ```

You are catching an SSDA only to throw another one... How about something like the following?

```python
try:
    ssda_response = requests.post(get_settings().ssda_api_url, json=body).json()
except:
    raise SSDAError()
if "errors" in ssda_response:
    raise SSDAError()
```
___
*[`saltapi/service/proposal_service.py` line 388 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5SgiM67-9Fd-x39zh:-O-5RpZ97MMjFisBDRxK:b3t38uu) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/service/proposal_service.py#L388)):*
> ```Python
>                 raise SSDAError()
>         except:
>             raise SSDAError()
> ```

Shouldn't you log the error message? (I know you log in the error handler, but by then you've lost the original error message.) So maybe include the error message in the SSDAError constructor, but don;'t include it in the error handler response?
___
*[`saltapi/web/api/proposals.py` line 342 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5TIpADb-bfNsyvYcI:-O-5TIpADb-bfNsyvYcJ:b3itkpt) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/web/api/proposals.py#L342)):*
> ```Python
>                 )
>             except SSDAError:
>                 status_code = status.HTTP_207_MULTI_STATUS
> ```

You should undo the (non-SSDA) proprietary period update when the SSDA request fails. So it would make more sense to execute `unit_of_work.commit()` only if the SSDA request was successful.
___
*[`saltapi/web/api/proposals.py` line 342 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5Tmsy7oYPoLl7CKnj:-O-5Tmsy7oYPoLl7CKnk:bepacsz) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/web/api/proposals.py#L342)):*
> ```Python
>                 )
>             except SSDAError:
>                 status_code = status.HTTP_207_MULTI_STATUS
> ```

Wrong HTTP status code.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/305)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/exceptions_handling.py` line 141 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5PRMLB2-XlJbWB8zZ:-O-BfEdB2u2GO_QnFH1a:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/exceptions_handling.py#L141)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wrong function name
</blockquote></details>

Done.
___
*[`saltapi/exceptions_handling.py` line 147 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5PlIu6gjDcI69An75:-O-BfEwb60W73aHXnq41:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/exceptions_handling.py#L147)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wrong HTTP code. (Why don't you use the status code 500?)
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 387 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5S3czDdcOtZzaYFU6:-O-B_qUUDGbCvz9uQAhZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/service/proposal_service.py#L387)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are catching an SSDA only to throw another one... How about something like the following?

```python
try:
    ssda_response = requests.post(get_settings().ssda_api_url, json=body).json()
except:
    raise SSDAError()
if "errors" in ssda_response:
    raise SSDAError()
```
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 388 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5SgiM67-9Fd-x39zh:-O-BfCXgCuu6pKr0y75V:bw9d9f2) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/service/proposal_service.py#L388)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't you log the error message? (I know you log in the error handler, but by then you've lost the original error message.) So maybe include the error message in the SSDAError constructor, but don;'t include it in the error handler response?
</blockquote></details>

I receive a list of errors and I will log them here.
___
*[`saltapi/web/api/proposals.py` line 342 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5TIpADb-bfNsyvYcI:-O-Bf90PEaIA7sc2O0tY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/web/api/proposals.py#L342)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should undo the (non-SSDA) proprietary period update when the SSDA request fails. So it would make more sense to execute `unit_of_work.commit()` only if the SSDA request was successful.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 342 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5Tmsy7oYPoLl7CKnj:-O-BfBDc1yQJNKTxzx8W:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/web/api/proposals.py#L342)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wrong HTTP status code.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/305)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/service/proposal_service.py` line 387 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5S3czDdcOtZzaYFU6:-O-MA_lR02B2N-f3XwrD:b-igd5xx) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/service/proposal_service.py#L387)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You might consider logging the exception you catch before raising the SSDAError.
___
*[`saltapi/service/proposal_service.py` line 393 at r2](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-MCCpW5Yqj55HgPGZh:-O-MCCpW5Yqj55HgPGZi:b-8080a5) ([raw file](https://github.com/saltastroops/salt-api/blob/c9de6769bc06e4cb9640e2b43d855ccafa210227/saltapi/service/proposal_service.py#L393)):*
> ```Python
>                 error_message = f'SSDA Error start\n{err["message"]}\n{err["path"]}\nSSDA error end'
>                 logging.error(error_message)
>             raise SSDAError()
> ```

You might consider including a `from` statement when raising the SSDA exception, so that you don't lose the exception causing the error (see https://realpython.com/python-raise-exception/#reraising-a-previous-exception).

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/305)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/proposal_service.py` line 387 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5S3czDdcOtZzaYFU6:-O-e7BFrBQvZmCO2HY1V:bkw7e9f) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/service/proposal_service.py#L387)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might consider logging the exception you catch before raising the SSDAError.
</blockquote></details>

this is done already
___
*[`saltapi/service/proposal_service.py` line 393 at r2](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-MCCpW5Yqj55HgPGZh:-O-e7PtOE_zS6ClImwjM:b-ku5kp0) ([raw file](https://github.com/saltastroops/salt-api/blob/c9de6769bc06e4cb9640e2b43d855ccafa210227/saltapi/service/proposal_service.py#L393)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might consider including a `from` statement when raising the SSDA exception, so that you don't lose the exception causing the error (see https://realpython.com/python-raise-exception/#reraising-a-previous-exception).
</blockquote></details>

Done.

There is no error raised here but the message that I am logging in the for loop
I want to raise a new error if ever SSDA contains errors

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/305)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/service/proposal_service.py` line 387 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5S3czDdcOtZzaYFU6:-O-eo0RUAqmHi2M2z11g:b6x8v8b) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/service/proposal_service.py#L387)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this is done already
</blockquote></details>

I don't see where this would be logged?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/305)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/service/proposal_service.py` line 387 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5S3czDdcOtZzaYFU6:-O-p78c9B2c-aLGHykS5:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/service/proposal_service.py#L387)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see where this would be logged?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/305)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/service/proposal_service.py` line 387 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5S3czDdcOtZzaYFU6:-O-pz36b7l9jwLznNJtE:b-3prxx2) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/service/proposal_service.py#L387)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do you need the exc_info (in particular in this case)?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/305)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/service/proposal_service.py` line 387 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5S3czDdcOtZzaYFU6:-O0O2SfCDKsPVXwcxG6U:b-kv75hk) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/service/proposal_service.py#L387)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you need the exc_info (in particular in this case)?
</blockquote></details>

I think so to get all the stack trace logged

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/305)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/service/proposal_service.py` line 387 at r1](https://reviewable.io/reviews/saltastroops/salt-api/305#-O-5S3czDdcOtZzaYFU6:-O0QM5yr7CSrmSujDiOC:b3j1k10) ([raw file](https://github.com/saltastroops/salt-api/blob/a3d970a6de0c93d6fa19fe970df4b61240c18b28/saltapi/service/proposal_service.py#L387)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I think so to get all the stack trace logged
</blockquote></details>

But I'd argue that should you should rather log the stack trace in the exception handler.

Thinking about this, the exception handler should do all the logging. So I guess it would make sense to pass the error message to the `SSDAException` and not worry about logging anywhere in this file.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/305)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
