### PR TITLE
nir-instrument-setups

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
NIR instrument setups

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/94)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/94)* status: all files reviewed, 8 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`saltapi/repository/nir_repository.py` line 56 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDgizdZ9INdr6wbLmOE:-NDgizdZ9INdr6wbLmOF:b-f9bbv9) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/repository/nir_repository.py#L56)):*
> ```Python
>             "id": row.nir_id,
>             "configuration": self._configuration(row),
>             "detector": self._detector(row),
> ```

The detector is part ofd a pattern step -- and the pattern is missing.
___
*[`saltapi/repository/nir_repository.py` line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDgezYw-WYZUoEqHB3_:-NDgezYw-WYZUoEqHB3a:b-c432nd) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/repository/nir_repository.py#L78)):*
> ```Python
> 
>         config = {
>             "mode": row.detector_sampling_mode,
> ```

The mode is covered by the detector already and thus should not be included here, I'd think.
___
*[`saltapi/repository/nir_repository.py` line 79 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDgdhbgB3wikeGA3f8E:-NDgdhbgB3wikeGA3f8F:b-voz8sz) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/repository/nir_repository.py#L79)):*
> ```Python
>         config = {
>             "mode": row.detector_sampling_mode,
>             "spectroscopy": self._spectroscopy(row),
> ```

Given that (contrary to RSS) NIR only does spectroscopy, I don't think there is a need for having an additional "spectroscopy" level; I'd suggest to include the relevant fields directly as fields of `config`:

```
config = {
    "grating": ...,
    "grating_angle": ...,
   ...
}
```
___
*[`saltapi/repository/nir_repository.py` line 91 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDghCDIDSOeEuhfw_Bg:-NDghCDIDSOeEuhfw_Bh:b6jo8s5) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/repository/nir_repository.py#L91)):*
> ```Python
>             "resets": row.resets,
>             "ramps": row.ramps,
>             "urg_groups": row.urg_groups,
> ```

It may be a pain, but "up_the_ramp_groups" might be clearer than "urg_groups:".
___
*[`saltapi/web/schema/nir.py` line 12 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDhBw1m1RWFG9yBDsx-:-NDhBw1m1RWFG9yBDsx0:b-kin310) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/web/schema/nir.py#L12)):*
> ```Python
> 
> 
> class NirSpectroscopy(BaseModel):
> ```

As mentioned elsewhere already, I don't think "spectroscopy" should be mentioned explicitly, and the properties of this class should rather be included directly as properties of `NirConfiguration`.
___
*[`saltapi/web/schema/nir.py` line 26 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDhCk_hBVy133Nt2Aqm:-NDhCk_hBVy133Nt2Aqn:bqdtgut) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/web/schema/nir.py#L26)):*
> ```Python
> 
> class NirConfiguration(BaseModel):
>     mode: str = Field(..., title="Instrument mode", description="Instrument mode")
> ```

There is no instrument mode, and hence there is no need for a `mode` property.
___
*[`saltapi/web/schema/nir.py` line 63 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDhEE9iCaLb2DrjkElf:-NDhEE9iCaLb2DrjkElg:bp3vwko) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/web/schema/nir.py#L63)):*
> ```Python
> 
> 
> class NirProcedure(BaseModel):
> ```

The dither pattern is missing.
___
*[`saltapi/web/schema/nir.py` line 81 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDhEPa96Lp-r58wX5ZT:-NDhEPa96Lp-r58wX5ZU:b-3yisxd) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/web/schema/nir.py#L81)):*
> ```Python
>         ..., title="Instrument configuration", description="Instrument configuration"
>     )
>     detector: NirDetector = Field(
> ```

The detector information is part of a dither pattern step.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/94)* status: 16 of 18 files reviewed, 8 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/repository/nir_repository.py` line 56 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDgizdZ9INdr6wbLmOE:-NDmLbifEBrFxy3nVWkB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/repository/nir_repository.py#L56)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The detector is part ofd a pattern step -- and the pattern is missing.
</blockquote></details>

Done.
___
*[`saltapi/repository/nir_repository.py` line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDgezYw-WYZUoEqHB3_:-NDmLcU05o-xGAdYAZjB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/repository/nir_repository.py#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The mode is covered by the detector already and thus should not be included here, I'd think.
</blockquote></details>

Done.
___
*[`saltapi/repository/nir_repository.py` line 79 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDgdhbgB3wikeGA3f8E:-NDmLd-61_ulXmJ3GGJK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/repository/nir_repository.py#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that (contrary to RSS) NIR only does spectroscopy, I don't think there is a need for having an additional "spectroscopy" level; I'd suggest to include the relevant fields directly as fields of `config`:

```
config = {
    "grating": ...,
    "grating_angle": ...,
   ...
}
```
</blockquote></details>

Done.
___
*[`saltapi/repository/nir_repository.py` line 91 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDghCDIDSOeEuhfw_Bg:-NDmLfIY-PBOZKGUEOG3:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/repository/nir_repository.py#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It may be a pain, but "up_the_ramp_groups" might be clearer than "urg_groups:".
</blockquote></details>

Done.
___
*[`saltapi/web/schema/nir.py` line 12 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDhBw1m1RWFG9yBDsx-:-NDmLgRFCJlEXo4MAdkX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/web/schema/nir.py#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As mentioned elsewhere already, I don't think "spectroscopy" should be mentioned explicitly, and the properties of this class should rather be included directly as properties of `NirConfiguration`.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/nir.py` line 26 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDhCk_hBVy133Nt2Aqm:-NDmLi2E2dFMTpMKtZxF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/web/schema/nir.py#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is no instrument mode, and hence there is no need for a `mode` property.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/nir.py` line 63 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDhEE9iCaLb2DrjkElf:-NDmLoh248cBDFGDVv0Z:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/web/schema/nir.py#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The dither pattern is missing.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/nir.py` line 81 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDhEPa96Lp-r58wX5ZT:-NDmLpbHDXa42vZr088o:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/web/schema/nir.py#L81)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The detector information is part of a dither pattern step.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/94)* status: all files reviewed, 18 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`saltapi/repository/nir_repository.py` line 91 at r1](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDghCDIDSOeEuhfw_Bg:-NDmXp7CCSwIYLFAI73d:b5r2jx7) ([raw file](https://github.com/saltastroops/salt-api/blob/cf8ff576b2a03ddc68afae309a06e913e2171af5/saltapi/repository/nir_repository.py#L91)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I guess we might revisit the naming when going through the API... :-/
___
*[`saltapi/repository/nir_repository.py` line 57 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmXU7m03-Oby4-BUl3:-NDmXU7m03-Oby4-BUl4:b-gtvanv) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/repository/nir_repository.py#L57)):*
> ```Python
>             "id": row.nir_id,
>             "configuration": self._configuration(row),
>             "calibration": self._calibration(row),
> ```

No need for a calibration field, I think.
___
*[`saltapi/repository/nir_repository.py` line 65 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmXb2oBbvg8vEJknEQ:-NDmXb2oBbvg8vEJknER:bsdsvx6) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/repository/nir_repository.py#L65)):*
> ```Python
>         return nir
> 
>     def _calibration(self, row: Any) -> List[Dict[str, Any]]:
> ```

No need for this function, I think.
___
*[`saltapi/repository/nir_repository.py` line 127 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmYCeb5OPhPQ2hjlSx:-NDmYCeb5OPhPQ2hjlSy:b-lbhsa) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/repository/nir_repository.py#L127)):*
> ```Python
>         return detector
> 
>     def _dither_step(self, row: Any) -> List[Dict[str, Any]]:
> ```

_dither_step > _dither_steps
___
*[`saltapi/repository/nir_repository.py` line 127 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmYFzTD4NsFtQntPah:-NDmYFzTD4NsFtQntPai:b3207c9) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/repository/nir_repository.py#L127)):*
> ```Python
>         return detector
> 
>     def _dither_step(self, row: Any) -> List[Dict[str, Any]]:
> ```

Given that the only item you need from the row is the id, maybe the id could be used as the function parameter instead?
___
*[`saltapi/repository/nir_repository.py` line 128 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmY85r7PP6GwzPKpBy:-NDmY85r7PP6GwzPKpBz:b-i9ldhl) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/repository/nir_repository.py#L128)):*
> ```Python
> 
>     def _dither_step(self, row: Any) -> List[Dict[str, Any]]:
>         """Return an NIR dither pattern step."""
> ```

Return the dither pattern steps.
___
*[`saltapi/repository/nir_repository.py` line 151 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmYZy9EobrS3D8DZuj:-NDmYZy9EobrS3D8DZuk:b-sdhrio) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/repository/nir_repository.py#L151)):*
> ```Python
>         )
> 
>         dither_step = [
> ```

dither_step > dither_steps
___
*[`saltapi/repository/nir_repository.py` line 163 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmYd3l33jkZfXemnpO:-NDmYd3l33jkZfXemnpP:brfsou8) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/repository/nir_repository.py#L163)):*
> ```Python
>         return dither_step
> 
>     def _dither_pattern(self, row: Any) -> Dict[str, Any]:
> ```

I fob;t think this method is necessary.
___
*[`saltapi/repository/nir_repository.py` line 184 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmYhA838svq0ZmjNnT:-NDmYhA838svq0ZmjNnU:b2nhsg) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/repository/nir_repository.py#L184)):*
> ```Python
>             "procedure_type": row.procedure_type,
>             "cycles": row.cycles,
>             "dither_pattern": self._dither_pattern(row),
> ```

```
"dither_pattern": self._dither_steps(...)
```
___
*[`saltapi/web/schema/nir.py` line 51 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmV3KaC64k0G453HQp:-NDmV3KaC64k0G453HQq:barxzlm) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/web/schema/nir.py#L51)):*
> ```Python
> 
> class NirDetector(BaseModel):
>     """NIR detector."""
> ```

detector > detector setup
___
*[`saltapi/web/schema/nir.py` line 56 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmV0jY1FZDOuF8Vel3:-NDmV0jY1FZDOuF8Vel4:b8fdpdo) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/web/schema/nir.py#L56)):*
> ```Python
>     groups: int = Field(
>         ...,
>         title="Up-the-ramp group",
> ```

group > groups
___
*[`saltapi/web/schema/nir.py` line 57 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmUvPm9hdfiUr4TKXD:-NDmUvPm9hdfiUr4TKXE:b-oif1w3) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/web/schema/nir.py#L57)):*
> ```Python
>         ...,
>         title="Up-the-ramp group",
>         description="Number of samples up the ramp for Up-the-ramp Group",
> ```

The number of samples up the ramp for the Up-the-Ramp Group mode.
___
*[`saltapi/web/schema/nir.py` line 101 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmXCxH-fKQc2Y3ROYq:-NDmXCxH-fKQc2Y3ROYr:bhkh5nd) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/web/schema/nir.py#L101)):*
> ```Python
>         ...,
>         title="Horizontal offset",
>         description="Horizontal offset (in image coordination), in milliarcseconds",
> ```

coordination > coordinates
___
*[`saltapi/web/schema/nir.py` line 106 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmXHgE-ouEcxnbkitA:-NDmXHgE-ouEcxnbkitB:bhkh5nd) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/web/schema/nir.py#L106)):*
> ```Python
>         ...,
>         title="Vertical offset",
>         description="Vertical offset (in image coordination), in milliarcseconds",
> ```

coordination > coordinates
___
*[`saltapi/web/schema/nir.py` line 125 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmWexz9d-GfaamQkFd:-NDmWexz9d-GfaamQkFe:b-7zqa7j) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/web/schema/nir.py#L125)):*
> ```Python
> 
> 
> class NirDitherPattern(BaseModel):
> ```

I think this type is unnecessary?
___
*[`saltapi/web/schema/nir.py` line 144 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmWuZCAY3w0OMikD0h:-NDmWuZCAY3w0OMikD0i:b-g6b7e4) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/web/schema/nir.py#L144)):*
> ```Python
>         ..., title="Procedure type", description="Procedure type"
>     )
>     dither_pattern: NirDitherPattern = Field(
> ```

The type should be `List[NirDitherStep]`, I think.
___
*[`saltapi/web/schema/nir.py` line 149 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmS2Sh9xlj9JlqUBB5:-NDmS2Sh9xlj9JlqUBB6:b-qkycb4) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/web/schema/nir.py#L149)):*
> ```Python
> 
> 
> class NirCalibration(BaseModel):
> ```

I don't think there should be a calibration type (yet).
___
*[`saltapi/web/schema/nir.py` line 173 at r2](https://reviewable.io/reviews/saltastroops/salt-api/94#-NDmRXpwBWwvtaF71eq2:-NDmRXpx0ToWmSq6FEns:b-2irrf) ([raw file](https://github.com/saltastroops/salt-api/blob/520938e36e697f872c6b90705a4a6161c5c1dec6/saltapi/web/schema/nir.py#L173)):*
> ```Python
>         ..., title="Instrument configuration", description="Instrument configuration"
>     )
>     calibration: List[NirCalibration] = Field(
> ```

No calibration information should be included in the NIR setup. (And the NirCalibration table isn't really corresponding to the calibration details in the XML, I think...)

**Review by hettlage — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/94)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @mofokeng-chaka)

**Pull request merged**
