### PR TITLE
exceptions-handling

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Exceptions handling

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/128)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/128)* status: all files reviewed, 10 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/exceptions_handling.py` line 16 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMV9-D71wpnu7rH4rC5:-NMV9-D88x8eAd6HCvgZ:bf9d9eq) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L16)):*
> ```Python
> 
> def log_message(method: str, url: Union[str, URL], message: Any) -> None:
>     """log message when catch exception"""
> ```

"Log a message together with the HTTP method and URL as an error."
___
*[`saltapi/exceptions_handling.py` line 18 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMV9pK42nljjsMAI4ci:-NMV9pK42nljjsMAI4cj:bmvvrut) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L18)):*
> ```Python
>     """log message when catch exception"""
> 
>     logger.error("start error, this is".center(60, "*"))
> ```

I'd omit the ", this is"
___
*[`saltapi/exceptions_handling.py` line 18 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVA0HS8DaKi2ErzrSE:-NMVA0HS8DaKi2ErzrSF:b-4m4rae) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L18)):*
> ```Python
>     """log message when catch exception"""
> 
>     logger.error("start error, this is".center(60, "*"))
> ```

I see a subtle problem: The log message should contain a datetime (added by the logger). But this time might be different for the different `error` calls in this function. So maybe there should only be a single error call?
___
*[`saltapi/exceptions_handling.py` line 27 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVAl2bA-F9GZI_SqP8:-NMVAl2bA-F9GZI_SqP9:bf2f1aw) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L27)):*
> ```Python
>     @app.exception_handler(HTTPException)
>     async def http_exception_handler(request: Request, exc: HTTPException) -> Response:
>         """catch FastAPI HTTPException"""
> ```

"""Catch a FastAPI HTTPException."""
___
*[`saltapi/exceptions_handling.py` line 40 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVBVHgCnZ3YzrGqvOY:-NMVBVHgCnZ3YzrGqvOZ:bjmy9rr) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L40)):*
> ```Python
>         request: Request, exc: RequestValidationError
>     ) -> Response:
>         """catch FastAPI RequestValidationError"""
> ```

"""Catch a FastAPI RequestValidationError."""
___
*[`saltapi/exceptions_handling.py` line 51 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVCmr3--9DIyy-2CHQ:-NMVCmr3--9DIyy-2CHR:b-jxd3qm) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L51)):*
> ```Python
>     @app.exception_handler(Exception)
>     async def exception_handle(request: Request, exc: Exception) -> Response:
>         """catch other exception"""
> ```

"""Catch an Exception."""
___
*[`saltapi/exceptions_handling.py` line 60 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVCyrxB1h9DipMAi17:-NMVCyrxB1h9DipMAi18:bgql4wc) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L60)):*
> ```Python
> 
>     @app.exception_handler(NotFoundError)
>     async def not_found_error_handler(request: Request, exc: NotFoundError) -> Response:
> ```

"""Catch a NotFoundError."""
___
*[`saltapi/exceptions_handling.py` line 67 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVD2WZ9H1AR_8jSMt9:-NMVD2WZ9H1AR_8jSMtA:b-6mpx8e) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L67)):*
> ```Python
> 
>     @app.exception_handler(ValidationError)
>     async def validation_error_handler(
> ```

"""Catch a ValidationError."""
___
*[`saltapi/exceptions_handling.py` line 72 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVD8zP1LMtUL6ZrALG:-NMVD8zP1LMtUL6ZrALH:b-hx5465) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L72)):*
> ```Python
>         log_message(request.method, request.url, exc)
>         return JSONResponse(
>             status_code=status.HTTP_404_NOT_FOUND, content={"message": str(exc)}
> ```

The status code should be 400.
___
*[`saltapi/exceptions_handling.py` line 77 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVDS7h7ZdJ_QAItYle:-NMVDS7h7ZdJ_QAItYlf:bhdctp0) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L77)):*
> ```Python
>     @app.exception_handler(AuthorizationError)
>     async def authorization_error_handler(
>         request: Request, exc: AuthorizationError
> ```

"""Catch an AuthorizationError."""

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/128)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/exceptions_handling.py` line 16 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMV9-D71wpnu7rH4rC5:-NMXfGuz4lj75rFhCplE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Log a message together with the HTTP method and URL as an error."
</blockquote></details>

Done.
___
*[`saltapi/exceptions_handling.py` line 18 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMV9pK42nljjsMAI4ci:-NMXfKDT0WVKJ5WJqyeb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd omit the ", this is"
</blockquote></details>

Done.
___
*[`saltapi/exceptions_handling.py` line 18 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVA0HS8DaKi2ErzrSE:-NMXfdfS0J-3vz2zVHL9:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I see a subtle problem: The log message should contain a datetime (added by the logger). But this time might be different for the different `error` calls in this function. So maybe there should only be a single error call?
</blockquote></details>

Done.
___
*[`saltapi/exceptions_handling.py` line 27 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVAl2bA-F9GZI_SqP8:-NMXfhPeD8aw1Wre8FxD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"""Catch a FastAPI HTTPException."""
</blockquote></details>

Done.
___
*[`saltapi/exceptions_handling.py` line 40 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVBVHgCnZ3YzrGqvOY:-NMXfnzvCT0QopwZdfPd:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"""Catch a FastAPI RequestValidationError."""
</blockquote></details>

Done.
___
*[`saltapi/exceptions_handling.py` line 51 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVCmr3--9DIyy-2CHQ:-NMXfng9DxKmnPwYx4M4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"""Catch an Exception."""
</blockquote></details>

Done.
___
*[`saltapi/exceptions_handling.py` line 60 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVCyrxB1h9DipMAi17:-NMXfqHP5CihgnwNz6qr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"""Catch a NotFoundError."""
</blockquote></details>

Done.
___
*[`saltapi/exceptions_handling.py` line 67 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVD2WZ9H1AR_8jSMt9:-NMXfy9P7SLUw84DEabx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"""Catch a ValidationError."""
</blockquote></details>

Done.
___
*[`saltapi/exceptions_handling.py` line 72 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVD8zP1LMtUL6ZrALG:-NMXgFNgCpsX5o4ejcLo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The status code should be 400.
</blockquote></details>

Done.
___
*[`saltapi/exceptions_handling.py` line 77 at r1](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMVDS7h7ZdJ_QAItYle:-NMXgFos8hE4cxEFXdqF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/00345f4d43e6b965faf205964e5c5afb9b1d4287/saltapi/exceptions_handling.py#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"""Catch an AuthorizationError."""
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/128)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/exceptions_handling.py` line 19 at r2](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMbsGLE-1C952S4eECA:-NMbsGLE-1C952S4eECB:b-ng2qmy) ([raw file](https://github.com/saltastroops/salt-api/blob/7cef24a600b1b510ff725cc93cc96173f9200da3/saltapi/exceptions_handling.py#L19)):*
> ```Python
> 
>     logger.error(
>         f"start error \n{method} {url} \n{message} \nend error".center(60, "*")
> ```

Centering and surrounding the whole string with '*'s is probably not what you want...

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/128)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/exceptions_handling.py` line 19 at r2](https://reviewable.io/reviews/saltastroops/salt-api/128#-NMbsGLE-1C952S4eECA:-NMnAk9ZCcbMHboUWXsY:b-eauqtt) ([raw file](https://github.com/saltastroops/salt-api/blob/7cef24a600b1b510ff725cc93cc96173f9200da3/saltapi/exceptions_handling.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Centering and surrounding the whole string with '*'s is probably not what you want...
</blockquote></details>

I have updated this.

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
