### PR TITLE
actions-versions-updates

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
GitHub actions version updates

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`.github/workflows/test.yml` line 22 at r2](https://reviewable.io/reviews/saltastroops/salt-api/100#-NECglUF1oUfW0Uu-Tji:-NECglUF1oUfW0Uu-Tjj:bxg1kgn) ([raw file](https://github.com/saltastroops/salt-api/blob/132762236b93049f6456800c346f282d2ccc9340/.github/workflows/test.yml#L22)):*
> ```YAML
>         with:
>           python-version: 3.9
>       - name: Set up output environment
> ```

output > Python ?
___
*[`.github/workflows/test.yml` line 24 at r2](https://reviewable.io/reviews/saltastroops/salt-api/100#-NECh7ZfDaItJXFppRn5:-NECh7ZfDaItJXFppRn6:b36rt9l) ([raw file](https://github.com/saltastroops/salt-api/blob/132762236b93049f6456800c346f282d2ccc9340/.github/workflows/test.yml#L24)):*
> ```YAML
>       - name: Set up output environment
>         id: setup-python
>         run: echo "python-version=3.9" >> $GITHUB_OUTPUT
> ```

Why is the `>> $GITHUB_OUTPUT` needed?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`.github/workflows/test.yml` line 22 at r2](https://reviewable.io/reviews/saltastroops/salt-api/100#-NECglUF1oUfW0Uu-Tji:-NEFCd9J5Z0ob_DcCsVr:b-ir6q2h) ([raw file](https://github.com/saltastroops/salt-api/blob/132762236b93049f6456800c346f282d2ccc9340/.github/workflows/test.yml#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

output > Python ?
</blockquote></details>

I agree with you, it makes sense.
___
*[`.github/workflows/test.yml` line 24 at r2](https://reviewable.io/reviews/saltastroops/salt-api/100#-NECh7ZfDaItJXFppRn5:-NEFGnI5Em4m1xddmFAv:bye14uw) ([raw file](https://github.com/saltastroops/salt-api/blob/132762236b93049f6456800c346f282d2ccc9340/.github/workflows/test.yml#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why is the `>> $GITHUB_OUTPUT` needed?
</blockquote></details>

The `$GITHUB_OUTPUT` environment file is used instead of the `set-output` in the latest version of actions.

Otherwise, a warning is shown at the end of the workflow stating that the `set-output` and `set-state` commands are deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`.github/workflows/test.yml` line 22 at r2](https://reviewable.io/reviews/saltastroops/salt-api/100#-NECglUF1oUfW0Uu-Tji:-NEFwrz3CfvussX-s6il:bg7pkoy) ([raw file](https://github.com/saltastroops/salt-api/blob/132762236b93049f6456800c346f282d2ccc9340/.github/workflows/test.yml#L22)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I agree with you, it makes sense.
</blockquote></details>

Now that I understand what the GITHUB_OUTPUT is for, I see an issue: You've hardcoded the Python version 3.9 twice in the file, and chances are you forget to update both instances when you have to update it in future. So it might be better to define the version as a secret und use that secret rather than hardcoding?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`.github/workflows/test.yml` line 22 at r2](https://reviewable.io/reviews/saltastroops/salt-api/100#-NECglUF1oUfW0Uu-Tji:-NEG6ryE1_do8bWWT0dS:babhglt) ([raw file](https://github.com/saltastroops/salt-api/blob/132762236b93049f6456800c346f282d2ccc9340/.github/workflows/test.yml#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Now that I understand what the GITHUB_OUTPUT is for, I see an issue: You've hardcoded the Python version 3.9 twice in the file, and chances are you forget to update both instances when you have to update it in future. So it might be better to define the version as a secret und use that secret rather than hardcoding?
</blockquote></details>

I agree with you. However, I have instead used the env variable.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`.github/workflows/test.yml` line 27 at r4](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEG7lD4CYaXNVTijRLH:-NEG7lD4CYaXNVTijRLI:b-41k2x7) ([raw file](https://github.com/saltastroops/salt-api/blob/f6c834e7a0a6a7becb1dcc4efe67e9c410204edd/.github/workflows/test.yml#L27)):*
> ```YAML
>       - name: Set up Python environment
>         id: setup-python
>         run: echo "python-version=${{ env.PYTHON_VERSION }}" >> $GITHUB_OUTPUT
> ```

I don't think you need this step any longer. Can't you just use `env.PYTHON_VERSION` instead of `steps.setup-python.outputs.python-version` in

```key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}```

below?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`.github/workflows/test.yml` line 27 at r4](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEG7lD4CYaXNVTijRLH:-NEG8q9uEgj7WJwQm96N:bl5cj31) ([raw file](https://github.com/saltastroops/salt-api/blob/f6c834e7a0a6a7becb1dcc4efe67e9c410204edd/.github/workflows/test.yml#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need this step any longer. Can't you just use `env.PYTHON_VERSION` instead of `steps.setup-python.outputs.python-version` in

```key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}```

below?
</blockquote></details>

You're right. I have removed this step now.

**Review by mofokeng-chaka — COMMENTED** [review]
I have updated the workflow to use tox instead of running dependencies individually.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100#-:-NEfFcMb37NoIci8o1Gq:bdkpmml)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @hettlage)

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: all files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`tox.ini` line 7 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfYGJz5SteeLrK1Ybg:-NEfYGJz5SteeLrK1Ybh:bpm21ue) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/tox.ini#L7)):*
> ```INI
> [testenv]
> passenv = *
> whitelist_externals = poetry
> ```

`whitelist_externals` is deprecated; `allowlist_externals` should be used instead.
___
*[`tox.ini` line 9 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfUVRqB5YeAjo2feKM:-NEfUVRqB5YeAjo2feKN:bkj4mlz) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/tox.ini#L9)):*
> ```INI
> whitelist_externals = poetry
> commands =
>     poetry run pytest --mock-db-data --db-data-dir tests/salt-testdata/salt-api/ \
> ```

I would expect you need the `poetry install`?
___
*[`tox.ini` line 28 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfWF8_CeWaJoWg9uwg:-NEfWF8_CeWaJoWg9uwh:b-u014m4) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/tox.ini#L28)):*
> ```INI
>     saltapi/web/schema/*.py:E501
>     tests/conftest.py:E402
>     tests/*.py:S105,S106
> ```

Indent think you should need all these exceptions?
___
*[`saltapi/service/block_service.py` line 70 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfZ6rvDBkDcjI-4xm0:-NEfZ6rvDBkDcjI-4xm1:bv3pzrv) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/saltapi/service/block_service.py#L70)):*
> ```Python
>         """
>         file = requests.get(get_settings().tcs_icd_url)
>         xml_file = minidom.parse(file.text)
> ```

Shouldn't this be `parseString`?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`tox.ini` line 7 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfYGJz5SteeLrK1Ybg:-NEgACBX7hKiRbRzbdHE:b-31cujb) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/tox.ini#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`whitelist_externals` is deprecated; `allowlist_externals` should be used instead.
</blockquote></details>

Thanks for pointing this out. It is now updated.
___
*[`tox.ini` line 9 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfUVRqB5YeAjo2feKM:-NEg5jQ27e3atLJhyYcH:b-6hdpfd) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/tox.ini#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would expect you need the `poetry install`?
</blockquote></details>

Probably true. However, it appears unnecessary because dependencies have already been installed on the two previous steps. Since the `poetry run` command executes the given command inside the project’s virtualenv, in that sense, a virtualenv is activated and deactivated before and after executing the given command.
___
*[`tox.ini` line 28 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfWF8_CeWaJoWg9uwg:-NEg7j0r2O-2rQLuGFjk:b-av9na6) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/tox.ini#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Indent think you should need all these exceptions?
</blockquote></details>

I do. The latest flake8 package has a flake8-bandit dependency.
___
*[`saltapi/service/block_service.py` line 70 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfZ6rvDBkDcjI-4xm0:-NEg8eFY-ms88Cor1LhM:bnewa3f) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/saltapi/service/block_service.py#L70)):*
Not anymore, I am now using the `defusedxml` package instead of the `xml` package, as per `bandit`s suggestion because of possible vulnerabilities. And so `defusedxml.minidom` uses `parse` not `parseString`. 

Here's the error and the suggestion from bandit:

>> Issue: [B318:blacklist] Using xml.dom.minidom.parseString to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.dom.minidom.parseString with its defusedxml equivalent function or make sure defusedxml.defuse_stdlib() is called
   Severity: Medium   
   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   Location: saltapi/service/block_service.py:70:19
   More Info: https://bandit.readthedocs.io/en/1.7.4/blacklists/blacklist_calls.html#b313-b320-xml-bad-minidom
69              file = requests.get(get_settings().tcs_icd_url)
70              xml_file = minidom.parseString(file.text)
71              elements = xml_file.getElementsByTagName("String")

**Review by mofokeng-chaka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100#-:-NEkL4EeAqFixG5FBBY3:bnfp4nl)* status: 11 of 27 files reviewed, 4 unresolved discussions (waiting on @hettlage)

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r6, 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`tox.ini` line 28 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfWF8_CeWaJoWg9uwg:-NEk2Nw00sDjS7gw7CHq:b8uigc9) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/tox.ini#L28)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I do. The latest flake8 package has a flake8-bandit dependency.
</blockquote></details>

I've significantly reduced the number of exceptions...
___
*[`saltapi/service/block_service.py` line 70 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfZ6rvDBkDcjI-4xm0:-NEkS0RG-N30cjHooIux:b-9erf0c) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/saltapi/service/block_service.py#L70)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Not anymore, I am now using the `defusedxml` package instead of the `xml` package, as per `bandit`s suggestion because of possible vulnerabilities. And so `defusedxml.minidom` uses `parse` not `parseString`. 

Here's the error and the suggestion from bandit:

>> Issue: [B318:blacklist] Using xml.dom.minidom.parseString to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.dom.minidom.parseString with its defusedxml equivalent function or make sure defusedxml.defuse_stdlib() is called
   Severity: Medium   
   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   Location: saltapi/service/block_service.py:70:19
   More Info: https://bandit.readthedocs.io/en/1.7.4/blacklists/blacklist_calls.html#b313-b320-xml-bad-minidom
69              file = requests.get(get_settings().tcs_icd_url)
70              xml_file = minidom.parseString(file.text)
71              elements = xml_file.getElementsByTagName("String")

</blockquote></details>

I have my doubts. defusedxml.minidom has both a `parse` and  `parseString` function (see https://pypi.org/project/defusedxml/#defusedxml-minidom), and given that it is supposed to provide the same functionalitt as minimum, `parseString` should be the function to use if you have the XML as a string.

**Review by hettlage — COMMENTED** [review]
> Reviewed 13 of 13 files at r8.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: 26 of 27 files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: 22 of 27 files reviewed, all discussions resolved (waiting on @hettlage)

___
*[`tox.ini` line 28 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfWF8_CeWaJoWg9uwg:-NEkU_eaEpwsVHAwmKfy:b-ucfknh) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/tox.ini#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I've significantly reduced the number of exceptions...
</blockquote></details>

Thanks!
___
*[`saltapi/service/block_service.py` line 70 at r5](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEfZ6rvDBkDcjI-4xm0:-NEkUlLKCBXF2uFD6tN8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4e37d5ed8430bffbe9206b1c54feaec4612c598a/saltapi/service/block_service.py#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I have my doubts. defusedxml.minidom has both a `parse` and  `parseString` function (see https://pypi.org/project/defusedxml/#defusedxml-minidom), and given that it is supposed to provide the same functionalitt as minimum, `parseString` should be the function to use if you have the XML as a string.
</blockquote></details>

Done.

**Comment by hettlage** [comment]
I think this PR should not be merged -- I'm worried it might cause unwanted changes in files which have nothing to with the GitHub Action.

I'd therefore propose to close this PR and open a new one, moving the GitHub Action stuff to the new PR.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/100)* status: 19 of 29 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`tox.ini` line 24 at r11](https://reviewable.io/reviews/saltastroops/salt-api/100#-NEm4EpH-5ZgeZ4pxvCl:-NEm4EpH-5ZgeZ4pxvCm:b-gzvyto) ([raw file](https://github.com/saltastroops/salt-api/blob/74050f7b8497abefcccd81fbcc4c4cb3d3c6fc5a/tox.ini#L24)):*
> ```INI
> per-file-ignores =
>     saltapi/repository/block_repository.py:E501
>     saltapi/service/create_proposal_progress_html.py:E501
> ```

I don't think these files should be excluded.

**Pull request closed without merging**
