### PR TITLE
Give dither offsets in arcseconds

### PR DESCRIPTION
**Pull request by hettlage**
Has failing tests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/97)

### CODE REVIEW

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/97)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/97)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/97)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`saltapi/service/proposal_service.py` line 19 at r6](https://reviewable.io/reviews/saltastroops/salt-api/97#-NECfjX99PcVWNcOQwRF:-NECfjX99PcVWNcOQwRG:b-fay7wb) ([raw file](https://github.com/saltastroops/salt-api/blob/accd6be7953b0759450701c91b4652f834880038/saltapi/service/proposal_service.py#L19)):*
> ```Python
> 
>     url = "{}://{}:{}{}".format(
>         request.url.scheme, request.client.host, request.client.port, router_path
> ```

`request.client` seems incorrect; this returns the details of the *connecting* computer.

**Review by mofokeng-chaka — COMMENTED** [review]
Tests are now passing: DB_DATA_DIR argument was missing in the workflow when running tests.

> Reviewed 1 of 1 files at r4, 3 of 6 files at r5, 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/97#-:-NEA7HFRBF9nkla4so5B:b-g97jn7)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/service/proposal_service.py` line 19 at r6](https://reviewable.io/reviews/saltastroops/salt-api/97#-NECfjX99PcVWNcOQwRF:-NEF7yNaAsa1HBu_uRFV:bpg0d5k) ([raw file](https://github.com/saltastroops/salt-api/blob/accd6be7953b0759450701c91b4652f834880038/saltapi/service/proposal_service.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`request.client` seems incorrect; this returns the details of the *connecting* computer.
</blockquote></details>

That's true, and it is now fixed.

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 1 of 3 files at r6, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/97)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
