### PR TITLE
Signed cookie

### LINKED ISSUE #111: Secondary auth token cookie should be signed
If the cookie is unsigned, it does not add any additional security.

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/319)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/319)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/authentication_service.py` line 119 at r1](https://reviewable.io/reviews/saltastroops/salt-api/319#-O2Uqop0CJmo-fqy1iaS:-O2Uqop0CJmo-fqy1iaT:b6lxvdl) ([raw file](https://github.com/saltastroops/salt-api/blob/dc5be4a28a76836a0f1e40ae62487e35d35eefc7/saltapi/service/authentication_service.py#L119)):*
> ```Python
>     user_id = request.session.get(USER_ID_KEY)
> 
>     def get_decoded_token(token_key, source):
> ```

I don't think you gain anything from signing the secondary auth token.
___
*[`saltapi/web/api/authentication.py` line 77 at r1](https://reviewable.io/reviews/saltastroops/salt-api/319#-O2Urnwk4q8vZALQlhva:-O2Urnwk4q8vZALQlhvb:bqgu6ti) ([raw file](https://github.com/saltastroops/salt-api/blob/dc5be4a28a76836a0f1e40ae62487e35d35eefc7/saltapi/web/api/authentication.py#L77)):*
> ```Python
>     secondary_auth_token = str(uuid.uuid4())
>     cookie_data = {"secondary_auth_token": secondary_auth_token}
>     signed_cookie = AuthenticationService.jwt_token(cookie_data)
> ```

I don't think you gain anything from signing the secondary auth cookie.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/319)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/web/api/authentication.py` line 77 at r1](https://reviewable.io/reviews/saltastroops/salt-api/319#-O2Urnwk4q8vZALQlhva:-O2_CMQFCPYLuXB5R8K8:bt4u7ty) ([raw file](https://github.com/saltastroops/salt-api/blob/dc5be4a28a76836a0f1e40ae62487e35d35eefc7/saltapi/web/api/authentication.py#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you gain anything from signing the secondary auth cookie.
</blockquote></details>

Looking at this again, I think this needs another discussion.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/319)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/authentication_service.py` line 119 at r1](https://reviewable.io/reviews/saltastroops/salt-api/319#-O2Uqop0CJmo-fqy1iaS:-O2czzrN-GJVejPSaM4j:b-41ljpw) ([raw file](https://github.com/saltastroops/salt-api/blob/dc5be4a28a76836a0f1e40ae62487e35d35eefc7/saltapi/service/authentication_service.py#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you gain anything from signing the secondary auth token.
</blockquote></details>

As per our discussion, I will close this PR and the issue.
___
*[`saltapi/web/api/authentication.py` line 77 at r1](https://reviewable.io/reviews/saltastroops/salt-api/319#-O2Urnwk4q8vZALQlhva:-O2czr5T5bB6bs0hDDaA:b-41ljpw) ([raw file](https://github.com/saltastroops/salt-api/blob/dc5be4a28a76836a0f1e40ae62487e35d35eefc7/saltapi/web/api/authentication.py#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Looking at this again, I think this needs another discussion.
</blockquote></details>

As per our discussion, I will close this PR and the issue.

**Comment by mofokeng-chaka** [comment]
Signing the cookie is not really beneficial in this case.

**Pull request closed without merging**
