### PR TITLE
Add a new contact.

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/325)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/325)* status: all files reviewed, 14 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/user_repository.py` line 1221 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IFkg2DMqZBOGwJafu:-O5IFkg2DMqZBOGwJafv:b-wirt13) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1221)):*
> ```Python
>             self._delete_right(user_id, right_setting)
> 
>     def _update_user_investigator(self, user_id, investigator_id):
> ```

Maybe `_set_preferred_contact` might make the intention of this method a bit clearer.
___
*[`saltapi/repository/user_repository.py` line 1231 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IHPHh0frWacgs2DKB:-O5IHPHh0frWacgs2DKC:bx18107) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1231)):*
> ```Python
>         self.connection.execute(stmt, {"user_id": user_id, "investigator_id": investigator_id})
> 
>     def _add_investigator_contact(self, user_id: int, new_user_contact: Dict[str, Any]) -> int:
> ```

Maybe rather `add_contact_details`?
___
*[`saltapi/repository/user_repository.py` line 1233 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IHkt-1X5GnVF8GczT:-O5IHkt05mC_ss_L183K:b-byf64z) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1233)):*
> ```Python
>     def _add_investigator_contact(self, user_id: int, new_user_contact: Dict[str, Any]) -> int:
>         """
>         Add investigator contact.
> ```

Maybe better:

Add contact details to a user.

The primary key of the new Investigator entry is returned.
___
*[`saltapi/repository/user_repository.py` line 1256 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5II87Z0IQRpO6bCZ0W:-O5II87Z0IQRpO6bCZ0X:bjtxf1x) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1256)):*
> ```Python
>             )
>         except IntegrityError as e:
>             raise ValueError(f"Email address: {new_user_contact['email']} already exist.")
> ```

Maybe better: The email address {new_user_contact['email']} already exists.
___
*[`saltapi/repository/user_repository.py` line 1261 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IIUMI2Uue7nRLaZXv:-O5IIUMI2Uue7nRLaZXw:b-yl4chl) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1261)):*
> ```Python
> 
> 
>     def add_contact(self, user_id: int,  contact:Dict[str, str]) -> Optional[User]:
> ```

I think this method can be removed, and its functionality can be covered on the service level. It is fundamentally doing two different things, name creating a contact and setting the preferred contact.

Also
___
*[`saltapi/repository/user_repository.py` line 1263 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IJWQ962e-OTGmQdJp:-O5IJWQ962e-OTGmQdJq:bx2rjcs) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1263)):*
> ```Python
>     def add_contact(self, user_id: int,  contact:Dict[str, str]) -> Optional[User]:
>         user = self.get(user_id)
>         if user:
> ```

The if condition should be unnecessary.
___
*[`saltapi/service/permission_service.py` line 544 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IJllJ2o56v2fRm_JL:-O5IJllK4c5cBQUMStFd:b-1kakra) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/service/permission_service.py#L544)):*
> ```Python
>             return
> 
>         raise ValidationError("You are not allowed to add this contact.")
> ```

Maybe better: You are not allowed to add a contact to the [or this] user.
___
*[`saltapi/web/api/users.py` line 396 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IK8I7AEW10KgDdo2p:-O5IK8I7AEW10KgDdo2q:b7m3qbh) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L396)):*
> ```Python
> 
> @router.post(
>     "/{user_id}/add-contact", summary="Add user's contact", response_model=User
> ```

"Add contact details to the user"
___
*[`saltapi/web/api/users.py` line 404 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IKIIU5MuyW2abIhNT:-O5IKIIU5MuyW2abIhNU:bdpmv8w) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L404)):*
> ```Python
>         user: _User = Depends(get_current_user),
>         contact: UserContact = Body(
>             ..., title="User Contact", description="User contact to add."
> ```

User contact > contact details
___
*[`saltapi/web/api/users.py` line 408 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IKmYj8duTrUkPqxjR:-O5IKmYj8duTrUkPqxjS:b-hu40bz) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L408)):*
> ```Python
> ) -> User:
>     """
>     Add user contact.
> ```

Add contact details to the user.
___
*[`saltapi/web/api/users.py` line 415 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IMMIEBMpkPqIJ9xnL:-O5IMMIEBMpkPqIJ9xnM:bdf7swl) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L415)):*
> ```Python
> 
>         user_service = services.user_service(unit_of_work.connection)
>         user = user_service.add_contact(user_id, vars(contact))
> ```

`contact` should have a `dict` method, and using that would be better than using `vars`.
___
*[`saltapi/web/api/users.py` line 416 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IL7A64L9dwSvj5Kjs:-O5IL7A64L9dwSvj5Kjt:b-3f1dfc) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L416)):*
> ```Python
>         user_service = services.user_service(unit_of_work.connection)
>         user = user_service.add_contact(user_id, vars(contact))
>         if not user:
> ```

This should never happen.
___
*[`saltapi/web/api/users.py` line 419 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IL-23AuDfxJI0BnOk:-O5IL-23AuDfxJI0BnOl:b-e84ywb) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L419)):*
> ```Python
>             raise NotFoundError("Unknown user.")
>         unit_of_work.commit()
>         return user
> ```

Newline missing at file end.
___
*[`saltapi/web/schema/user.py` line 202 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IMz738CbwUS2s6VmU:-O5IMz738CbwUS2s6VmV:b-bs128r) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/schema/user.py#L202)):*
> ```Python
>     given_name: str = Field(..., title="Given name", description="Given name.")
>     family_name: str = Field(..., title="Family name", description="Family name.")
>     email: str = Field(..., title="Email", description="Email.")
> ```

Email > Email address

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/325)* status: all files reviewed, 14 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/user_repository.py` line 1221 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IFkg2DMqZBOGwJafu:-O5OO4Ey3N_eccLobXBO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1221)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe `_set_preferred_contact` might make the intention of this method a bit clearer.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1231 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IHPHh0frWacgs2DKB:-O5OOMIYBEfzKytNwWNY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1231)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe rather `add_contact_details`?
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1233 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IHkt-1X5GnVF8GczT:-O5OOzoW7hPV3mTseCP7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1233)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better:

Add contact details to a user.

The primary key of the new Investigator entry is returned.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1256 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5II87Z0IQRpO6bCZ0W:-O5OOzUg317Ga06-SkiE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1256)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: The email address {new_user_contact['email']} already exists.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1261 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IIUMI2Uue7nRLaZXv:-O5OZQcM76K1iH8wDMtR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1261)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this method can be removed, and its functionality can be covered on the service level. It is fundamentally doing two different things, name creating a contact and setting the preferred contact.

Also
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1263 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IJWQ962e-OTGmQdJp:-O5OZPCs5RXmuQ_bI8Wc:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/repository/user_repository.py#L1263)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The if condition should be unnecessary.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 544 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IJllJ2o56v2fRm_JL:-O5ORKJHDLIgEHR7NIMO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/service/permission_service.py#L544)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: You are not allowed to add a contact to the [or this] user.
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 396 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IK8I7AEW10KgDdo2p:-O5ORZYc5PsXKA3--_uJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L396)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Add contact details to the user"
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 404 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IKIIU5MuyW2abIhNT:-O5ORfsV-Rpixj_2vbjx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L404)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

User contact > contact details
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 408 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IKmYj8duTrUkPqxjR:-O5ORn-C3sl5-GM4CNuB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L408)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Add contact details to the user.
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 415 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IMMIEBMpkPqIJ9xnL:-O5OTAWx3ODw4hPOKSbH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L415)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`contact` should have a `dict` method, and using that would be better than using `vars`.
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 416 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IL7A64L9dwSvj5Kjs:-O5OTCWq5Yi1juaUgSeH:bxoh1co) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L416)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should never happen.
</blockquote></details>

Yes correct not at this level correct, it can happen when you have the wrong user ID
___
*[`saltapi/web/api/users.py` line 419 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IL-23AuDfxJI0BnOk:-O5OUii2-p5-AG6txHQg:b-7tfmjp) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/api/users.py#L419)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Newline missing at file end.
</blockquote></details>

added
___
*[`saltapi/web/schema/user.py` line 202 at r1](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5IMz738CbwUS2s6VmU:-O5OVWMQDi_2hViXdC1q:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/47afebc528e8abe43a04de4503c5c3a11fbf737e/saltapi/web/schema/user.py#L202)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Email > Email address
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/325)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/web/schema/user.py` line 201 at r2](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5ScWtv1XHs17ZcO-ds:-O5ScWtv1XHs17ZcO-dt:b-bu8l2b) ([raw file](https://github.com/saltastroops/salt-api/blob/24d3469c832db897ad719241d422bfe4e38dd7fe/saltapi/web/schema/user.py#L201)):*
> ```Python
> class UserContact(BaseModel):
>     given_name: str = Field(..., title="Given name", description="Given name.")
>     family_name: str = Field(..., title="Family name", description="Family name.")
> ```

Including a "The" is inconsistent with the other descriptions.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/325)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/web/schema/user.py` line 201 at r2](https://reviewable.io/reviews/saltastroops/salt-api/325#-O5ScWtv1XHs17ZcO-ds:-O8bVECd9-y2_LufoPp6:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/24d3469c832db897ad719241d422bfe4e38dd7fe/saltapi/web/schema/user.py#L201)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Including a "The" is inconsistent with the other descriptions.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/325)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
