### PR TITLE
Fixed access and Cors related issues

### PR DESCRIPTION
**Pull request by hettlage**
* Read allowed origin from setting

* Allow all HTTP headers with CORS

* Use datetime (not just date) for token expiry

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/14)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/14)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[saltapi/main.py, line 20 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/14#-MhNwhG1EL2CvUT6BsT9:-MhNwhG1EL2CvUT6BsTA:bwyj3wm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6781f20ff7f590914a80bb9e8fa1a59f1d6c3279/saltapi/main.py#L20)):*
> ```Python
> 
> app.include_router(blocks_router)
> app.include_router(proposals_router)
> ```

missing authenticatoin router

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/14)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[saltapi/main.py, line 20 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/14#-MhNwhG1EL2CvUT6BsT9:-MhO1CJe42XNeFNMIQmZ:b-jf8of6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6781f20ff7f590914a80bb9e8fa1a59f1d6c3279/saltapi/main.py#L20)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

missing authenticatoin router
</blockquote></details>

Oops, sorry. Switching between different branches took its toll...

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/14)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @hettlage)

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
