### PR TITLE
So page

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
The code doesn't run, `xmltodict` is listed twice in the pyproject.toml file.

> Reviewed 6 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93#-:-NDRqgXZ4NCOdXdEDsR2:b-soxxkr)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`saltapi/settings.py` line 103 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRvplT7xftrvc2OWzx:-NDRvplT7xftrvc2OWzy:b-as2g2s) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/settings.py#L103)):*
> ```Python
>     mapping_tool_image_conversion_command: str
> 
>     # ?
> ```

Maybe worth adding as a ToDo?
___
*[`saltapi/repository/block_repository.py` line 785 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRtOnr2uPxV_Cce7uA:-NDRtOnr2uPxV_Cce7uB:b2eekm5) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/repository/block_repository.py#L785)):*
> ```Python
>         stmt = text("SELECT Block_Id FROM schedule")
>         result = self.connection.execute(stmt)
>         block_id = cast(int, result.scalar_one())
> ```

Maybe use `try catch` for cases with no scheduled block since it raises an SQL error? Or try handling `sqlalchemy.exc.NoResultFound: No row was found when one was required` raised on this line?
___
*[`saltapi/web/api/blocks.py` line 23 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRvaBJ0gDsHjziAqe5:-NDRvaBJ0gDsHjziAqe6:bsp750) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L23)):*
> ```Python
> def get_scheduled_block(user: User = Depends(get_current_user)) -> _Block:
>     """
> ```

Docstring missing.

**Review by Eb-Zeero — COMMENTED** [review]
fixed now it is onence

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93#-:-NDhTH4z2--TGPXIlKsr:b-u407yy)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/settings.py` line 103 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRvplT7xftrvc2OWzx:-NDbyV6N7c0NqNPFGjtC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/settings.py#L103)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Maybe worth adding as a ToDo?
</blockquote></details>

Done.
___
*[`saltapi/repository/block_repository.py` line 785 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRtOnr2uPxV_Cce7uA:-NDhY0Mp5Bd0kjTliWf0:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/repository/block_repository.py#L785)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Maybe use `try catch` for cases with no scheduled block since it raises an SQL error? Or try handling `sqlalchemy.exc.NoResultFound: No row was found when one was required` raised on this line?
</blockquote></details>

Done.
___
*[`saltapi/web/api/blocks.py` line 23 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRvaBJ0gDsHjziAqe5:-NDhT7844f3qv42FccRk:b-7tfmjp) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L23)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Docstring missing.
</blockquote></details>

added

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/blocks.py` line 23 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRvaBJ0gDsHjziAqe5:-NDhYtO47tujTX5D1BoY:b90r4v8) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L23)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

added
</blockquote></details>

Some nit-picking and for consistency, maybe use a small letter s?
"Get the scheduled block"
___
*[`saltapi/web/api/blocks.py` line 54 at r2](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhZ8Ij5bkOkbj5md8E:-NDhZ8Ij5bkOkbj5md8F:b-gdol63) ([raw file](https://github.com/saltastroops/salt-api/blob/55b9ab484b167b1d7477731de06c0e0fb6ae03ac/saltapi/web/api/blocks.py#L54)):*
>> "Get the next scheduled block"

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93)* status: all files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/settings.py` line 103 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRvplT7xftrvc2OWzx:-NDhGzuXECpnV3EEYRnU:b-f0iihd) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/settings.py#L103)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Maybe worth adding as a ToDo?
</blockquote></details>

```# URL for getting the TCS ICD file```

And shouldn't the variable be called `tcs_icd_url` rather than `tcs_icd`?
___
*[`saltapi/repository/block_repository.py` line 785 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRtOnr2uPxV_Cce7uA:-NDhFWEs9vSp6bAZNUqC:b4jqq96) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/repository/block_repository.py#L785)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Maybe use `try catch` for cases with no scheduled block since it raises an SQL error? Or try handling `sqlalchemy.exc.NoResultFound: No row was found when one was required` raised on this line?
</blockquote></details>

Isn't there a method `one_or_none`?
___
*[`saltapi/repository/block_repository.py` line 787 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhFmCD3qGMxKRB8qdV:-NDhFmCD3qGMxKRB8qdW:b-ortyqo) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/repository/block_repository.py#L787)):*
> ```Python
>         block_id = cast(int, result.scalar_one())
>         if not block_id:
>             return FileNotFoundError()
> ```

I don't think this should be a FileNotFoundError? Also, as it is legitimate that no block is scheduled, wouldn't you return `None` rather than throw an error?
___
*[`saltapi/web/api/blocks.py` line 32 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhIn-C1Bo7EeCptvz1:-NDhIn-C1Bo7EeCptvz2:b-yhfee2) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L32)):*
> ```Python
>                 or permission_service.check_user_has_role(user, Role.SALT_ASTRONOMER) \
>                 or permission_service.check_user_has_role(user, Role.SALT_OPERATOR):
>             file = requests.get(get_settings().tcs_icd)
> ```

All this logic should be in a repository method, I'd say.

Also, a question regarding naming the endpoints. Shouldn't `/scheduled-block` be `/current-block`? And maybe `-block` could be dropped, given that there is a `/blocks/` prefix anyway?
___
*[`saltapi/web/api/blocks.py` line 34 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhHh9m4TQXviwHpmP2:-NDhHh9m4TQXviwHpmP3:b-nk8uq4) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L34)):*
> ```Python
>             file = requests.get(get_settings().tcs_icd)
>             xml_file = minidom.parseString(file.text)
>             models = xml_file.getElementsByTagName('String')
> ```

It is not clear why the variable is called `models`.

**Review by Eb-Zeero — COMMENTED** [review]
*onence -> only once

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93#-:-NDlpeI8AvytZL9hpR-0:b-9uzvu1)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`saltapi/settings.py` line 103 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRvplT7xftrvc2OWzx:-NDlq0ga5e_A9kHYlRmW:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/settings.py#L103)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

```# URL for getting the TCS ICD file```

And shouldn't the variable be called `tcs_icd_url` rather than `tcs_icd`?
</blockquote></details>

fixed
___
*[`saltapi/repository/block_repository.py` line 785 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRtOnr2uPxV_Cce7uA:-NDlly0K2QHw5yqFy4w8:b3z88jx) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/repository/block_repository.py#L785)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't there a method `one_or_none`?
</blockquote></details>

yes, there is using it now.
___
*[`saltapi/repository/block_repository.py` line 787 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhFmCD3qGMxKRB8qdV:-NDlmFHuCRRCU_jtqgyT:b-6ylied) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/repository/block_repository.py#L787)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this should be a FileNotFoundError? Also, as it is legitimate that no block is scheduled, wouldn't you return `None` rather than throw an error?
</blockquote></details>

now returning none or block
___
*[`saltapi/web/api/blocks.py` line 23 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDRvaBJ0gDsHjziAqe5:-NDlo2a37hPSH2UBHk_O:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L23)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Some nit-picking and for consistency, maybe use a small letter s?
"Get the scheduled block"
</blockquote></details>

Done.
___
*[`saltapi/web/api/blocks.py` line 32 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhIn-C1Bo7EeCptvz1:-NDloZG44XNRawWBVdR-:bbhrvje) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

All this logic should be in a repository method, I'd say.

Also, a question regarding naming the endpoints. Shouldn't `/scheduled-block` be `/current-block`? And maybe `-block` could be dropped, given that there is a `/blocks/` prefix anyway?
</blockquote></details>

Done. `current-block`
`blocks/current` will not be clear whether it is current blocks or just one block
I propose to keep the `-block`
___
*[`saltapi/web/api/blocks.py` line 34 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhHh9m4TQXviwHpmP2:-NDlpN_A5b_1L7e2agFr:biemehd) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It is not clear why the variable is called `models`.
</blockquote></details>

yes correct named it elements
___
*[`saltapi/web/api/blocks.py` line 54 at r2](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhZ8Ij5bkOkbj5md8E:-NDlpYRYCWT2nawzOva3:b-st8lp5) ([raw file](https://github.com/saltastroops/salt-api/blob/55b9ab484b167b1d7477731de06c0e0fb6ae03ac/saltapi/web/api/blocks.py#L54)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

>> "Get the next scheduled block"
</blockquote></details>

nice one :)

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/block_repository.py` line 779 at r3](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmObdc0iZ_vhkJeYyO:-NDmObdc0iZ_vhkJeYyP:b-h884sy) ([raw file](https://github.com/saltastroops/salt-api/blob/97bb8880f42062d33c897390f8052eaaf03d9b33/saltapi/repository/block_repository.py#L779)):*
> ```Python
>         return cast(bool, result.scalar_one() > 1)
> 
>     def get_next_scheduled_block(self) -> Block:
> ```

The return value is `Optional[Block]` now.
___
*[`saltapi/web/api/blocks.py` line 32 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhIn-C1Bo7EeCptvz1:-NDmPjBf7kQkngz6iMZQ:b9fy7u1) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L32)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done. `current-block`
`blocks/current` will not be clear whether it is current blocks or just one block
I propose to keep the `-block`
</blockquote></details>

But you haven't addressed my other concern... API functions should be simple, which is why I suggested to move the logic (other than permission checks) into a repository (or service?) function.
___
*[`saltapi/web/api/blocks.py` line 23 at r3](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmPoHO6pTSbzF7pflX:-NDmPoHPD39D3-11Annp:beemj18) ([raw file](https://github.com/saltastroops/salt-api/blob/97bb8880f42062d33c897390f8052eaaf03d9b33/saltapi/web/api/blocks.py#L23)):*
> ```Python
> def get_current_block(user: User = Depends(get_current_user)) -> _Block:
>     """
>     Get the scheduled block.
> ```

scheduled > currently observed

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/block_repository.py` line 779 at r3](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmObdc0iZ_vhkJeYyO:-NDmlXTe3LocnojXNO3g:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/97bb8880f42062d33c897390f8052eaaf03d9b33/saltapi/repository/block_repository.py#L779)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The return value is `Optional[Block]` now.
</blockquote></details>

Done.
___
*[`saltapi/web/api/blocks.py` line 32 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhIn-C1Bo7EeCptvz1:-NDmoVBxEfICBZULAnCe:b2nf5qn) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But you haven't addressed my other concern... API functions should be simple, which is why I suggested to move the logic (other than permission checks) into a repository (or service?) function.
</blockquote></details>

I knew I missed something.
Done now
___
*[`saltapi/web/api/blocks.py` line 23 at r3](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmPoHO6pTSbzF7pflX:-NDmliTJ7Skp7w0pKd8_:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/97bb8880f42062d33c897390f8052eaaf03d9b33/saltapi/web/api/blocks.py#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

scheduled > currently observed
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/service/block_service.py` line 64 at r4](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmqHi8CnrrpYjT-4OR:-NDmqHi8CnrrpYjT-4OS:b-cmnqyr) ([raw file](https://github.com/saltastroops/salt-api/blob/86b4e20dd73afc3141d6ffae7d1e0f7405191ce4/saltapi/service/block_service.py#L64)):*
> ```Python
> 
>     @staticmethod
>     def get_current_block_id() -> int:
> ```

It might be better to have a ,method `get_current_block`.
___
*[`saltapi/service/block_service.py` line 76 at r4](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmpy8w0AfF3Hgvi7Aw:-NDmpy8w0AfF3Hgvi7Ax:b5d2p9q) ([raw file](https://github.com/saltastroops/salt-api/blob/86b4e20dd73afc3141d6ffae7d1e0f7405191ce4/saltapi/service/block_service.py#L76)):*
> ```Python
>                 value = els.getElementsByTagName('Val')
>                 block_id = value.item(0).firstChild.data
>         if not block_id:
> ```

I'm not convinced there has to be a current block; so you probably should return `None` rather than raising an error.
___
*[`saltapi/web/api/blocks.py` line 32 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhIn-C1Bo7EeCptvz1:-NDmpTGdBQcHryegcVU-:bza9frx) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L32)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I knew I missed something.
Done now
</blockquote></details>

Nitpicking, I know, but:

This method is asking the service for an _id_ and then uses it to get the block.

But the method for the next selected block just calls a method for getting the block.

I think this is a bit inconsistent... :(
___
*[`saltapi/web/api/blocks.py` line 23 at r3](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmPoHO6pTSbzF7pflX:-NDmp8eP62bPLd9z6Rjx:bppkxxf) ([raw file](https://github.com/saltastroops/salt-api/blob/97bb8880f42062d33c897390f8052eaaf03d9b33/saltapi/web/api/blocks.py#L23)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I missed this earlier, but there is a "block" missing:

Get the currently observed block.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/block_service.py` line 64 at r4](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmqHi8CnrrpYjT-4OR:-NDmtNXz-zcPwqf-0DXT:b83hz5f) ([raw file](https://github.com/saltastroops/salt-api/blob/86b4e20dd73afc3141d6ffae7d1e0f7405191ce4/saltapi/service/block_service.py#L64)):*
> get_current_block
renamed
___
*[`saltapi/service/block_service.py` line 76 at r4](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmpy8w0AfF3Hgvi7Aw:-NDmtSLp-D25fOZAYO9G:b-ce8e59) ([raw file](https://github.com/saltastroops/salt-api/blob/86b4e20dd73afc3141d6ffae7d1e0f7405191ce4/saltapi/service/block_service.py#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced there has to be a current block; so you probably should return `None` rather than raising an error.
</blockquote></details>

None Returened
___
*[`saltapi/web/api/blocks.py` line 32 at r1](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDhIn-C1Bo7EeCptvz1:-NDmtxuS8QMEMCJYSaiV:bqglh5z) ([raw file](https://github.com/saltastroops/salt-api/blob/cf45fc5f17cf95b832dcb8ab81c92480dd1db374/saltapi/web/api/blocks.py#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nitpicking, I know, but:

This method is asking the service for an _id_ and then uses it to get the block.

But the method for the next selected block just calls a method for getting the block.

I think this is a bit inconsistent... :(
</blockquote></details>

yeah noticed this after pushing it is fixed now
___
*[`saltapi/web/api/blocks.py` line 23 at r3](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmPoHO6pTSbzF7pflX:-NDmu4i25tER4vBpCb9V:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/97bb8880f42062d33c897390f8052eaaf03d9b33/saltapi/web/api/blocks.py#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, I missed this earlier, but there is a "block" missing:

Get the currently observed block.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/service/block_service.py` line 65 at r5](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmwQo7ExEzZKq8eMHa:-NDmwQo7ExEzZKq8eMHb:b-92jwcr) ([raw file](https://github.com/saltastroops/salt-api/blob/ddb6ab9c2cf32ca33ef49560ba67777c8093c072/saltapi/service/block_service.py#L65)):*
> ```Python
>     def get_current_block(self) -> Optional[Block]:
>         """
>         Get Current observed block. If block not found returns None
> ```

Return the currently observed block.

None is returned if there is no currently observed block.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/service/block_service.py` line 65 at r5](https://reviewable.io/reviews/saltastroops/salt-api/93#-NDmwQo7ExEzZKq8eMHa:-NE-eAJI-LVbGjh_9nE4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/ddb6ab9c2cf32ca33ef49560ba67777c8093c072/saltapi/service/block_service.py#L65)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Return the currently observed block.

None is returned if there is no currently observed block.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
