### PR TITLE
Get proposal endpoint updates

### LINKED ISSUE #49: One more proposals End-point
we should be able to query proposal by
PI, semester, year and phase and more if needed

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/250)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/250)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/web/api/proposals.py` line 163 at r1](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRMC4O8-GVYGzCc53Y:-NhRMC4O8-GVYGzCc53Z:bluz6u9) ([raw file](https://github.com/saltastroops/salt-api/blob/92d82bdb714d8a14b4953febbe7f8f4aa097a60b/saltapi/web/api/proposals.py#L163)):*
> ```Python
>         description="Proposal code of the returned proposal.",
>     ),
>     semester: Union[Semester | None] = Query(
> ```

Simpler : `Optional[Semester]`
___
*[`saltapi/web/api/proposals.py` line 168 at r1](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRMKOz0sZMqR5yZDkl:-NhRMKOz0sZMqR5yZDkm:b6srbn0) ([raw file](https://github.com/saltastroops/salt-api/blob/92d82bdb714d8a14b4953febbe7f8f4aa097a60b/saltapi/web/api/proposals.py#L168)):*
> ```Python
>         title="Semester",
>     ),
>     phase: Optional[int] = Query(
> ```

Simpler : `Optional[int]`
___
*[`saltapi/web/api/proposals.py` line 176 at r1](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRMR8-27BLKPDErh5K:-NhRMR8-27BLKPDErh5L:bub8u4o) ([raw file](https://github.com/saltastroops/salt-api/blob/92d82bdb714d8a14b4953febbe7f8f4aa097a60b/saltapi/web/api/proposals.py#L176)):*
> ```Python
> ) -> _Proposal:
>     """
>     Returns a JSON representation of the proposal with a given proposal code, semester and phase.
> ```

You should state what the default values are for the semester and phase.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/250)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/api/proposals.py` line 163 at r1](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRMC4O8-GVYGzCc53Y:-NhRP7PsDLjWnMPhF7ol:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/92d82bdb714d8a14b4953febbe7f8f4aa097a60b/saltapi/web/api/proposals.py#L163)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Simpler : `Optional[Semester]`
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 168 at r1](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRMKOz0sZMqR5yZDkl:-NhRP7sGARmK8Hy-4a0G:bf7kf4m) ([raw file](https://github.com/saltastroops/salt-api/blob/92d82bdb714d8a14b4953febbe7f8f4aa097a60b/saltapi/web/api/proposals.py#L168)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Simpler : `Optional[int]`
</blockquote></details>

As confirmed this comment is a mistake, as such it has been ignored.
___
*[`saltapi/web/api/proposals.py` line 176 at r1](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRMR8-27BLKPDErh5K:-NhRQEvf9bM3jBTkDX8k:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/92d82bdb714d8a14b4953febbe7f8f4aa097a60b/saltapi/web/api/proposals.py#L176)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should state what the default values are for the semester and phase.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/250)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/web/api/proposals.py` line 177 at r2](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRvni15SYQpqBQn1Tm:-NhRvni15SYQpqBQn1Tn:bdjjeig) ([raw file](https://github.com/saltastroops/salt-api/blob/3190c631e5e6b70c9987fc1e061db0a2e2e86637/saltapi/web/api/proposals.py#L177)):*
> ```Python
>     """
>     Returns a JSON representation of the proposal with a given proposal code, semester and phase.
>     The default values for semester and phase are the latest submission semester and phase, respectively.
> ```

Maybe better: "... are those chosen during the latest submission." ?
___
*[`saltapi/web/api/proposals.py` line 312 at r2](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRwHbR6dhInwtF89Yg:-NhRwHbR6dhInwtF89Yh:bsaqshv) ([raw file](https://github.com/saltastroops/salt-api/blob/3190c631e5e6b70c9987fc1e061db0a2e2e86637/saltapi/web/api/proposals.py#L312)):*
> ```Python
>         )
>         proposal_service = services.proposal_service(unit_of_work.connection)
>         proposal = proposal_service.get_proposal(proposal_code, None, None)
> ```

Wouldn't the more natural change be to assign `None` as the default value for the phase and semester in the `get_proposal` method?
___
*[`saltapi/web/api/proposals.py` line 331 at r2](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRwXpT6zzqS1clhz3q:-NhRwXpT6zzqS1clhz3r:bsaqshv) ([raw file](https://github.com/saltastroops/salt-api/blob/3190c631e5e6b70c9987fc1e061db0a2e2e86637/saltapi/web/api/proposals.py#L331)):*
> ```Python
>                 proprietary_period=proprietary_period_update_request.proprietary_period,
>             )
>             proposal = proposal_service.get_proposal(proposal_code, None, None)
> ```

Wouldn't the more natural change be to assign `None` as the default value for the phase and semester in the `get_proposal` method?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/250)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/api/proposals.py` line 177 at r2](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRvni15SYQpqBQn1Tm:-NhVGGWnE8NTWdEgTuLh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3190c631e5e6b70c9987fc1e061db0a2e2e86637/saltapi/web/api/proposals.py#L177)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: "... are those chosen during the latest submission." ?
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 312 at r2](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRwHbR6dhInwtF89Yg:-NhVGcW6DyYklvlBmQS7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3190c631e5e6b70c9987fc1e061db0a2e2e86637/saltapi/web/api/proposals.py#L312)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't the more natural change be to assign `None` as the default value for the phase and semester in the `get_proposal` method?
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 331 at r2](https://reviewable.io/reviews/saltastroops/salt-api/250#-NhRwXpT6zzqS1clhz3q:-NhVGct1DOgDvYJg0bax:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3190c631e5e6b70c9987fc1e061db0a2e2e86637/saltapi/web/api/proposals.py#L331)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't the more natural change be to assign `None` as the default value for the phase and semester in the `get_proposal` method?
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
