### PR TITLE
Progress report updates

### LINKED ISSUE #167: Case of no additional pdf gives an error
If you try to submit a progress report without an additional pdf, an internal server error occurs.

### PR DESCRIPTION
**Pull request by hettlage**
Fixes #167

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/168)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/168)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/repository/test_proposal_repository.py` line 768 at r1](https://reviewable.io/reviews/saltastroops/salt-api/168#-NNvRbIF4YBUKzxRMMgt:-NNvRbIF4YBUKzxRMMgu:b-2w9d6g) ([raw file](https://github.com/saltastroops/salt-api/blob/a29f5a4675098ce89a88b20e6e0c27af9ce3ad34/tests/repository/test_proposal_repository.py#L768)):*
> ```Python
> 
> 
> def test_insert_progress_report_can_be_repeated(db_connection: Connection) -> None:
> ```

This test seems to be trivial when no assertion statements are used. Even when commenting out the logic line `proposal_repository.insert_or_update_proposal_progress` and below, the test still passes.

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/168)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`tests/repository/test_proposal_repository.py` line 768 at r1](https://reviewable.io/reviews/saltastroops/salt-api/168#-NNvRbIF4YBUKzxRMMgt:-NNvWg7w2jc0EVbKuF9M:b-qloziv) ([raw file](https://github.com/saltastroops/salt-api/blob/a29f5a4675098ce89a88b20e6e0c27af9ce3ad34/tests/repository/test_proposal_repository.py#L768)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

This test seems to be trivial when no assertion statements are used. Even when commenting out the logic line `proposal_repository.insert_or_update_proposal_progress` and below, the test still passes.
</blockquote></details>

Ok, I've added an assertion so that it fails more gracefully.

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/168)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/repository/test_proposal_repository.py` line 768 at r1](https://reviewable.io/reviews/saltastroops/salt-api/168#-NNvRbIF4YBUKzxRMMgt:-NNvaAyo9Hsn_MyehXRw:bx85zax) ([raw file](https://github.com/saltastroops/salt-api/blob/a29f5a4675098ce89a88b20e6e0c27af9ce3ad34/tests/repository/test_proposal_repository.py#L768)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ok, I've added an assertion so that it fails more gracefully.
</blockquote></details>

Why not use `proposal_repository.get_progress_report` after updating and assert that the respective file entries were updated?

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/168)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
