### PR TITLE
Jenkins pipeline

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/218)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 12 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/218)* status: 12 of 17 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`jenkins/tests/Jenkinsfile` line 6 at r1](https://reviewable.io/reviews/saltastroops/salt-api/218#-NURCZFZCBCUKmdRcGds:-NURCZFZCBCUKmdRcGdt:b827dph) ([raw file](https://github.com/saltastroops/salt-api/blob/1a9941574af453a5b526c42bd5b3fc577ccc71cd/jenkins/tests/Jenkinsfile#L6)):*
> ```Groovy
>   agent {
>     dockerfile {
>       filename 'Dockerfile'
> ```

I get the following error when running the pipeline:

"Required context class hudson.FilePath is missing"
It appears to be `Dockerfile`, it not found. Maybe the path is incorrect?

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/218)* status: 11 of 17 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`jenkins/tests/Jenkinsfile` line 6 at r1](https://reviewable.io/reviews/saltastroops/salt-api/218#-NURCZFZCBCUKmdRcGds:-NUTPiVUAWQ4bfSRtDdN:bpyrk5z) ([raw file](https://github.com/saltastroops/salt-api/blob/1a9941574af453a5b526c42bd5b3fc577ccc71cd/jenkins/tests/Jenkinsfile#L6)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I get the following error when running the pipeline:

"Required context class hudson.FilePath is missing"
It appears to be `Dockerfile`, it not found. Maybe the path is incorrect? 
</blockquote></details>

Okay, the dir Argument was clearly incorrect. But it still worked for me...

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 5 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/218)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`jenkins/tests/Jenkinsfile` line 17 at r2](https://reviewable.io/reviews/saltastroops/salt-api/218#-NU_Bqqn6a9LDbSKIo9w:-NU_Bqqp5u79giqJKbiH:b-vi7axg) ([raw file](https://github.com/saltastroops/salt-api/blob/8a2db6a9a78d3c7c2621ca46aaa06f03ebec4a82/jenkins/tests/Jenkinsfile#L17)):*
> ```Groovy
>     stage("Run tests") {
>       steps {
>         sh './jenkins/run-tests.sh'
> ```

Now the pipeline is failing with the following error:

"./jenkins/run-tests.sh: not found"

sh './jenkins/run-tests.sh' >> sh './jenkins/tests/run-tests.sh' ?

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/218)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

**Pull request merged**
