### PR TITLE
rss-masks-updates

### LINKED ISSUE #43: General method for RSS masks in magazine
There currently is a method `get_mos_mask_in_magazine` in `instrument_repository.py` and `rss_repository.py`. These should be replaced with more general methods return _all_ RSS masks in the magazine. Such methods should accept an array of mask types to filter by.

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Updates for RSS masks in magazine method

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/76)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/76)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/web/api/instruments.py` line 34 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N54fn3u1VapR7URvW56:-N54fn3u1VapR7URvW57:b-x4nj0b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0175090ae59e75baeec02652cd4c4bd36f20be20/saltapi/web/api/instruments.py#L34)):*
> ```Python
>     Mask Type | Description
>     --- | ---
>     Longslit | Single, 8 arcmin long, 0.6/1.0/1.25/1.5/2.0/3.0/4.0 arcsec wide slit (- version 2).
> ```

Maybe it would be better to have a generic description rather than listing all the available masks for a type?

Also "N/A" for MOS might be misleading, as it could be interpreted as saying the MOS type is unavailable.
___
*[`saltapi/web/api/instruments.py` line 124 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N54gCYzC0_biBogxLbL:-N54gCYzC0_biBogxLbM:b-pswqnx) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0175090ae59e75baeec02652cd4c4bd36f20be20/saltapi/web/api/instruments.py#L124)):*
> ```Python
> def get_obsolete_rss_masks_in_magazine(
>     mask_types: List[str] = Query(
>         [], title="Mask types", description="The mask types."
> ```

Maybe: "The mask types" > "The mask to types to include"

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/76)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/api/instruments.py` line 34 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N54fn3u1VapR7URvW56:-N5GYwcKDlXz2zqgbaVi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0175090ae59e75baeec02652cd4c4bd36f20be20/saltapi/web/api/instruments.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe it would be better to have a generic description rather than listing all the available masks for a type?

Also "N/A" for MOS might be misleading, as it could be interpreted as saying the MOS type is unavailable.
</blockquote></details>

Done.
___
*[`saltapi/web/api/instruments.py` line 124 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N54gCYzC0_biBogxLbL:-N5GYx1n99qTuNXcQydf:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0175090ae59e75baeec02652cd4c4bd36f20be20/saltapi/web/api/instruments.py#L124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe: "The mask types" > "The mask to types to include"
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/76)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/web/api/instruments.py` line 34 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N54fn3u1VapR7URvW56:-N5K2rLJ1rw6hle_iZiV:beubh4t) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0175090ae59e75baeec02652cd4c4bd36f20be20/saltapi/web/api/instruments.py#L34)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

How about:

Longslit | Longslit
Imaging | Imaging mask
MOS | Mask for multi-object sppectroscopy
Engineering | Engineering mask

But typing this, I notice something else: Shouldn't the mask type be an enum rather than a string?
___
*[`saltapi/web/api/instruments.py` line 124 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N54gCYzC0_biBogxLbL:-N5K3Xei8hZwbe4p0vDw:bmbe91d) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0175090ae59e75baeec02652cd4c4bd36f20be20/saltapi/web/api/instruments.py#L124)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I notice something else: Shouldn't the mask type be an enum rather than a string?
___
*[`tests/integration/instruments/test_get_rss_masks_in_magazine.py` line 34 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N5K3wVFCxkHTY1Ae9Ij:-N5K3wVFCxkHTY1Ae9Ik:b-9c89z8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/aa77f3aa43de1f76fe77269d149c9361743f2a0a/tests/integration/instruments/test_get_rss_masks_in_magazine.py#L34)):*
> ```Python
>         params={"mask_types": ["MOS", "Imaging", "Engineering"]},
>     )
>     assert response.status_code == status.HTTP_200_OK
> ```

These tests are potentially brittle: What if currently there is no MOS, imaging or engineering mask in the magazine?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/76)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/api/instruments.py` line 34 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N54fn3u1VapR7URvW56:-N5KaAS35kKOvBWBweHL:b210pum) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0175090ae59e75baeec02652cd4c4bd36f20be20/saltapi/web/api/instruments.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about:

Longslit | Longslit
Imaging | Imaging mask
MOS | Mask for multi-object sppectroscopy
Engineering | Engineering mask

But typing this, I notice something else: Shouldn't the mask type be an enum rather than a string?

</blockquote></details>

You're right, it should be and I have fixed it now.
___
*[`saltapi/web/api/instruments.py` line 124 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N54gCYzC0_biBogxLbL:-N5Kazz-2rLXUFpK5B4T:b7yukl1) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0175090ae59e75baeec02652cd4c4bd36f20be20/saltapi/web/api/instruments.py#L124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I notice something else: Shouldn't the mask type be an enum rather than a string?
</blockquote></details>

You're right, it is fixed now.
___
*[`tests/integration/instruments/test_get_rss_masks_in_magazine.py` line 34 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N5K3wVFCxkHTY1Ae9Ij:-N5Kn3Tq2ogVAE6MO5L-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/aa77f3aa43de1f76fe77269d149c9361743f2a0a/tests/integration/instruments/test_get_rss_masks_in_magazine.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

These tests are potentially brittle: What if currently there is no MOS, imaging or engineering mask in the magazine?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/76)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`saltapi/repository/rss_repository.py` line 421 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N5o-LQGAJGVSfRtkqZP:-N5o-LQH33VZii5AYcFO:b-ks2fo3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/aa02136b305f2c743f8256b638ff5d5b47f59bdd/saltapi/repository/rss_repository.py#L421)):*
> ```Python
> 
>         results = self.connection.execute(text(stmt), {"mask_type": mask_types})
>         print([row.barcode for row in results])
> ```

Unnecessary print statement

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/76)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`saltapi/repository/rss_repository.py` line 421 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-N5o-LQGAJGVSfRtkqZP:-N5o-LQH33VZii5AYcFO:b-ks2fo3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/aa02136b305f2c743f8256b638ff5d5b47f59bdd/saltapi/repository/rss_repository.py#L421)):*
> ```Python
> 
>         results = self.connection.execute(text(stmt), {"mask_type": mask_types})
>         print([row.barcode for row in results])
> ```

Unnecessary print statement

**Review by mofokeng-chaka — COMMENTED** [review]
Done removing the unnecessary print statement.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/76#-:-N678WgAEwkOJLncL5rq:b6gtp5d)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/76)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
