### PR TITLE
backend changes corresponding to frontend issue: check PI/PC with user id

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/51)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/51)* status: all files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[saltapi/repository/proposal_repository.py, line 145 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/51#-MzL5Kh_3ohQHEC5huJV:-MzL5Kh_3ohQHEC5huJW:bq21bve) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f4ae5d0c849b77d56f047156751a40e910b9531d/saltapi/repository/proposal_repository.py#L145)):*
> ```Python
>                 "proposal_type": self._map_proposal_type(row.proposal_type),
>                 "principal_investigator": {
>                     "id": self._principal_investigator_user_id(row.proposal_code),
> ```

I don't think you need this; you should be able to get the id in the query above (as you do for thew liaison astronomer already).
___
*[saltapi/repository/proposal_repository.py, line 151 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/51#-MzL5d0o7dJ6tNLE9tF5:-MzL5d0o7dJ6tNLE9tF6:bq21bve) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f4ae5d0c849b77d56f047156751a40e910b9531d/saltapi/repository/proposal_repository.py#L151)):*
> ```Python
>                 },
>                 "principal_contact": {
>                     "id": self._principal_contact_user_id(row.proposal_code),
> ```

I don't think you need this; you should be able to get the id in the query above (as you do for thew liaison astronomer already).
___
*[saltapi/web/schema/proposal.py, line 38 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/51#-MzL5pFf7tQsjJsAhBD1:-MzL5pFf7tQsjJsAhBD2:brn1x40) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f4ae5d0c849b77d56f047156751a40e910b9531d/saltapi/web/schema/proposal.py#L38)):*
> ```Python
> 
> 
> class ContactDetails(BaseModel):
> ```

As highlighted in the corresponding frontend PR, I consider including the user id in the contact details problematic. See that PR for a suggested alternative solution.
___
*[tests/repository/test_user_repository.py, line 55 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/51#-MzL4w5iAnMg5giVVKtr:-MzL4w5jAyD_zEUCGgbs:bozlb7s) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ad61f482abd16bd508372f0e919c1273d062fc34/tests/repository/test_user_repository.py#L55)):*
> ```Python
> 
> @nodatabase
> def test_get_user_by_email_returns_correct_user(
> ```

Why did you remove this test?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/51)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/proposal_repository.py, line 145 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/51#-MzL5Kh_3ohQHEC5huJV:-MzOKEtf9_-8JV4zS7XO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f4ae5d0c849b77d56f047156751a40e910b9531d/saltapi/repository/proposal_repository.py#L145)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need this; you should be able to get the id in the query above (as you do for thew liaison astronomer already).
</blockquote></details>

Done.
___
*[saltapi/repository/proposal_repository.py, line 151 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/51#-MzL5d0o7dJ6tNLE9tF5:-MzOJNYH2Gm-aF4hNxuN:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f4ae5d0c849b77d56f047156751a40e910b9531d/saltapi/repository/proposal_repository.py#L151)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need this; you should be able to get the id in the query above (as you do for thew liaison astronomer already).
</blockquote></details>

Done.
___
*[saltapi/web/schema/proposal.py, line 38 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/51#-MzL5pFf7tQsjJsAhBD1:-MzOJMwS8g3iW6IUWYqP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f4ae5d0c849b77d56f047156751a40e910b9531d/saltapi/web/schema/proposal.py#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As highlighted in the corresponding frontend PR, I consider including the user id in the contact details problematic. See that PR for a suggested alternative solution.
</blockquote></details>

Done.
___
*[tests/repository/test_user_repository.py, line 55 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/51#-MzL4w5iAnMg5giVVKtr:-MzOJCX8-IsfPydzUWxv:b-odey17) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ad61f482abd16bd508372f0e919c1273d062fc34/tests/repository/test_user_repository.py#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why did you remove this test?
</blockquote></details>

My mistake, I thought it was the same code as the test above.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/51)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[saltapi/repository/proposal_repository.py, line 151 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/51#-MzL5d0o7dJ6tNLE9tF5:-MzTsxHf4bUbcNuZpGu-:bjcbgsm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f4ae5d0c849b77d56f047156751a40e910b9531d/saltapi/repository/proposal_repository.py#L151)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change...

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/51)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[saltapi/repository/proposal_repository.py, line 151 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/51#-MzL5d0o7dJ6tNLE9tF5:-MzU4WRq-A52TLGJyPHP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f4ae5d0c849b77d56f047156751a40e910b9531d/saltapi/repository/proposal_repository.py#L151)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see a change...
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/51)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
