### PR TITLE
RSS current MOS masks

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/42)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/42)* status: all files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/repository/instrument_repository.py, line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwGNKAB9zIqByshOqH:-MvwGNKAB9zIqByshOqI:bw9uu4x) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/repository/instrument_repository.py#L35)):*
> ```Python
>         return self.bvit_repository.get(bvit_id)
> 
>     def get_mos_mask_in_magazine(self) -> List[str]:
> ```

I think it might be better to have  a method which returns all the masks, as this will be needed anyway.

But I will raise this as a separate issue.
___
*[saltapi/repository/instrument_repository.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwIgozCIouymYNs3ry:-MvwIgp-EzXx99WH3m3f:b9xnklr) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/repository/instrument_repository.py#L36)):*
> ```Python
> 
>     def get_mos_mask_in_magazine(self) -> List[str]:
>         """The list of MOS masks on the magazine"""
> ```

on the > in the

magazine > magazine.



_Code quote:_
```Python
get_mos_mask_in_magazine
```
___
*[saltapi/repository/rss_repository.py, line 409 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwIsdh62QgwQ7awjw8:-MvwIsdh62QgwQ7awjw9:b-dn97w8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/repository/rss_repository.py#L409)):*
> ```Python
>         stmt = text(
>             """
> SELECT Barcode AS barcode
> ```

Nit-picking: If you abbreviate all the other table names, you should abbreviate `Barcode` as well.
___
*[saltapi/service/instrument_service.py, line 11 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwJAeK8wNrAWeo5eiz:-MvwJAeK8wNrAWeo5ej-:b9xnklr) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/service/instrument_service.py#L11)):*
> ```Python
> 
>     def get_mos_mask_in_magazine(self) -> List[str]:
>         """The list of MOS masks on the magazine"""
> ```

on the > in the

magazine > magazine.
___
*[saltapi/web/api/instruments.py, line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwJdZ49AoRTeo2B9b_:-MvwJdZ49AoRTeo2B9ba:bep54ym) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/web/api/instruments.py#L10)):*
> ```Python
> 
> 
> router = APIRouter(prefix="/instruments", tags=["Instrument"])
> ```

This means you end up with a URL like `/instruments/rss/current-mos-masks`, and I'm not convinced of the need for the `instruments` part.
___
*[saltapi/web/api/instruments.py, line 14 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwKdZT2uanvWYioaUL:-MvwKdZT2uanvWYioaUM:blz8bj3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/web/api/instruments.py#L14)):*
> ```Python
> 
> @router.get(
>     "/rss/current-mos-mask",
> ```

current-mos-mssk > current-mos-msasks
___
*[saltapi/web/api/instruments.py, line 27 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwKpZ96tiIgKbpAkf1:-MvwKpZA5LnXRM1iZ-ek:b-dsjlzm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/web/api/instruments.py#L27)):*
> ```Python
>     with UnitOfWork() as unit_of_work:
>         permission_service = services.permission_service(unit_of_work.connection)
>         permission_service.check_permission_to_view_mos_data(user)
> ```

This is public information -- it is available on https://astronomers.salt.ac.za/status/ already.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/42)* status: all files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/repository/instrument_repository.py, line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwGNKAB9zIqByshOqH:-MvwXdZB4fE_VShQZlcU:b-1cyu7w) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/repository/instrument_repository.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think it might be better to have  a method which returns all the masks, as this will be needed anyway.

But I will raise this as a separate issue.
</blockquote></details>

thank you
___
*[saltapi/repository/instrument_repository.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwIgozCIouymYNs3ry:-MvwY7Bn19NZfLLWEsHm:b3kre) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/repository/instrument_repository.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

on the > in the

magazine > magazine.
</blockquote></details>

?
___
*[saltapi/repository/rss_repository.py, line 409 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwIsdh62QgwQ7awjw8:-MvwYK2O97ffyRYtvHKA:b-z5sxkc) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/repository/rss_repository.py#L409)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nit-picking: If you abbreviate all the other table names, you should abbreviate `Barcode` as well.
</blockquote></details>

that is the name I need on my results
___
*[saltapi/service/instrument_service.py, line 11 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwJAeK8wNrAWeo5eiz:-MvwZG5oBAXTmUnA5C5d:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/service/instrument_service.py#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

on the > in the

magazine > magazine.
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwJdZ49AoRTeo2B9b_:-MvwZbMNCjuFHldNHVdZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/web/api/instruments.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This means you end up with a URL like `/instruments/rss/current-mos-masks`, and I'm not convinced of the need for the `instruments` part.
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 14 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwKdZT2uanvWYioaUL:-MvwZd-tDM_ThHKrODh-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/web/api/instruments.py#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

current-mos-mssk > current-mos-msasks
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/42)* status: all files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/repository/instrument_repository.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwIgozCIouymYNs3ry:-MvxI2Mw0NR-y4boMZF7:b-54pay6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/repository/instrument_repository.py#L36)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

?
</blockquote></details>

Sorry, that cut-and-paste must have been accidental. :(
___
*[saltapi/repository/rss_repository.py, line 409 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwIsdh62QgwQ7awjw8:-MvxILUy8UkZDzGcOH9v:bsi8v3l) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/repository/rss_repository.py#L409)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

that is the name I need on my results
</blockquote></details>

Sorry, my bad.
___
*[saltapi/web/api/instruments.py, line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvxIn_t86O8fGQ2fdDo:-MvxIn_t86O8fGQ2fdDp:bock5vh) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/web/api/instruments.py#L7)):*
> ```Python
> from saltapi.service.authentication_service import get_current_user
> from saltapi.service.user import User
> from saltapi.web import services
> ```

operations".
___
*[saltapi/web/api/instruments.py, line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwJdZ49AoRTeo2B9b_:-MvxI_SeByK9R16pQIqd:brggbvp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/web/api/instruments.py#L10)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I suspect this might resurface. Maybe at some point there will have to be another router or some prefix like "telescope" or "operations".

But no need for action now.
___
*[saltapi/web/api/instruments.py, line 14 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwKdZT2uanvWYioaUL:-MvxIwM_CAAWZAa90P7N:b-bng84s) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/web/api/instruments.py#L14)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I had missed that: This applies to the function name as well:

get_current_mos_mask > get_current_mos_masks

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/42)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/instrument_repository.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwIgozCIouymYNs3ry:-Mw2c2NM1aG1AQMHsowu:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/repository/instrument_repository.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, that cut-and-paste must have been accidental. :(
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvxIn_t86O8fGQ2fdDo:-Mw5lJk65Qth-HXcawkh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/web/api/instruments.py#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

operations".
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwJdZ49AoRTeo2B9b_:-Mw2cAUV4DOysdViWoLD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/web/api/instruments.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I suspect this might resurface. Maybe at some point there will have to be another router or some prefix like "telescope" or "operations".

But no need for action now.
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 14 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-MvwKdZT2uanvWYioaUL:-Mw2cGVl3zfzeXaL9g9V:b-9f8j4v) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d097570f52f3060696e4aec9da0a6784fa865ad6/saltapi/web/api/instruments.py#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, I had missed that: This applies to the function name as well:

get_current_mos_mask > get_current_mos_masks
</blockquote></details>

I missed the name some how

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/42)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/repository/instrument_repository.py, line 39 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6Qcqp9LPMBgmQrftj:-Mw6Qcqp9LPMBgmQrftk:b6orenx) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/repository/instrument_repository.py#L39)):*
> ```Python
>         return self.rss_repository.get_mos_mask_in_magazine()
> 
>     def get_mos_block(self, semesters: List[str]) -> List[Dict[str, Any]]:
> ```

get_mos_block > get_mod_blocks
___
*[saltapi/repository/instrument_repository.py, line 40 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6Qjz7B8Y0CuuPeHpF:-Mw6Qjz7B8Y0CuuPeHpG:bu351ob) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/repository/instrument_repository.py#L40)):*
> ```Python
> 
>     def get_mos_block(self, semesters: List[str]) -> List[Dict[str, Any]]:
>         """The list of Mos block"""
> ```

Mos > MOS
___
*[saltapi/repository/rss_repository.py, line 442 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6Qosv1ibggoUaxFGx:-Mw6Qosv1ibggoUaxFGy:bcug6q6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/repository/rss_repository.py#L442)):*
> ```Python
>         return liaison_astronomers
> 
>     def get_mos_block(self, semesters: List[str]) -> List[Dict[str, Any]]:
> ```

get_mos_block > get_mos_blocks
___
*[saltapi/service/instrument_service.py, line 16 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6Qy5W3zecG5kxr-2i:-Mw6Qy5W3zecG5kxr-2j:b-26lote) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/service/instrument_service.py#L16)):*
> ```Python
>     def get_mos_data(self, semesters: List[str]) -> List[Dict[str, Any]]:
>         """
>         Return MOS data
> ```

data > data.

Why do you this method get_mos_data rather than get_mos_blocks?
___
*[saltapi/web/services.py, line 68 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6RUNp-IMzuvXfw4Gw:-Mw6RUNp-IMzuvXfw4Gx:b1xbhfw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/web/services.py#L68)):*
> ```Python
> 
> 
> def mos_service(connection: Connection) -> InstrumentService:
> ```

Why do you still have this function?
___
*[saltapi/web/api/instruments.py, line 31 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6RiD53uB2faasITEy:-Mw6RiD53uB2faasITEz:bvcenw8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/web/api/instruments.py#L31)):*
> ```Python
> 
> @router.get(
>     "/mos",
> ```

I'd suggest `/rss/mos`.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/42)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/repository/instrument_repository.py, line 40 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw70IHw6kAuAM_5t3Rl:-Mw70IHw6kAuAM_5t3Rm:bybcs4b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0249e9fda1d45be3d02112431a1e4133b2fe10e3/saltapi/repository/instrument_repository.py#L40)):*
> ```Python
> 
>     def get_mos_blocks(self, semesters: List[str]) -> List[Dict[str, Any]]:
>         """The list of MOS block"""
> ```

Oops. I missed this: block > blocks.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/42)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/instrument_repository.py, line 39 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6Qcqp9LPMBgmQrftj:-Mw6vFQq42UtEtkuXRk9:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/repository/instrument_repository.py#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

get_mos_block > get_mod_blocks
</blockquote></details>

Done.
___
*[saltapi/repository/instrument_repository.py, line 40 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6Qjz7B8Y0CuuPeHpF:-Mw6vF-x3T_WMdjrs4O4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/repository/instrument_repository.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Mos > MOS
</blockquote></details>

Done.
___
*[saltapi/repository/instrument_repository.py, line 40 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw70IHw6kAuAM_5t3Rl:-Mw742O97t0fUVXLASxD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0249e9fda1d45be3d02112431a1e4133b2fe10e3/saltapi/repository/instrument_repository.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oops. I missed this: block > blocks.
</blockquote></details>

Done.
___
*[saltapi/repository/rss_repository.py, line 442 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6Qosv1ibggoUaxFGx:-Mw6vGuv6zcdH4HP5Mxp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/repository/rss_repository.py#L442)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

get_mos_block > get_mos_blocks
</blockquote></details>

Done.
___
*[saltapi/service/instrument_service.py, line 16 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6Qy5W3zecG5kxr-2i:-Mw6vgZe5tkRXcaW5e8Z:b-nfcaj9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/service/instrument_service.py#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

data > data.

Why do you this method get_mos_data rather than get_mos_blocks?
</blockquote></details>

My mistake fixed.
___
*[saltapi/web/services.py, line 68 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6RUNp-IMzuvXfw4Gw:-Mw6wqWK9OvmsEt21Oiv:ba3dfob) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/web/services.py#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you still have this function?
</blockquote></details>

Removed
___
*[saltapi/web/api/instruments.py, line 31 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw6RiD53uB2faasITEy:-Mw73zblE9CuSZP808Pn:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/35bcf34aa6fcd1ab7235cb46c30d21dd62190e6b/saltapi/web/api/instruments.py#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest `/rss/mos`.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/42)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[saltapi/repository/instrument_repository.py, line 40 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/42#-Mw70IHw6kAuAM_5t3Rl:-Mw7AmnPDJwJlT9SfhQy:b-vhr3ub) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0249e9fda1d45be3d02112431a1e4133b2fe10e3/saltapi/repository/instrument_repository.py#L40)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, but it's not done, it seems, I was referring to the docstring:

"""The list of MOS block""" > """The list of MOS blocks."""

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
