### PR TITLE
Handle updating mos mask metadata

### LINKED ISSUE #44: Tests for MOS functionality
There should be tests for the MOS functionality.

### LINKED ISSUE #54: Handling of updating MOS mask metadata
I would suggest the following changes:

* MOS mask metadata should be updated with a PATCH rather than PUT request

* The `update_mos_mask_metadata` method in `rss_repository.py` should not return anything.

* The `update_mos_mask_matadata` function in `instruments.py` should return the full MOS mask metadata (i.e. a GET and PUT/PATCH request should return the same content).

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/236)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/236)* status: all files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/web/api/instruments.py` line 73 at r1](https://reviewable.io/reviews/saltastroops/salt-api/236#-NYXEhA_3wYT1jc0jt-U:-NYXEhA_3wYT1jc0jt-V:b-mwolhy) ([raw file](https://github.com/saltastroops/salt-api/blob/bb3967fd6d0a4d0b6e099b69a6a42e1ea6331f56/saltapi/web/api/instruments.py#L73)):*
> ```Python
>     """
>     with UnitOfWork() as unit_of_work:
>         if semester_start(from_semester) > semester_start(to_semester):
> ```

I don't think you need the semester_start call; ordinary string comparison should do the job in this case. (And if it doesn't, you should probable implement `_lt__` and `__gt__` for the `Semester` class.)
___
*[`saltapi/web/api/instruments.py` line 115 at r1](https://reviewable.io/reviews/saltastroops/salt-api/236#-NYXHKLc6K3tARrDvxfG:-NYXHKLc6K3tARrDvxfH:bjvi1gm) ([raw file](https://github.com/saltastroops/salt-api/blob/bb3967fd6d0a4d0b6e099b69a6a42e1ea6331f56/saltapi/web/api/instruments.py#L115)):*
> ```Python
>         unit_of_work.connection.commit()
> 
>         mos_block = instrument_service.get_mos_mask_metadata(barcode)
> ```

This is not a block.
___
*[`tests/integration/instruments/test_get_rss_mos_masks_metadata.py` line 117 at r1](https://reviewable.io/reviews/saltastroops/salt-api/236#-NYXIA0q1A8sDDGmYVAe:-NYXIA0q1A8sDDGmYVAf:btnev6k) ([raw file](https://github.com/saltastroops/salt-api/blob/bb3967fd6d0a4d0b6e099b69a6a42e1ea6331f56/tests/integration/instruments/test_get_rss_mos_masks_metadata.py#L117)):*
> ```Python
>     assert len(mos_masks_metadata) == mos_masks_count
> 
>     for mos in mos_masks_metadata:
> ```

Might it make sense to use `purest-regressions`?
___
*[`tests/integration/instruments/test_patch_rss_mos_mask_metadata.py` line 60 at r1](https://reviewable.io/reviews/saltastroops/salt-api/236#-NYXUN_Y3xNDdwBn5g5i:-NYXUN_Y3xNDdwBn5g5j:b-pbqbi3) ([raw file](https://github.com/saltastroops/salt-api/blob/bb3967fd6d0a4d0b6e099b69a6a42e1ea6331f56/tests/integration/instruments/test_patch_rss_mos_mask_metadata.py#L60)):*
> ```Python
> 
> 
> def test_mos_mask_update(
> ```

Shouldn't you also check (in a separate test) that you can update the cut date and the mask comment?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/236)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/api/instruments.py` line 73 at r1](https://reviewable.io/reviews/saltastroops/salt-api/236#-NYXEhA_3wYT1jc0jt-U:-NYqf9JS7uSX78lzj6rY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bb3967fd6d0a4d0b6e099b69a6a42e1ea6331f56/saltapi/web/api/instruments.py#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need the semester_start call; ordinary string comparison should do the job in this case. (And if it doesn't, you should probable implement `_lt__` and `__gt__` for the `Semester` class.)
</blockquote></details>

Done.
___
*[`saltapi/web/api/instruments.py` line 115 at r1](https://reviewable.io/reviews/saltastroops/salt-api/236#-NYXHKLc6K3tARrDvxfG:-NYqf8Sz1X8rEDyhCI29:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bb3967fd6d0a4d0b6e099b69a6a42e1ea6331f56/saltapi/web/api/instruments.py#L115)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is not a block.
</blockquote></details>

Done.
___
*[`tests/integration/instruments/test_get_rss_mos_masks_metadata.py` line 117 at r1](https://reviewable.io/reviews/saltastroops/salt-api/236#-NYXIA0q1A8sDDGmYVAe:-NYqhFCk-quyYm_Ej4n7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bb3967fd6d0a4d0b6e099b69a6a42e1ea6331f56/tests/integration/instruments/test_get_rss_mos_masks_metadata.py#L117)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might it make sense to use `purest-regressions`?
</blockquote></details>

Done.
___
*[`tests/integration/instruments/test_patch_rss_mos_mask_metadata.py` line 60 at r1](https://reviewable.io/reviews/saltastroops/salt-api/236#-NYXUN_Y3xNDdwBn5g5i:-NYqz8RO7WzOZkqCiiSX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bb3967fd6d0a4d0b6e099b69a6a42e1ea6331f56/tests/integration/instruments/test_patch_rss_mos_mask_metadata.py#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't you also check (in a separate test) that you can update the cut date and the mask comment?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/236)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`tests/integration/instruments/test_patch_rss_mos_mask_metadata.py` line 88 at r2](https://reviewable.io/reviews/saltastroops/salt-api/236#-NZUyjduCKRPO5gnjLRP:-NZUyjdv72n_ZcfgDvog:bb42d50) ([raw file](https://github.com/saltastroops/salt-api/blob/92616b06b8eccbd0899b63b2ec85a720e9afb9f8/tests/integration/instruments/test_patch_rss_mos_mask_metadata.py#L88)):*
> ```Python
>     barcode = "P000127N01"
>     cut_by = "Chaka"
>     cut_date = date.today().isoformat()
> ```

I would not use `date.today()` as it makes the test non-deterministic.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/236)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/integration/instruments/test_patch_rss_mos_mask_metadata.py` line 88 at r2](https://reviewable.io/reviews/saltastroops/salt-api/236#-NZUyjduCKRPO5gnjLRP:-NZV4bvnB4pqUGutjXUS:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/92616b06b8eccbd0899b63b2ec85a720e9afb9f8/tests/integration/instruments/test_patch_rss_mos_mask_metadata.py#L88)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would not use `date.today()` as it makes the test non-deterministic.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/236)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
