### PR TITLE
block-visit-status-update-issue

### LINKED ISSUE #34: Block visit status update must also update rejection reason
The (repository) function for updating the block visit status currently does not update the rejection reason.

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Block visit status update also updates the rejection reason

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/75)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 6 of 85 files at r1, 80 of 80 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/75)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/web/api/block_visits.py` line 44 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N54aDa9CnZGQZN8Py1u:-N54aDa9CnZGQZN8Py1v:bp9cmk) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/305e958e43933dded89b14614c897d7b16f9bb3f/saltapi/web/api/block_visits.py#L44)):*
> ```Python
> 
> 
> @router.patch("/{block_visit_id}/status", summary="Update the status of a block visit")
> ```

I'm just curious: Given you removed the methods for getting a block visit status, shouldn't updating the block visit status be handled by a block update function?
___
*[`saltapi/web/api/block_visits.py` line 58 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N54_f_aEDKEGwk2cL3V:-N54_f_aEDKEGwk2cL3W:b-uadpjo) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/305e958e43933dded89b14614c897d7b16f9bb3f/saltapi/web/api/block_visits.py#L58)):*
> ```Python
>         None,
>         alias="reason",
>         title="Block visit rejection  reason",
> ```

One blank too many between "rejection" and "reason"
___
*[`tests/service/test_block_service.py` line 159 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N54clyMDfdB3WwspQER:-N54clyMDfdB3WwspQES:b-xuhvus) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/305e958e43933dded89b14614c897d7b16f9bb3f/tests/service/test_block_service.py#L159)):*
> ```Python
> 
>     block_visit = block_service.get_block_visit(BLOCK_VISIT_ID)
>     assert block_visit["status"] != "Not set"
> ```

But isn't "not set" an invalid block visit status value?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/75)* status: 85 of 86 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/api/block_visits.py` line 44 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N54aDa9CnZGQZN8Py1u:-N5G_gav-_fjwxv-XSd2:bxqkv51) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/305e958e43933dded89b14614c897d7b16f9bb3f/saltapi/web/api/block_visits.py#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm just curious: Given you removed the methods for getting a block visit status, shouldn't updating the block visit status be handled by a block update function?
</blockquote></details>

I am not sure, I was just following you comment. I mean it does make sense to remove the get method for getting a block visit status because it wasn't returning the block rejection status reason. And so that possibly meant also having a separate method for getting/updating block rejection status reason. Will it make any difference updating the block visit status by a block update function?
___
*[`saltapi/web/api/block_visits.py` line 58 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N54_f_aEDKEGwk2cL3V:-N5Gb6J-Dg4LCyESafAp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/305e958e43933dded89b14614c897d7b16f9bb3f/saltapi/web/api/block_visits.py#L58)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

One blank too many between "rejection" and "reason"
</blockquote></details>

Done.
___
*[`tests/service/test_block_service.py` line 159 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N54clyMDfdB3WwspQER:-N5GbENsCXoL3eu4K07L:bjyw3n7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/305e958e43933dded89b14614c897d7b16f9bb3f/tests/service/test_block_service.py#L159)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But isn't "not set" an invalid block visit status value?
</blockquote></details>

I don't know, last time I checked the only invalid block visit status value we defined was 'deleted'. Should 'not set' be regarded as invalid as well?

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/75)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`tests/service/test_block_service.py` line 159 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N54clyMDfdB3WwspQER:-N5K69Re5pXgLwE76f1L:b-49n5fo) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/305e958e43933dded89b14614c897d7b16f9bb3f/tests/service/test_block_service.py#L159)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I don't know, last time I checked the only invalid block visit status value we defined was 'deleted'. Should 'not set' be regarded as invalid as well?
</blockquote></details>

Ah, I see... You are actually testing that you cannot update with a wrong block visit type. But the test function's name doesn't reflect this, and it would also make sense to check the HTTP status code.

Which also means that you are testing nowhere what this test claims to test: that you can set/update a block visit status.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/75)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/service/test_block_service.py` line 159 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N54clyMDfdB3WwspQER:-N67yg5G4jnIX6D7QOr8:bsci0e7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/305e958e43933dded89b14614c897d7b16f9bb3f/tests/service/test_block_service.py#L159)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, I see... You are actually testing that you cannot update with a wrong block visit type. But the test function's name doesn't reflect this, and it would also make sense to check the HTTP status code.

Which also means that you are testing nowhere what this test claims to test: that you can set/update a block visit status.
</blockquote></details>

This is a service test right and I might be wrong but we are not doing any HTTP requests here and so I can't check the HTTP status code in this test.

I have changed the test case to test that you cannot update with a wrong block visit type. And I think a test for setting/updating a block visit status is already in place (the test above this one)

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/75)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`saltapi/service/block.py` line 13 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68XHso-evZRQudXZvB:-N68XHsp7s7PZ7EIKjPX:bdansor) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/saltapi/service/block.py#L13)):*
> ```Python
> 
> class BlockVisitStatus(BaseModel):
>     status: str
> ```

Is this a str or an enum?

I'm not convinced there should be a Pydantic model at this level. Also the class is inconsistent with a different BlockVisitStatus defined at the API level.
___
*[`saltapi/service/block_service.py` line 43 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68_PNq1vCV7tLXZxLh:-N68_PNq1vCV7tLXZxLi:b-uwx5mn) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/saltapi/service/block_service.py#L43)):*
> ```Python
>         self,
>         block_visit_id: int,
>         status: BlockVisitStatus,
> ```

I don't this this is the right type here? Probably should be str?
___
*[`saltapi/service/block_service.py` line 44 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68_d2B0hOhhYKTkQfc:-N68_d2B0hOhhYKTkQfd:b-fsuc4d) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/saltapi/service/block_service.py#L44)):*
> ```Python
>         block_visit_id: int,
>         status: BlockVisitStatus,
>         reason: Optional[BlockRejectionReason],
> ```

This might rather have to be str, so as not to let the web layer leak into the repository layer.
___
*[`tests/service/test_block_service.py` line 155 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68Xwrf9tf5s58H1JVp:-N68Xwrf9tf5s58H1JVq:bmem4xb) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/tests/service/test_block_service.py#L155)):*
> ```Python
> 
>     block_visit = block_service.get_block_visit(BLOCK_VISIT_ID)
>     assert block_visit["status"] != "Not set"
> ```

Is this line needed?
___
*[`tests/service/test_block_service.py` line 157 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68Y1Lz5-fZoCftXuXq:-N68Y1M-8NyRsdAgSz2_:b-m3cwgw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/tests/service/test_block_service.py#L157)):*
> ```Python
>     assert block_visit["status"] != "Not set"
> 
>     with pytest.raises(AttributeError):
> ```

This looks a bit odd... Would you really expect an AttributeError? Shouldn't you rather get a ValueError here, with a meaningful error message?
___
*[`tests/service/test_block_service.py` line 163 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68YYIT5n-gqs-WRtv7:-N68YYIT5n-gqs-WRtv8:b-88g54u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/tests/service/test_block_service.py#L163)):*
> ```Python
> def test_update_block_visit_status_raises_error_for_wrong_block_id() -> None:
>     block_service = create_block_service()
>     status = BlockVisitStatus("In queue")
> ```

Shouldn't BlockVisitStatus have two arguments?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/75)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/block.py` line 13 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68XHso-evZRQudXZvB:-N6E0OJ180yLgDgE04JY:bj2wykl) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/saltapi/service/block.py#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this a str or an enum?

I'm not convinced there should be a Pydantic model at this level. Also the class is inconsistent with a different BlockVisitStatus defined at the API level.
</blockquote></details>

I think we've had this discussion before and we agreed that there should be no Pedantic model at API level, I got confused a bit but I have fixed it now. The status property should be a string and it should also be fixed now.
___
*[`saltapi/service/block_service.py` line 43 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68_PNq1vCV7tLXZxLh:-N6E1F_N4p2SP7xvTrXK:b-heud42) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/saltapi/service/block_service.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't this this is the right type here? Probably should be str?
</blockquote></details>

It should be a string.
___
*[`saltapi/service/block_service.py` line 44 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68_d2B0hOhhYKTkQfc:-N6E1KGiClOHzBHvxm6w:b-lc08c3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/saltapi/service/block_service.py#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This might rather have to be str, so as not to let the web layer leak into the repository layer.
</blockquote></details>

Yep, we did discuss this before I just got confused a bit.
___
*[`tests/service/test_block_service.py` line 155 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68Xwrf9tf5s58H1JVp:-N6E1SGQ5QlQIut5Ueij:b-h335yi) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/tests/service/test_block_service.py#L155)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this line needed?
</blockquote></details>

No, it is not.
___
*[`tests/service/test_block_service.py` line 157 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68Y1Lz5-fZoCftXuXq:-N6E1Va469w4ILmarbUH:boi83sq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/tests/service/test_block_service.py#L157)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This looks a bit odd... Would you really expect an AttributeError? Shouldn't you rather get a ValueError here, with a meaningful error message?
</blockquote></details>

Yes it should be a ValueError and I have updated it accordingly.
___
*[`tests/service/test_block_service.py` line 163 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N68YYIT5n-gqs-WRtv7:-N6E1bE651Qv-gWeRpTj:b-3dhg9v) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/87850f5d699962b96300c634f9cf3f6c191eed38/tests/service/test_block_service.py#L163)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't BlockVisitStatus have two arguments?
</blockquote></details>

That's true, and for consistency, I have renamed this property to BlockVisitStatus value. And I didn't add a schema for BlockVisitStatus because it is not be used anywhere since we agreed to get rid of the get_block_visit_status method

**Review by hettlage — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

___
*[`tests/service/test_block_service.py` line 159 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/75#-N54clyMDfdB3WwspQER:-N6OjmTe0kTqo7AH5w2J:bm46mia) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/305e958e43933dded89b14614c897d7b16f9bb3f/tests/service/test_block_service.py#L159)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

This is a service test right and I might be wrong but we are not doing any HTTP requests here and so I can't check the HTTP status code in this test.

I have changed the test case to test that you cannot update with a wrong block visit type. And I think a test for setting/updating a block visit status is already in place (the test above this one)

</blockquote></details>

Good point about the HTTP status,... :-)

**Pull request merged**
