### PR TITLE
Proposal Status

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/310)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/310)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1351 at r1](https://reviewable.io/reviews/saltastroops/salt-api/310#-O0moyVp8S5v4R_ZhOFU:-O0moyVp8S5v4R_ZhOFV:byxzzvc) ([raw file](https://github.com/saltastroops/salt-api/blob/17d1bd3ad6b1e1bcf2776698141048ba15ee9494/saltapi/repository/proposal_repository.py#L1351)):*
> ```Python
>             raise NotFoundError()
> 
>     def _validate_status_update(self, proposal_code: str, status: str) -> None:
> ```

Tests are missing.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/310)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1351 at r1](https://reviewable.io/reviews/saltastroops/salt-api/310#-O0moyVp8S5v4R_ZhOFU:-O0xOZo7BtvdsCGwcjYQ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/17d1bd3ad6b1e1bcf2776698141048ba15ee9494/saltapi/repository/proposal_repository.py#L1351)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Tests are missing.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/310)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1355 at r2](https://reviewable.io/reviews/saltastroops/salt-api/310#-O1GAoc33oechBsMoEDJ:-O1GAoc33oechBsMoEDK:b-ks2fo3) ([raw file](https://github.com/saltastroops/salt-api/blob/25d3d8ad76a94b0ce76b1bb229e028d7351c80ae/saltapi/repository/proposal_repository.py#L1355)):*
> ```Python
>         """Check if the proposal status can be updated."""
>         proposal = self.get(proposal_code)
>         pprint(proposal)
> ```

Unnecessary print statement
___
*[`tests/repository/test_proposal_repository.py` line 430 at r2](https://reviewable.io/reviews/saltastroops/salt-api/310#-O1GAc5H1XGSf3Cg5UXz:-O1GAc5H1XGSf3Cg5UY-:b-hzlnix) ([raw file](https://github.com/saltastroops/salt-api/blob/25d3d8ad76a94b0ce76b1bb229e028d7351c80ae/tests/repository/test_proposal_repository.py#L430)):*
> ```Python
> )
> def test_update_proposal_status_raise_validation_error(proposal_code: str, status: str, db_connection: Connection) -> None:
>     # Set the status to "Active"
> ```

This comment is misleading.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/310)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1355 at r2](https://reviewable.io/reviews/saltastroops/salt-api/310#-O1GAoc33oechBsMoEDJ:-O1GCtwC2VQrj85km-wp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/25d3d8ad76a94b0ce76b1bb229e028d7351c80ae/saltapi/repository/proposal_repository.py#L1355)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary print statement
</blockquote></details>

Done.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/310)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`tests/repository/test_proposal_repository.py` line 430 at r2](https://reviewable.io/reviews/saltastroops/salt-api/310#-O1GAc5H1XGSf3Cg5UXz:-O1GDz5JEsZ_pSNvlMg8:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/25d3d8ad76a94b0ce76b1bb229e028d7351c80ae/tests/repository/test_proposal_repository.py#L430)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This comment is misleading.
</blockquote></details>

removed

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/310)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
