### PR TITLE
Fixing Dockerfile Again

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/106)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/106)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`Dockerfile` line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api/106#-NFLLBpa2jas_lFzShaN:-NFLLBpa2jas_lFzShaO:ba5ix0j) ([raw file](https://github.com/saltastroops/salt-api/blob/1edf90538f282b739745869fc03fad2a4f2ad69c/Dockerfile#L7)):*
> ```Dockerfile
> # Based on https://fastapi.tiangolo.com/deployment/docker/
> 
> FROM python:3.10 as requirements-stage
> ```

The "as requirements-stage" should be removed.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/106)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`Dockerfile` line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api/106#-NFLLBpa2jas_lFzShaN:-NGQzvaS-Cl-ZCFBWN5B:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1edf90538f282b739745869fc03fad2a4f2ad69c/Dockerfile#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The "as requirements-stage" should be removed. 
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/106)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`Dockerfile` line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api/106#-NFLLBpa2jas_lFzShaN:-NGWq_Q77Zkb8of1eps-:b8velxb) ([raw file](https://github.com/saltastroops/salt-api/blob/1edf90538f282b739745869fc03fad2a4f2ad69c/Dockerfile#L7)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yioub changed the Python version, but did not remove the `as requirements-stage`...

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/106)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`Dockerfile` line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api/106#-NFLLBpa2jas_lFzShaN:-NG_ZoUzEXinsLuMPuzw:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1edf90538f282b739745869fc03fad2a4f2ad69c/Dockerfile#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yioub changed the Python version, but did not remove the `as requirements-stage`...
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
