### PR TITLE
added nights remaining.

### PR DESCRIPTION
**Pull request by Eb-Zeero**
added other barcode.

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/58)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/58)* status: all files reviewed, 13 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/repository/rss_repository.py, line 444 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-ScZDLDkDE2KYIZ6Fl:-N-ScZDLDkDE2KYIZ6Fm:bdw265b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L444)):*
> ```Python
>         return liaison_astronomers
> 
>     def _get_barcodes(self, encoded_contents: Set[str]):
> ```

The method name might be a bit generic. (Maybe better `_get_barcodes_for_encoded_content`?)
___
*[saltapi/repository/rss_repository.py, line 446 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-ScrJz3N5oBbOt64nc:-N-ScrJz3N5oBbOt64nd:b-xf5k7l) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L446)):*
> ```Python
>     def _get_barcodes(self, encoded_contents: Set[str]):
>         """
>         Get other barcodes with the same encoded content.
> ```

"other" is not correct; you return all the barcodes for some encoded content.
___
*[saltapi/repository/rss_repository.py, line 458 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-ScQD_4X5kJRLyMAE4:-N-ScQD_4X5kJRLyMAE5:b-nuoign) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L458)):*
> ```Python
>             """
>         )
>         ec = dict()
> ```

Can't you use a defaultdict?
___
*[saltapi/repository/rss_repository.py, line 475 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SgvbY7Zxm-8juz6jI:-N-SgvbaCUSNGBUAtlDN:b-714lwx) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L475)):*
> ```Python
>          ON BVW.BlockVisibilityWindowType_Id = BVWT.BlockVisibilityWindowType_Id
>          JOIN Block B ON BVW.Block_Id = B.Block_Id
>          JOIN Proposal P ON B.Proposal_Id = P.Proposal_Id
> ```

Why are you joining the Proposal table?

The WHERE condition for the block visibility type is missing: `AND BVWT.BlockVisibilityWindowType='Strict'`
___
*[saltapi/repository/rss_repository.py, line 482 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SiJbo6KRvefsZ3aXN:-N-SiJbo6KRvefsZ3aXO:bkmpn1m) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L482)):*
> ```Python
>         )
>         start = datetime.now()
>         end = semester_end(semester_of_datetime(start.astimezone()))
> ```

I think this isn't correct. The end time should be the end of the semester to which the block belongs. (And then you might have too catch the case that the end date is before the start date -- I'm not sure what MySQL does in that case.)
___
*[saltapi/repository/rss_repository.py, line 549 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SvmoH5Uh1Hy40J_lv:-N-SvmoI9TsxqwZj-nrF:bupwh6h) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L549)):*
> ```Python
>         encoded_contents = []
>         for row in results:
>             mos_blocks.append(dict(row, **{"other_barcodes": []}))
> ```

I was surprised this is working, but yes, the documentation allows. I've learned something! :-)
___
*[saltapi/repository/rss_repository.py, line 553 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SoqaRAnt58JR4ULij:-N-SoqaRAnt58JR4ULik:b-ks2fo3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L553)):*
> ```Python
> 
>             encoded_contents.append(row.encoded_content)
>         print(sorted(block_ids))
> ```

Unnecessary print statement
___
*[saltapi/repository/rss_repository.py, line 560 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SoulsBj98i7lAp0i0:-N-SoulsBj98i7lAp0i1:b-ks2fo3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L560)):*
> ```Python
>         barcodes = self._get_barcodes(set(encoded_contents))
>         remaining_nights = self._get_blocks_remaining_nights(set(block_ids))
>         print(remaining_nights)
> ```

Unnecessary print statement
___
*[saltapi/repository/rss_repository.py, line 568 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SuGWQ0IKFavvriTO1:-N-SuGWS6hr-FtwZqFzD:b-3pwyb9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L568)):*
> ```Python
>                 else None
>             )
>             m["other_barcodes"] = copy(barcodes[m["encoded_content"]])
> ```

Perhaps more clearly (?):

`m["other_barcodes"] = [b for b in barcodes[m["encoded_content"]] if b != m["barcode"]]
___
*[saltapi/repository/rss_repository.py, line 570 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SubYb3A2RZbeV3b2Q:-N-SubYc3QHMiKOMiq0n:b-otilcs) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L570)):*
> ```Python
>             m["other_barcodes"] = copy(barcodes[m["encoded_content"]])
>             m["remaining_nights"] = remaining_nights[m["block_id"]] if m["block_id"] in remaining_nights else 0
>             m["other_barcodes"].remove(m['barcode'])
> ```

See comment above.
___
*[saltapi/web/schema/rss.py, line 431 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SwE5Z9ydJSTR7kOCX:-N-SwE5Z9ydJSTR7kOCY:bzcbdtp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/web/schema/rss.py#L431)):*
> ```Python
>         ..., title="Liaison astronomer", description="The liaison astronomer"
>     )
>     other_barcodes: Optional[List[str]] = Field(
> ```

Should this really be optional? If there are no other barcodes, an empty list would make sense.
___
*[saltapi/web/schema/rss.py, line 432 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SxHaU-eiNmvilO4Cm:-N-SxHaU-eiNmvilO4Cn:b-xp39d8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/web/schema/rss.py#L432)):*
> ```Python
>     )
>     other_barcodes: Optional[List[str]] = Field(
>         ..., title="Other barcode", description="The other masks with the same cut."
> ```

barcode > barcodes

The other masks with the same cut. > The masks which are identical to this one
___
*[saltapi/web/schema/rss.py, line 437 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-Sx9869UMTzPbUxy8A:-N-Sx9869UMTzPbUxy8B:behsud) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/web/schema/rss.py#L437)):*
> ```Python
>         ...,
>         title="Remaining nights",
>         description="The number of night of which the block is visible"
> ```

The number of nights in which the block is still visible

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/58)* status: 0 of 5 files reviewed, 13 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/rss_repository.py, line 444 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-ScZDLDkDE2KYIZ6Fl:-N00NSCd3_8NY63BJnZm:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L444)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The method name might be a bit generic. (Maybe better `_get_barcodes_for_encoded_content`?)
</blockquote></details>

Done.
___
*[saltapi/repository/rss_repository.py, line 446 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-ScrJz3N5oBbOt64nc:-N00Ndbp3G6GPcUy0nVO:bt2vr1b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L446)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"other" is not correct; you return all the barcodes for some encoded content.
</blockquote></details>

Fixed.
___
*[saltapi/repository/rss_repository.py, line 458 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-ScQD_4X5kJRLyMAE4:-N00NgH13-2GOK1bm5Ui:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L458)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can't you use a defaultdict?
</blockquote></details>

Done.
___
*[saltapi/repository/rss_repository.py, line 475 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SgvbY7Zxm-8juz6jI:-N00NhLJBGIB4CcFRQzp:bpm6xhp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L475)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why are you joining the Proposal table?

The WHERE condition for the block visibility type is missing: `AND BVWT.BlockVisibilityWindowType='Strict'`
</blockquote></details>

whas quering proposal codes before slept thougt.
Removed
___
*[saltapi/repository/rss_repository.py, line 482 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SiJbo6KRvefsZ3aXN:-N0520Cs0utMtwcAtIx3:b4ofyn) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L482)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this isn't correct. The end time should be the end of the semester to which the block belongs. (And then you might have too catch the case that the end date is before the start date -- I'm not sure what MySQL does in that case.)
</blockquote></details>


Fixed
___
*[saltapi/repository/rss_repository.py, line 549 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SvmoH5Uh1Hy40J_lv:-N00rCulDGtbgCoGjRAJ:bvs55d0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L549)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I was surprised this is working, but yes, the documentation allows. I've learned something! :-)
</blockquote></details>

Thank you
___
*[saltapi/repository/rss_repository.py, line 553 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SoqaRAnt58JR4ULij:-N00rGGJ6SfOAVzMhWjY:ba3dfob) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L553)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary print statement
</blockquote></details>

Removed
___
*[saltapi/repository/rss_repository.py, line 560 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SoulsBj98i7lAp0i0:-N00rIPe-VW_hhRQm8V3:ba3dfob) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L560)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary print statement
</blockquote></details>

Removed
___
*[saltapi/repository/rss_repository.py, line 568 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SuGWQ0IKFavvriTO1:-N00rJxi8Ttc_g-37hrS:bt2vr1b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L568)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Perhaps more clearly (?):

`m["other_barcodes"] = [b for b in barcodes[m["encoded_content"]] if b != m["barcode"]]
</blockquote></details>

Fixed.
___
*[saltapi/repository/rss_repository.py, line 570 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SubYb3A2RZbeV3b2Q:-N00rMgn-17_kWwbgE2x:b-op1ek4) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L570)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment above.
</blockquote></details>

removed fixed above
___
*[saltapi/web/schema/rss.py, line 431 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SwE5Z9ydJSTR7kOCX:-N01-CwlAxXFAbD8nzqb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/web/schema/rss.py#L431)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should this really be optional? If there are no other barcodes, an empty list would make sense.
</blockquote></details>

Done.
___
*[saltapi/web/schema/rss.py, line 432 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SxHaU-eiNmvilO4Cm:-N01-E0W8-G3ZLpRiEeI:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/web/schema/rss.py#L432)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

barcode > barcodes

The other masks with the same cut. > The masks which are identical to this one
</blockquote></details>

Done.
___
*[saltapi/web/schema/rss.py, line 437 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-Sx9869UMTzPbUxy8A:-N01-EON2_wEBawzKxEQ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/web/schema/rss.py#L437)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The number of nights in which the block is still visible
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/58)* status: all files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/repository/rss_repository.py, line 444 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-ScZDLDkDE2KYIZ6Fl:-N05k6rGBSb23W7Oweo_:bhl0w1x) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L444)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, but I was wrong about the method name; it should be _get_barcodes_for_encoded_contents.
___
*[saltapi/repository/rss_repository.py, line 482 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SiJbo6KRvefsZ3aXN:-N05lsmF4M88PgJPIiJP:b-hazxlk) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L482)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

The problem remains... :( If the proposal is for a past semester, the end of that semester is relevant, not that of the current semester.
___
*[saltapi/repository/rss_repository.py, line 447 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N05kKn15GH-S3dOvVav:-N05kKn15GH-S3dOvVaw:b-temhod) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/bc8b3ed025d6523cf4adab17365e818990079d60/saltapi/repository/rss_repository.py#L447)):*
> ```Python
>     def _get_barcodes_for_encoded_content(self, encoded_contents: Set[str]):
>         """
>         Get barcodes with the same encoded content.
> ```

"""
Get the barcodes for a set of encoded mask contents.

A dictionary of encoded contents and corresponding lists of barcodes is returned. If a list of barcodes has more than one item, this means that some masks have the same layout (slits, reference stars) but different barcodes.
"""
___
*[saltapi/repository/rss_repository.py, line 482 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N05mVZF5Z72dRYaNDiV:-N05mVZF5Z72dRYaNDiW:b831fxw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/bc8b3ed025d6523cf4adab17365e818990079d60/saltapi/repository/rss_repository.py#L482)):*
> ```Python
>         start = datetime.now()
>         end = semester_end(semester_of_datetime(start.astimezone())) \
>               + timedelta(hours=12)
> ```

I don't think 12 hours should be added.



_Code quote:_
```Python
d
```

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/58)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/rss_repository.py, line 444 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-ScZDLDkDE2KYIZ6Fl:-N05yxoIEAjBtTYetff0:br1hw53) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L444)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, but I was wrong about the method name; it should be _get_barcodes_for_encoded_contents.
</blockquote></details>

I noticed I thing the conflicts distructed me on the second try
___
*[saltapi/repository/rss_repository.py, line 482 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N-SiJbo6KRvefsZ3aXN:-N06-O0K3tTB2OHxJvM-:b-ncz55b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7ac8ca5c267fc42b1e691a9f1e692aaeecdbf5dd/saltapi/repository/rss_repository.py#L482)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The problem remains... :( If the proposal is for a past semester, the end of that semester is relevant, not that of the current semester.
</blockquote></details>

Can you please explain what is happening.
___
*[saltapi/repository/rss_repository.py, line 447 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N05kKn15GH-S3dOvVav:-N05zEEm1TfaOCrIuAFb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/bc8b3ed025d6523cf4adab17365e818990079d60/saltapi/repository/rss_repository.py#L447)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"""
Get the barcodes for a set of encoded mask contents.

A dictionary of encoded contents and corresponding lists of barcodes is returned. If a list of barcodes has more than one item, this means that some masks have the same layout (slits, reference stars) but different barcodes.
"""
</blockquote></details>

Done.
___
*[saltapi/repository/rss_repository.py, line 482 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/58#-N05mVZF5Z72dRYaNDiV:-N05zSprB_B3trKbboLF:b4cpr5x) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/bc8b3ed025d6523cf4adab17365e818990079d60/saltapi/repository/rss_repository.py#L482)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think 12 hours should be added.
</blockquote></details>

Can you please explain what exatly is going on here::)?

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
