### PR TITLE
Split target type

### LINKED ISSUE #129: Split target type
The target type should be split into type and subtype.

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/200)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/200)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/util.py` line 230 at r1](https://reviewable.io/reviews/saltastroops/salt-api/200#-NQUrXED9F4sqq2YUM0X:-NQUrXED9F4sqq2YUM0Y:b2z9sk6) ([raw file](https://github.com/saltastroops/salt-api/blob/bee4640192dae3535a6a4515cb773f37b24366ef/saltapi/util.py#L230)):*
> ```Python
> 
>     if row.target_type != "Unknown":
>         return {"type": row.target_type, "sub_type": row.target_sub_type}
> ```

sub_type > subtype
___
*[`saltapi/util.py` line 232 at r1](https://reviewable.io/reviews/saltastroops/salt-api/200#-NQUrZre07nHTjZHtOHv:-NQUrZre07nHTjZHtOHw:b2z9sk6) ([raw file](https://github.com/saltastroops/salt-api/blob/bee4640192dae3535a6a4515cb773f37b24366ef/saltapi/util.py#L232)):*
> ```Python
>         return {"type": row.target_type, "sub_type": row.target_sub_type}
>     else:
>         return {"type": "Unknown", "sub_type": "Unknown"}
> ```

sub_type > subtype
___
*[`saltapi/web/schema/target.py` line 85 at r1](https://reviewable.io/reviews/saltastroops/salt-api/200#-NQUqZgRBGq4EwNQG18u:-NQUqZgRBGq4EwNQG18v:bxwqzo2) ([raw file](https://github.com/saltastroops/salt-api/blob/bee4640192dae3535a6a4515cb773f37b24366ef/saltapi/web/schema/target.py#L85)):*
> ```Python
> 
> 
> class TargetType(BaseModel):
> ```

I'd suggest the following:

```
class TargetType(BaseModel):
    """A target type and subtype, based on the SIMBAD classification."""

    type: str = Field(
        ...,
        title="Target type",
        description="Target type.",
    )
    subtype: str = Field(
        ..., title="Target sub type", description="The target sub type."
    )
```

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/200)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/util.py` line 230 at r1](https://reviewable.io/reviews/saltastroops/salt-api/200#-NQUrXED9F4sqq2YUM0X:-NQWJrdw5RFDjbeFesD-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bee4640192dae3535a6a4515cb773f37b24366ef/saltapi/util.py#L230)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

sub_type > subtype
</blockquote></details>

Done.
___
*[`saltapi/util.py` line 232 at r1](https://reviewable.io/reviews/saltastroops/salt-api/200#-NQUrZre07nHTjZHtOHv:-NQWJrz43t6kiwQke4vU:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bee4640192dae3535a6a4515cb773f37b24366ef/saltapi/util.py#L232)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

sub_type > subtype
</blockquote></details>

Done.
___
*[`saltapi/web/schema/target.py` line 85 at r1](https://reviewable.io/reviews/saltastroops/salt-api/200#-NQUqZgRBGq4EwNQG18u:-NQWKI-zBdf-DVO_Gd3o:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bee4640192dae3535a6a4515cb773f37b24366ef/saltapi/web/schema/target.py#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest the following:

```
class TargetType(BaseModel):
    """A target type and subtype, based on the SIMBAD classification."""

    type: str = Field(
        ...,
        title="Target type",
        description="Target type.",
    )
    subtype: str = Field(
        ..., title="Target sub type", description="The target sub type."
    )
```
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/200)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/schema/target.py` line 94 at r2](https://reviewable.io/reviews/saltastroops/salt-api/200#-NQWiOmo8DQUUq6RX1Oi:-NQWiOmo8DQUUq6RX1Oj:b-fl1pd8) ([raw file](https://github.com/saltastroops/salt-api/blob/1430db34c713f60388ed1809db58cd1722bd8f7b/saltapi/web/schema/target.py#L94)):*
> ```Python
>     )
>     subtype: str = Field(
>         ..., title="Target sub type", description="The target sub type."
> ```

sub type > subtype

(Sorry!)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/200)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/schema/target.py` line 94 at r2](https://reviewable.io/reviews/saltastroops/salt-api/200#-NQWiOmo8DQUUq6RX1Oi:-NQZGwfJDUI6YV3S83Hl:b-jg6ewz) ([raw file](https://github.com/saltastroops/salt-api/blob/1430db34c713f60388ed1809db58cd1722bd8f7b/saltapi/web/schema/target.py#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

sub type > subtype

(Sorry!)
</blockquote></details>

nice catch

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
