### PR TITLE
Download proposal file

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/67)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/67)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1295 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/67#-N1rQE9g1fns5gGNcmSi:-N1rQE9lAQ5amqHQclkD:b33l3ee) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f8e61b7f71f33f25519b7cafaca8a376d5ee76ce/saltapi/repository/proposal_repository.py#L1295)):*
> ```Python
>     def get_current_version(self, proposal_code: str) -> int:
>         """
>         Return the current version (number) of sa proposal.
> ```

Return > Returns
___
*[`saltapi/service/proposal_service.py` line 41 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/67#-N1rQQXq5ixVePedSHXa:-N1rQQXq5ixVePedSHXb:b33l3ee) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f8e61b7f71f33f25519b7cafaca8a376d5ee76ce/saltapi/service/proposal_service.py#L41)):*
> ```Python
>     def get_proposal_zip(self, proposal_code: str) -> pathlib.Path:
>         """
>         Return the file path of proposal zip file.
> ```

Return > Returns
___
*[`saltapi/service/proposal_service.py` line 62 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/67#-N1rQSSl4kOZd258HFE_:-N1rQSSl4kOZd258HFEa:b33l3ee) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f8e61b7f71f33f25519b7cafaca8a376d5ee76ce/saltapi/service/proposal_service.py#L62)):*
> ```Python
>     def get_proposal(self, proposal_code: str) -> Proposal:
>         """
>         Return the JSON representation of a proposal.
> ```

Return > Returns

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/67)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 1295 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/67#-N1rQE9g1fns5gGNcmSi:-N1rnxpr0bDCdX1nyFxl:bk8hyo4) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f8e61b7f71f33f25519b7cafaca8a376d5ee76ce/saltapi/repository/proposal_repository.py#L1295)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Return > Returns
</blockquote></details>

No, actually the first line in a Python docstring is supposed to be in the imperatives form (cf. https://peps.python.org/pep-0257/).
___
*[`saltapi/service/proposal_service.py` line 41 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/67#-N1rQQXq5ixVePedSHXa:-N1roMJMBTzTT4XTowNe:b-q64pkt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f8e61b7f71f33f25519b7cafaca8a376d5ee76ce/saltapi/service/proposal_service.py#L41)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Return > Returns
</blockquote></details>

See above.
___
*[`saltapi/service/proposal_service.py` line 62 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/67#-N1rQSSl4kOZd258HFE_:-N1roOVuAgWf7Qpc8R2c:b-q64pkt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f8e61b7f71f33f25519b7cafaca8a376d5ee76ce/saltapi/service/proposal_service.py#L62)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Return > Returns
</blockquote></details>

See above.

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/67)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1295 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/67#-N1rQE9g1fns5gGNcmSi:-N1s3Ndq8Wj2WH19mMJ1:brh04e2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f8e61b7f71f33f25519b7cafaca8a376d5ee76ce/saltapi/repository/proposal_repository.py#L1295)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No, actually the first line in a Python docstring is supposed to be in the imperatives form (cf. https://peps.python.org/pep-0257/).
</blockquote></details>

Oh, I see. Thanks for sharing this.

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/67)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 1295 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/67#-N1rQE9g1fns5gGNcmSi:-N1tffd-8mEoNLhympa2:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f8e61b7f71f33f25519b7cafaca8a376d5ee76ce/saltapi/repository/proposal_repository.py#L1295)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Oh, I see. Thanks for sharing this.
</blockquote></details>

Done.

**Review by mofokeng-chaka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
