### PR TITLE
latest-block-submission-date

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Add latest block submission date to block

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/184)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/184)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/block_repository.py` line 130 at r1](https://reviewable.io/reviews/saltastroops/salt-api/184#-NOznff26IjzqjOojkKb:-NOzn1yc25-c8LukO6j7:byty6ad) ([raw file](https://github.com/saltastroops/salt-api/blob/97aba8731c409bd953c4d5a9d4791452bd4fa17e/saltapi/repository/block_repository.py#L130)):*
> ```Python
>             "block_visits": self._block_visits(block_id),
>             "observations": self._pointings(block_id),
>             "latest_submission_date": pytz.utc.localize(row.latest_submission_date),
> ```

Converting the submission into a `datetime` turns out to be problematic. It seems that the string representation of the `datetime` in the JSON reply has no timezone information and will thus be interpreted as a local time. So it might be safer to use an ISO 8601 string with timezone information ('Z', I'd guess, as it is UTC).
___
*[`saltapi/web/schema/block.py` line 170 at r1](https://reviewable.io/reviews/saltastroops/salt-api/184#-NOzkAfS-qHpMq8ePm6a:-NOzkAfS-qHpMq8ePm6b:b-gq2zem) ([raw file](https://github.com/saltastroops/salt-api/blob/97aba8731c409bd953c4d5a9d4791452bd4fa17e/saltapi/web/schema/block.py#L170)):*
> ```Python
>     latest_submission_date: datetime = Field(
>         ...,
>         title="Latest block submission date",
> ```

That technically is not accurate. It is the date of the latest submission with significant changes.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/184)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/block_repository.py` line 130 at r1](https://reviewable.io/reviews/saltastroops/salt-api/184#-NOznff26IjzqjOojkKb:-NP1Psug1FrCbiprOQWo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/97aba8731c409bd953c4d5a9d4791452bd4fa17e/saltapi/repository/block_repository.py#L130)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Converting the submission into a `datetime` turns out to be problematic. It seems that the string representation of the `datetime` in the JSON reply has no timezone information and will thus be interpreted as a local time. So it might be safer to use an ISO 8601 string with timezone information ('Z', I'd guess, as it is UTC).
</blockquote></details>

Done.
___
*[`saltapi/web/schema/block.py` line 170 at r1](https://reviewable.io/reviews/saltastroops/salt-api/184#-NOzkAfS-qHpMq8ePm6a:-NP1Pfci0PbW5q0tczMb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/97aba8731c409bd953c4d5a9d4791452bd4fa17e/saltapi/web/schema/block.py#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That technically is not accurate. It is the date of the latest submission with significant changes.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/184)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/block_repository.py` line 130 at r1](https://reviewable.io/reviews/saltastroops/salt-api/184#-NOznff26IjzqjOojkKb:-NP1qjkX2nb90JkB4jYb:bcin7hl) ([raw file](https://github.com/saltastroops/salt-api/blob/97aba8731c409bd953c4d5a9d4791452bd4fa17e/saltapi/repository/block_repository.py#L130)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You shouldn't believe everything I say... It seems all is working perfectly fine without converting the datetime to a string.
___
*[`saltapi/web/schema/block.py` line 168 at r1](https://reviewable.io/reviews/saltastroops/salt-api/184#-NP1rEnfDZXFzH3k8erk:-NP1rEnfDZXFzH3k8erl:b6raoqm) ([raw file](https://github.com/saltastroops/salt-api/blob/97aba8731c409bd953c4d5a9d4791452bd4fa17e/saltapi/web/schema/block.py#L168)):*
> ```Python
>         ),
>     )
>     latest_submission_date: datetime = Field(
> ```

Sorry I forgot 
___
*[`saltapi/web/schema/block.py` line 170 at r1](https://reviewable.io/reviews/saltastroops/salt-api/184#-NOzkAfS-qHpMq8ePm6a:-NP1rHSn1q1ANeQiZNt0:b-qv57m0) ([raw file](https://github.com/saltastroops/salt-api/blob/97aba8731c409bd953c4d5a9d4791452bd4fa17e/saltapi/web/schema/block.py#L170)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry for not raising it before, but you might consider moving the `latest_submission_date` property up in the schema. It might be a bit hidden at the bottom off the type...

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/184)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/block_repository.py` line 130 at r1](https://reviewable.io/reviews/saltastroops/salt-api/184#-NOznff26IjzqjOojkKb:-NP1viQC2wCiIZ5k7uI-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/97aba8731c409bd953c4d5a9d4791452bd4fa17e/saltapi/repository/block_repository.py#L130)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You shouldn't believe everything I say... It seems all is working perfectly fine without converting the datetime to a string.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/block.py` line 168 at r1](https://reviewable.io/reviews/saltastroops/salt-api/184#-NP1rEnfDZXFzH3k8erk:-NP1vkjT8mqujfe-KCwB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/97aba8731c409bd953c4d5a9d4791452bd4fa17e/saltapi/web/schema/block.py#L168)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry I forgot 
</blockquote></details>

Done.
___
*[`saltapi/web/schema/block.py` line 170 at r1](https://reviewable.io/reviews/saltastroops/salt-api/184#-NOzkAfS-qHpMq8ePm6a:-NP1vjCY9dADhkyiWtLF:bb6un1j) ([raw file](https://github.com/saltastroops/salt-api/blob/97aba8731c409bd953c4d5a9d4791452bd4fa17e/saltapi/web/schema/block.py#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry for not raising it before, but you might consider moving the `latest_submission_date` property up in the schema. It might be a bit hidden at the bottom off the type...
</blockquote></details>

Done

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
