### PR TITLE
corresponding updates to the frontend issue: type changes

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/36)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/36)* status: all files reviewed, 8 unresolved discussions (waiting on @mofokeng-chaka)

___
*[saltapi/repository/proposal_repository.py, line 64 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGVKtRBtYKT7Nl9nmv:-MpGVKtS7l7Hqr0qJco3:bckmhiv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/repository/proposal_repository.py#L64)):*
> ```Python
>          JOIN ProposalType T ON PGI.ProposalType_Id = T.ProposalType_Id
>          JOIN ProposalContact C ON PC.ProposalCode_Id = C.ProposalCode_Id
>          JOIN ProposalInactiveReason PIR 
> ```

Might this have to be a LEFT JOIN?
___
*[saltapi/repository/proposal_repository.py, line 457 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGVT7ECx99t5xUtjXq:-MpGVT7ECx99t5xUtjXr:bckmhiv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/repository/proposal_repository.py#L457)):*
> ```Python
>          JOIN ProposalStatus PS ON PGI.ProposalStatus_Id = PS.ProposalStatus_Id
>          JOIN ProposalContact C ON PC.ProposalCode_Id = C.ProposalCode_Id
>          JOIN ProposalInactiveReason PIR 
> ```

Might this have to be a LEFT JOIN?
___
*[saltapi/repository/target_repository.py, line 41 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGVZtt5a5_OjNMnXId:-MpGVZtt5a5_OjNMnXIe:b-fdzqgd) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/repository/target_repository.py#L41)):*
> ```Python
>        TB.Time_Base                     AS period_time_base,
>        HT.Identifier                    AS horizons_identifier,
>        IF(MT1.Target_Id IS NOT NULL,
> ```

This is not entirely correct: According to this logic Horizons targets would be sidereal./
___
*[saltapi/repository/target_repository.py, line 71 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGVptw8OtQ5ZGvU5c5:-MpGVptw8OtQ5ZGvU5c6:bn3rgn0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/repository/target_repository.py#L71)):*
> ```Python
>             "period_ephemeris": self._period_ephemeris(row),
>             "horizons_identifier": row.horizons_identifier,
>             "non_sidereal": row.non_sidereal > 0
> ```

Maybe say "= 1" rather than "> 0". I know its functionally the same here, but it might be a bit clearer.
___
*[saltapi/web/schema/proposal.py, line 66 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGWF-n2OAo9EJsgiT2:-MpGWF-n2OAo9EJsgiT3:bgd0w6y) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/web/schema/proposal.py#L66)):*
> ```Python
> 
> class ProposalStatus(BaseModel):
>     """Proposal status"""
> ```

Full stop missing.
___
*[saltapi/web/schema/proposal.py, line 151 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGW_m7ElabtJmOnDqF:-MpGW_m7ElabtJmOnDqG:bc329o5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/web/schema/proposal.py#L151)):*
> ```Python
>         description="Brief (one-line) summary to include in the observing night log",
>     )
> ```

For consistency: No blank line between summary_for_night_log and is_self_activable

And is there a word "activable"...? Maybe better "activatable" (even though that word probable doesn't exist either...) The same problem applies to the is_self_activable method in proposal_repository, so I guess it might have been my fault,,,
___
*[saltapi/web/schema/proposal.py, line 154 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGYTj-6pTtCjvm19F3:-MpGYTj-6pTtCjvm19F4:b-sjfv82) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/web/schema/proposal.py#L154)):*
> ```Python
>     is_self_activable: bool = Field(
>         ...,
>         title="Proposal activation by the Principal Investigator and Principal Contact",
> ```

title="Can the proposal be self-activated?"
description="Can the proposal be activated by the Principal Investigator or Principal Contact?"
___
*[saltapi/web/schema/target.py, line 119 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGZ2dm5RC_j39et-z6:-MpGZ2dm5RC_j39et-z7:b-hmlezt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/web/schema/target.py#L119)):*
> ```Python
>     non_sidereal: bool = Field(
>         ...,
>         title="Is a target a non sidereal?",
> ```

title="Is the target non-sidereal?
description="Is the target a non-sidereal target?"

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/36)* status: all files reviewed, 7 unresolved discussions (waiting on @mofokeng-chaka)

___
*[saltapi/repository/target_repository.py, line 42 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpHFo9TClLF6Wxg5jDV:-MpHFo9TClLF6Wxg5jDW:bz2q6ux) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/660c635216918b5499cfe91c0799a38854381786/saltapi/repository/target_repository.py#L42)):*
> ```Python
>                 HT.Identifier                                    AS horizons_identifier,
>                 IF((MT1.Target_Id IS NOT NULL
>                     OR HT.HorizonsTarget_Id IS NOT NULL),
> ```

It turns out that I was wrong: Horizons targets are recorded in the MovingTable. However, targets in yhjr MovingTableFile table are not in MovingTable table; so you have to check for these as well.
___
*[saltapi/web/schema/proposal.py, line 154 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpHDHRDBhXazw3LS9dH:-MpHDHRDBhXazw3LS9dI:b-gjvp94) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/660c635216918b5499cfe91c0799a38854381786/saltapi/web/schema/proposal.py#L154)):*
> ```Python
>         ...,
>         title="Can the proposal be self-activated?",
>         description="Can the proposal be activated by the Principal Investigator or Principal Contact",
> ```

"?" missing.
___
*[tests/repository/test_target_repository.py, line 160 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpHDeTD6MI5ez6qGB-Q:-MpHDeTD6MI5ez6qGB-R:b-7c92a5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/660c635216918b5499cfe91c0799a38854381786/tests/repository/test_target_repository.py#L160)):*
> ```Python
> 
>     assert target["horizons_identifier"] is None
>     assert target["non_sidereal"] == 0
> ```

Checking equality with 0 is a bit misleading, perhaps, as target["non_sidereal"] should be a boolean. So maybe better:

assert target["non_sidereal"] is False

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/36)* status: 6 of 9 files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/proposal_repository.py, line 64 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGVKtRBtYKT7Nl9nmv:-MpH1IBME93slq81eqhn:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/repository/proposal_repository.py#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might this have to be a LEFT JOIN?
</blockquote></details>

Done.
___
*[saltapi/repository/proposal_repository.py, line 457 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGVT7ECx99t5xUtjXq:-MpH1InLE89vABl_G4a6:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/repository/proposal_repository.py#L457)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might this have to be a LEFT JOIN?
</blockquote></details>

Done.
___
*[saltapi/repository/target_repository.py, line 41 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGVZtt5a5_OjNMnXId:-MpH1KGc53DH99boQTE3:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/repository/target_repository.py#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is not entirely correct: According to this logic Horizons targets would be sidereal./
</blockquote></details>

Done.
___
*[saltapi/repository/target_repository.py, line 71 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGVptw8OtQ5ZGvU5c5:-MpH1Kp_BZ30RPaQ3h75:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/repository/target_repository.py#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe say "= 1" rather than "> 0". I know its functionally the same here, but it might be a bit clearer.
</blockquote></details>

Done.
___
*[saltapi/repository/target_repository.py, line 42 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpHFo9TClLF6Wxg5jDV:-MpHfAXXDeAl45FS4Gyd:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/660c635216918b5499cfe91c0799a38854381786/saltapi/repository/target_repository.py#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It turns out that I was wrong: Horizons targets are recorded in the MovingTable. However, targets in yhjr MovingTableFile table are not in MovingTable table; so you have to check for these as well.
</blockquote></details>

Done.
___
*[saltapi/web/schema/proposal.py, line 66 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGWF-n2OAo9EJsgiT2:-MpH1OrjBbgn_pZM4OLB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/web/schema/proposal.py#L66)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Full stop missing.
</blockquote></details>

Done.
___
*[saltapi/web/schema/proposal.py, line 151 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGW_m7ElabtJmOnDqF:-MpH1Q7d5RbDYFd-O4Ek:b-bkajyq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/web/schema/proposal.py#L151)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency: No blank line between summary_for_night_log and is_self_activable

And is there a word "activable"...? Maybe better "activatable" (even though that word probable doesn't exist either...) The same problem applies to the is_self_activable method in proposal_repository, so I guess it might have been my fault,,,
</blockquote></details>

Yes, I think this part was done by you. Anyway I have made those chanegs
___
*[saltapi/web/schema/proposal.py, line 154 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGYTj-6pTtCjvm19F3:-MpH1fulBZAjbB3hajE0:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/web/schema/proposal.py#L154)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

title="Can the proposal be self-activated?"
description="Can the proposal be activated by the Principal Investigator or Principal Contact?"
</blockquote></details>

Done.
___
*[saltapi/web/schema/proposal.py, line 154 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpHDHRDBhXazw3LS9dH:-MpHdolgB5AVK-7DZh6Q:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/660c635216918b5499cfe91c0799a38854381786/saltapi/web/schema/proposal.py#L154)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"?" missing.
</blockquote></details>

Done.
___
*[saltapi/web/schema/target.py, line 119 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpGZ2dm5RC_j39et-z6:-MpH1gfL50YqgbWPZs2O:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c5a3e056a30e7341375377b4b0941af2beb638b3/saltapi/web/schema/target.py#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

title="Is the target non-sidereal?
description="Is the target a non-sidereal target?"
</blockquote></details>

Done.
___
*[tests/repository/test_target_repository.py, line 160 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/36#-MpHDeTD6MI5ez6qGB-Q:-MpHdvrs8qAhEl7_IuvY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/660c635216918b5499cfe91c0799a38854381786/tests/repository/test_target_repository.py#L160)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Checking equality with 0 is a bit misleading, perhaps, as target["non_sidereal"] should be a boolean. So maybe better:

assert target["non_sidereal"] is False
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
