### PR TITLE
Fix the reset password end point.

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/291)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
The tests are now failing.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/291#-:-NvkjyIU6uNI8GSx3e4k:b-ad98q5)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/users.py` line 55 at r1](https://reviewable.io/reviews/saltastroops/salt-api/291#-Nvkh4r_C8V0dMHsozHz:-Nvkh4raET9emmiZRe6v:bglt75z) ([raw file](https://github.com/saltastroops/salt-api/blob/f5b891f28a1623b92dd9047aa7c90c7633903074/saltapi/web/api/users.py#L55)):*
> ```Python
> 
>         if not user:
>             raise NotFoundError("User not found.")
> ```

How about the following ?

```python
user = user_service.get_user_by_username(username_email) or user_service.get_user_by_email(username_email)
if not user:
    raise NotFoundError("User not found.")
```



_Code quote:_
```Python
        user = user_service.get_user_by_username(username_email)
        if not user:
            user = user_service.get_user_by_email(username_email)

        if not user:
            raise NotFoundError("User not found.")
```
___
*[`saltapi/web/api/users.py` line 321 at r1](https://reviewable.io/reviews/saltastroops/salt-api/291#-NvkhtlK4ptJft-Pv2Nd:-NvkhtlK4ptJft-Pv2Ne:b-mb3afn) ([raw file](https://github.com/saltastroops/salt-api/blob/f5b891f28a1623b92dd9047aa7c90c7633903074/saltapi/web/api/users.py#L321)):*
> ```Python
>         ...,
>         title="Password and authentication token",
>         description="Password to replace the old one. And and Authentication token to verify the user"
> ```

"Password to replace the old one. And and Authentication token to verify the user" >> "Password to replace the old one, and an authentication token to verify the user"
___
*[`saltapi/web/api/users.py` line 341 at r1](https://reviewable.io/reviews/saltastroops/salt-api/291#-NvkiZQx6m8kapgWGxxI:-NvkiZQz1vCLZ15Qrpg_:b-qoilvo) ([raw file](https://github.com/saltastroops/salt-api/blob/f5b891f28a1623b92dd9047aa7c90c7633903074/saltapi/web/api/users.py#L341)):*
> ```Python
>             return user
> 
>         raise NotFoundError("Unknown user.")
> ```

How about? 
```python
user = authentication_service.validate_auth_token(password_update.authentication_key, verification=True)
if not user:
    raise NotFoundError("Unknown user.")

permission_service = services.permission_service(unit_of_work.connection)
permission_service.check_permission_to_update_user(user, user_id)

user_service = services.user_service(unit_of_work.connection)
user_service.update_password(user_id, password_update.password)

unit_of_work.commit()
user = user_service.get_user(user_id)
return user
```



_Code quote:_
```Python
        if user:
            permission_service = services.permission_service(unit_of_work.connection)
            permission_service.check_permission_to_update_user(user, user_id)

            user_service = services.user_service(unit_of_work.connection)
            user_service.update_password(user_id, password_update.password)

            unit_of_work.commit()
            user = user_service.get_user(user_id)
            return user

        raise NotFoundError("Unknown user.")
```
___
*[`saltapi/web/schema/user.py` line 189 at r1](https://reviewable.io/reviews/saltastroops/salt-api/291#-NvkjMXsBVVyZEX8Xplz:-NvkjMXsBVVyZEX8Xpm-:b-c5lgps) ([raw file](https://github.com/saltastroops/salt-api/blob/f5b891f28a1623b92dd9047aa7c90c7633903074/saltapi/web/schema/user.py#L189)):*
> ```Python
> class PasswordUpdate(BaseModel):
>     password: str = Field(..., title="Password", description="Password.")
>     authentication_key: str = Field(..., title="Authentication Token", description="The authentication Token")
> ```

For consistency: "Authentication Token" >> "Authentication token"

**Review by mofokeng-chaka — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/291#-:-Nw4wsR72CkwYqeTvhRL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/291)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`saltapi/web/api/users.py` line 55 at r1](https://reviewable.io/reviews/saltastroops/salt-api/291#-Nvkh4r_C8V0dMHsozHz:-Nw4aGgh-b2wKeUdIpHS:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f5b891f28a1623b92dd9047aa7c90c7633903074/saltapi/web/api/users.py#L55)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

How about the following ?

```python
user = user_service.get_user_by_username(username_email) or user_service.get_user_by_email(username_email)
if not user:
    raise NotFoundError("User not found.")
```
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 321 at r1](https://reviewable.io/reviews/saltastroops/salt-api/291#-NvkhtlK4ptJft-Pv2Nd:-Nw4aUq2EXgHzapOSzym:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f5b891f28a1623b92dd9047aa7c90c7633903074/saltapi/web/api/users.py#L321)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

"Password to replace the old one. And and Authentication token to verify the user" >> "Password to replace the old one, and an authentication token to verify the user"
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 341 at r1](https://reviewable.io/reviews/saltastroops/salt-api/291#-NvkiZQx6m8kapgWGxxI:-Nw4bt_23KInGXFUOPAx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f5b891f28a1623b92dd9047aa7c90c7633903074/saltapi/web/api/users.py#L341)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

How about? 
```python
user = authentication_service.validate_auth_token(password_update.authentication_key, verification=True)
if not user:
    raise NotFoundError("Unknown user.")

permission_service = services.permission_service(unit_of_work.connection)
permission_service.check_permission_to_update_user(user, user_id)

user_service = services.user_service(unit_of_work.connection)
user_service.update_password(user_id, password_update.password)

unit_of_work.commit()
user = user_service.get_user(user_id)
return user
```
</blockquote></details>

Done.
___
*[`saltapi/web/schema/user.py` line 189 at r1](https://reviewable.io/reviews/saltastroops/salt-api/291#-NvkjMXsBVVyZEX8Xplz:-Nw4accWCUXeCQ4zF7JH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f5b891f28a1623b92dd9047aa7c90c7633903074/saltapi/web/schema/user.py#L189)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

For consistency: "Authentication Token" >> "Authentication token"
</blockquote></details>

Done.

**Review by Eb-Zeero — COMMENTED** [review]
Fixed

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/291#-:-Nw5EXyJCVtd7GiCHhvC:b-886gsx)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

**Review by mofokeng-chaka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/291)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
