### PR TITLE
tests-updates

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Tests updates

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/71)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 19 of 86 files at r1, 77 of 77 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/71)* status: 81 of 86 files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`tests/integration/users/test_get_user.py` line 10 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3s8z70BXfQAPzVZGgB:-N3s8z70BXfQAPzVZGgC:b-hcckn1) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/integration/users/test_get_user.py#L10)):*
> ```Python
>     authenticate,
>     find_username,
>     get_authenticated_user_id,
> ```

I am losing track on what is happening to this method.
have we removed the get method for gettin gthe user by username?
___
*[`tests/integration/users/test_patch_user.py` line 20 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3s9xGNEaiD_BP-FCc-:-N3s9xGNEaiD_BP-FCc0:b-ubhjg2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/integration/users/test_patch_user.py#L20)):*
> ```Python
> 
> def _url(user_id: int) -> str:
>     return USERS_URL + str(user_id)
> ```

as commented some where can we chat about this?
___
*[`tests/integration/users/test_post_user.py` line 77 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3s6FwS6C8SqGtDtZc_:-N3s6FwS6C8SqGtDtZca:b-z73oyl) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/integration/users/test_post_user.py#L77)):*
> ```Python
> def test_post_user_should_create_a_new_user(client: TestClient) -> None:
>     new_user_details = _new_user_details()
>     new_user_details["affiliations"] = [
> ```

This should be added to the _new_user_details() as the method only return new user
___
*[`tests/integration/users/test_post_user.py` line 94 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3s6p8ZDWC7JJBor4Ti:-N3s6p8ZDWC7JJBor4Tj:boqepne) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/integration/users/test_post_user.py#L94)):*
> ```Python
>     response = client.post(USERS_URL, json=new_user_details)
>     assert response.status_code == status.HTTP_201_CREATED
>     assert response.json()["affiliations"] == expected_user["affiliations"]
> ```

you should thest the whole user or nothing since this tests the creation of a new user.
and status 201 means created.
___
*[`tests/repository/test_submission_repository.py` line 35 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3sAKIn20MwCVN_tlEs:-N3sAKIn20MwCVN_tlEt:bp6qwdo) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/repository/test_submission_repository.py#L35)):*
> ```Python
>     assert submission["proposal_code"] is None
>     assert submission["submitter_id"] == 1243
>     assert submission["status"] == SubmissionStatus.FAILED
> ```

I see something wrong with this thes but I am not sure what!
why change from in_progress to fail? 
___
*[`tests/repository/test_user_repository.py` line 554 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3s7AF02OcgsJUhESbA:-N3s7AF02OcgsJUhESbB:bptomzp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/repository/test_user_repository.py#L554)):*
> ```Python
>         username = d["username"]
>         expected_roles = set(d["roles"])
>         print(user_repository.get_user_roles(username))
> ```

remove print statement

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/71)* status: 81 of 86 files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

___
*[`tests/integration/users/test_get_user.py` line 10 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3s8z70BXfQAPzVZGgB:-N3sHjNe3YGno8bVD0cW:bgn93h0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/integration/users/test_get_user.py#L10)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I am losing track on what is happening to this method.
have we removed the get method for gettin gthe user by username?
</blockquote></details>

I think the answer to your question is yes and no. Yes, at an API level the get (user) method has since changed from using the username to using user id, hence the changes I have made herein . And no, at a service level this method still exist
___
*[`tests/integration/users/test_patch_user.py` line 20 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3s9xGNEaiD_BP-FCc-:-N3sJLyfEAyJ4FhvOEEk:b6h8nur) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/integration/users/test_patch_user.py#L20)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

as commented some where can we chat about this?
</blockquote></details>

No problem, we can have a chat about this.
___
*[`tests/integration/users/test_post_user.py` line 77 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3s6FwS6C8SqGtDtZc_:-N3sKVs12MHNvcJQk3gz:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/integration/users/test_post_user.py#L77)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

This should be added to the _new_user_details() as the method only return new user
</blockquote></details>

Done.
___
*[`tests/integration/users/test_post_user.py` line 94 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3s6p8ZDWC7JJBor4Ti:-N3sN5cE949KgHNLkyE0:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/integration/users/test_post_user.py#L94)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

you should thest the whole user or nothing since this tests the creation of a new user.
and status 201 means created.
</blockquote></details>

Done.
___
*[`tests/repository/test_submission_repository.py` line 35 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3sAKIn20MwCVN_tlEs:-N3sNBCI9-HkrsfkJgD_:b-cj30vq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/repository/test_submission_repository.py#L35)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I see something wrong with this thes but I am not sure what!
why change from in_progress to fail? 
</blockquote></details>

Upon investigating why these tests were failing I found that it because the status was not in "progress" but "fail". I think it is the fact that the submission was handled and a status was changed from in progress to failed. Maybe let's discuss this if I don't make any sense. Also, I think it might be worth having this discussion with Christian as well.
___
*[`tests/repository/test_user_repository.py` line 554 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3s7AF02OcgsJUhESbA:-N3sOZor-OsTaXuouEj6:bwqhqql) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/repository/test_user_repository.py#L554)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

remove print statement
</blockquote></details>

I missed this, thanks!

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 86 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/71)* status: all files reviewed, 8 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`tests/integration/users/test_get_user.py` line 28 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N5K7rmKCTsaZGPlxucz:-N5K7rmKCTsaZGPlxud-:b-17bpu2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8b1fe3dbdf99afc4ed492ab2a796177709e403dd/tests/integration/users/test_get_user.py#L28)):*
> ```Python
> ) -> None:
>     not_authenticated(client)
>     user_id = 1602
> ```

It might be reasonable to choose different user ids. When I saw the id 1602, my first thought was "Do we actually have that many users?".
___
*[`tests/integration/users/test_patch_user.py` line 74 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N5K9ioF0hZdB4DYpB0F:-N5K9ioG35RLHf9bjHRz:biog47d) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8b1fe3dbdf99afc4ed492ab2a796177709e403dd/tests/integration/users/test_patch_user.py#L74)):*
> ```Python
> 
> def test_patch_user_should_keep_existing_values_by_default(client: TestClient) -> None:
>     new_user = create_user(client)
> ```

I don't think user should be renamed to new_user here or in the other tests.

Yes, the user is "new" in the sense that the test creates the user. But this is immaterial for the test, and the prefix "new_" in the tests rather suggests that a value is updated.
___
*[`tests/integration/users/test_post_user.py` line 94 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N3s6p8ZDWC7JJBor4Ti:-N5KAPjs6epcpwjL10KS:b-7u9fuj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/845ac6b71bb90020391f0735897a066efffcec2f/tests/integration/users/test_post_user.py#L94)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Shouldn't the comment be

`# check properties other than the user id` ?

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 86 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/71)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/71)* status: 83 of 86 files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`tests/integration/users/test_get_user.py` line 28 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N5K7rmKCTsaZGPlxucz:-N6SjUze3_f80hsDB-0Y:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8b1fe3dbdf99afc4ed492ab2a796177709e403dd/tests/integration/users/test_get_user.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be reasonable to choose different user ids. When I saw the id 1602, my first thought was "Do we actually have that many users?".
</blockquote></details>

Done.
___
*[`tests/integration/users/test_patch_user.py` line 74 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/71#-N5K9ioF0hZdB4DYpB0F:-N6SiqAr-iRvZcq5RTsy:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8b1fe3dbdf99afc4ed492ab2a796177709e403dd/tests/integration/users/test_patch_user.py#L74)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think user should be renamed to new_user here or in the other tests.

Yes, the user is "new" in the sense that the test creates the user. But this is immaterial for the test, and the prefix "new_" in the tests rather suggests that a value is updated.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/71)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
