### PR TITLE
github-workflow-updates

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Workflow updates

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/104)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/104)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`lint.sh` line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api/104#-NF8aqY1EG4xP1Hou3np:-NF8aqY1EG4xP1Hou3nq:bs230or) ([raw file](https://github.com/saltastroops/salt-api/blob/0dab64a0f75641fda6535e5fb3b01e1eb97c06fd/lint.sh#L1)):*
> ```Shell
> black saltapi tests --preview && \
> ```

Do you need the --preview flag?

Also, if you use it, wouldn't you have to use it everywhere you are using black?
___
*[`saltapi/service/create_proposal_progress_html.py` line 137 at r1](https://reviewable.io/reviews/saltastroops/salt-api/104#-NF8cE262AhAcRzDuDMS:-NF8cE262AhAcRzDuDMT:brqq9wr) ([raw file](https://github.com/saltastroops/salt-api/blob/0dab64a0f75641fda6535e5fb3b01e1eb97c06fd/saltapi/service/create_proposal_progress_html.py#L137)):*
> ```Python
>                 </div>
>             </div>
>         """
> ```

It might be worth having an else case with a message that there is no Phase 1 proposal and hence there are no previously requested observing conditions.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/104)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`lint.sh` line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api/104#-NF8aqY1EG4xP1Hou3np:-NF8hiYC3b_kkZ1hON5M:b-vmg55e) ([raw file](https://github.com/saltastroops/salt-api/blob/0dab64a0f75641fda6535e5fb3b01e1eb97c06fd/lint.sh#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you need the --preview flag?

Also, if you use it, wouldn't you have to use it everywhere you are using black?
</blockquote></details>

Yes, I do need it. and I have added the flag everywhere I am using black
___
*[`saltapi/service/create_proposal_progress_html.py` line 137 at r1](https://reviewable.io/reviews/saltastroops/salt-api/104#-NF8cE262AhAcRzDuDMS:-NF8ktX-BbpBdzlfbCWU:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/0dab64a0f75641fda6535e5fb3b01e1eb97c06fd/saltapi/service/create_proposal_progress_html.py#L137)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be worth having an else case with a message that there is no Phase 1 proposal and hence there are no previously requested observing conditions.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/104)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`tox.ini` line 11 at r2](https://reviewable.io/reviews/saltastroops/salt-api/104#-NF9EaqJEYKqjwzUHGhy:-NF9EaqJEYKqjwzUHGhz:b-ivwtot) ([raw file](https://github.com/saltastroops/salt-api/blob/6e44dcf60328ccc8e3f872155ebcd7120a615ccd/tox.ini#L11)):*
> ```INI
>     poetry install --no-interaction
>     poetry run isort --check saltapi tests
>     poetry run black --preview saltapi tests
> ```

You still need the `--check` flag, don't you?
___
*[`saltapi/service/create_proposal_progress_html.py` line 137 at r1](https://reviewable.io/reviews/saltastroops/salt-api/104#-NF8cE262AhAcRzDuDMS:-NF9Enk51p799hti7chE:b-ucfknh) ([raw file](https://github.com/saltastroops/salt-api/blob/0dab64a0f75641fda6535e5fb3b01e1eb97c06fd/saltapi/service/create_proposal_progress_html.py#L137)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/104)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`tox.ini` line 11 at r2](https://reviewable.io/reviews/saltastroops/salt-api/104#-NF9EaqJEYKqjwzUHGhy:-NF9G_pZ54VvpYthSr14:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/6e44dcf60328ccc8e3f872155ebcd7120a615ccd/tox.ini#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You still need the `--check` flag, don't you?
</blockquote></details>

Done.

**Review by hettlage — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/104)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

**Pull request merged**
