### PR TITLE
Phase1 observation type

### LINKED ISSUE #130: Phase1Target should be an observation
The `Phase1Target` class should rather be `Phase1Observation`, and it should not inherit from the `Target` class.

It should have a `target` field of type `Target`.

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/235)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
Can I please ask why change target to observation

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/235#-:-NXt6gx0-YL-kzRsaKV0:b-2issy9)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 299 at r1](https://reviewable.io/reviews/saltastroops/salt-api/235#-NXt51Oo3TTii216Zq0T:-NXt51Oo3TTii216Zq0U:b-701ztw) ([raw file](https://github.com/saltastroops/salt-api/blob/5b4bbd3471ab05ba46a447db6e25d97f26de7e1d/saltapi/repository/proposal_repository.py#L299)):*
> ```Python
>             "charged_time": self._charged_time(proposal_code, semester),
>             "observation_comments": self.get_observation_comments(proposal_code),
>             "observations": self._get_phase_one_observations(proposal_code),
> ```

this is not an observation it is a target.
___
*[`saltapi/repository/proposal_repository.py` line 2217 at r1](https://reviewable.io/reviews/saltastroops/salt-api/235#-NXt5AHQ7AAau8NDsP-z:-NXt5AHQ7AAau8NDsP0-:b90spjk) ([raw file](https://github.com/saltastroops/salt-api/blob/5b4bbd3471ab05ba46a447db6e25d97f26de7e1d/saltapi/repository/proposal_repository.py#L2217)):*
> ```Python
>         return [
>             {
>                 "target": {
> ```

you do not need an additional level
___
*[`saltapi/web/schema/p1_proposal.py` line 6 at r1](https://reviewable.io/reviews/saltastroops/salt-api/235#-NXt5RGf-tkra9zmJVEt:-NXt5RGf-tkra9zmJVEu:b-5x0wcs) ([raw file](https://github.com/saltastroops/salt-api/blob/5b4bbd3471ab05ba46a447db6e25d97f26de7e1d/saltapi/web/schema/p1_proposal.py#L6)):*
> ```Python
> 
> from saltapi.web.schema.proposal import GeneralProposalInfo, Proposal
> from saltapi.web.schema.target import Phase1Observation
> ```

this should be phase1Target
___
*[`saltapi/web/schema/p1_proposal.py` line 62 at r1](https://reviewable.io/reviews/saltastroops/salt-api/235#-NXt5WRm0qDd-H7q9Wvn:-NXt5WRm0qDd-H7q9Wvo:b2ss7xm) ([raw file](https://github.com/saltastroops/salt-api/blob/5b4bbd3471ab05ba46a447db6e25d97f26de7e1d/saltapi/web/schema/p1_proposal.py#L62)):*
> ```Python
>         description="General proposal information for a semester",
>     )
>     observations: Optional[List[Phase1Observation]] = Field(
> ```

see comment above

**Review by mofokeng-chaka — COMMENTED** [review]
This the suggestion from this issue: https://github.com/saltastroops/salt-api/issues/130#issue-1553541927

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/235#-:-NXt8ahy3v4ulyXCkbCj:br2k7kv)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

**Review by Eb-Zeero — COMMENTED** [review]
I overlooked the issue sorry.

this PR is somehow confusing me can it wait for Christian to review?

> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/235#-:-NXyFHtmA2ij-KJ1gh4w:b-7hvudz)* status: 1 of 4 files reviewed, all discussions resolved

**Review by mofokeng-chaka — COMMENTED** [review]
No problem, it'll wait for Christian.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/235#-:-NXyNtoK-VmK3YmJ5l3h:b-nbztfq)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/235)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`saltapi/web/schema/target.py` line 142 at r1](https://reviewable.io/reviews/saltastroops/salt-api/235#-NYXYTor1_CRPKIO587y:-NYXYTor1_CRPKIO587z:b-p0xgru) ([raw file](https://github.com/saltastroops/salt-api/blob/5b4bbd3471ab05ba46a447db6e25d97f26de7e1d/saltapi/web/schema/target.py#L142)):*
> ```Python
> 
> 
> class Phase1Observation(BaseModel):
> ```

Shouldn't that be P1Observation? And shouldn't it be defined in `p1_proposal.py`?

**Comment by mofokeng-chaka** [comment]
>> Shouldn't that be P1Observation? And shouldn't it be defined in p1_proposal.py?

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
