### PR TITLE
Getting the list of SALT astronomers

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/158)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/158)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 447 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMp2fv0HKeEoYJGK1B:-NNMp2fv0HKeEoYJGK1C:bpm6uog) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/repository/proposal_repository.py#L447)):*
> ```Python
>        PGI.TimeRestricted                  AS is_time_restricted,
>        P1T.Reason						   AS too_reason,
>        I.PiptUser_Id                      AS liaison_salt_astronomer_id,
> ```

The "AS" is not aligned properly.
___
*[`saltapi/repository/user_repository.py` line 626 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMpJ0n47OqFwVlykKG:-NNMpJ0n47OqFwVlykKH:boh36ce) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/repository/user_repository.py#L626)):*
> ```Python
>     def get_salt_astronomers(self) -> List[Dict[str, Any]]:
>         """
>        Returns a list of salt Astronomers
> ```

Return the list of SALT Astronomers.
___
*[`saltapi/repository/user_repository.py` line 641 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMqUsC3QHUNvRNOtzR:-NNMqUsC3QHUNvRNOtzS:b-1u1c7j) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/repository/user_repository.py#L641)):*
> ```Python
>         result = self.connection.execute(stmt)
> 
>         salt_astronomers = []
> ```

A bit shorter, perhaps:

```
salt_astronomers = [
    { 
       "id": row.id,
       "given_name": row.given_name,
       "family_name": row.family_name,
   }
   for row in result if row.given_name != "Techops"
]
```
___
*[`saltapi/web/api/users.py` line 101 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMrkvW3NugO79S1ZeT:-NNMrkvW3NugO79S1ZeU:bkiwz0) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/web/api/users.py#L101)):*
> ```Python
>         return user_service.get_users()
> 
> @router.get("/salt-astronomers", summary="Get SALT astronomers", response_model=List[UserListItem])
> ```

Get SALT > Get the SALT
___
*[`saltapi/web/api/users.py` line 102 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMrdyG6kNbwXl90ruZ:-NNMrdyH4gZhQyDsMmkr:b799pxd) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/web/api/users.py#L102)):*
> ```Python
> 
> @router.get("/salt-astronomers", summary="Get SALT astronomers", response_model=List[UserListItem])
> def get_users(
> ```

get_users > get_salt_astronomers
___
*[`saltapi/web/api/users.py` line 103 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMrwiFDm1Xbda4L-NZ:-NNMrwiFDm1Xbda4L-N_:buig9j) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/web/api/users.py#L103)):*
> ```Python
> @router.get("/salt-astronomers", summary="Get SALT astronomers", response_model=List[UserListItem])
> def get_users(
>         user: _User = Depends(get_current_user),
> ```

The user is not needed.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/158)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 447 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMp2fv0HKeEoYJGK1B:-NNb6lc70JeWAH5kZ6_U:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/repository/proposal_repository.py#L447)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The "AS" is not aligned properly.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 626 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMpJ0n47OqFwVlykKG:-NNb6tWSE-cA7N1DgCmU:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/repository/user_repository.py#L626)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Return the list of SALT Astronomers.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 641 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMqUsC3QHUNvRNOtzR:-NNb71Qm9RDvJ9Kl8ZXl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/repository/user_repository.py#L641)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A bit shorter, perhaps:

```
salt_astronomers = [
    { 
       "id": row.id,
       "given_name": row.given_name,
       "family_name": row.family_name,
   }
   for row in result if row.given_name != "Techops"
]
```

</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 101 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMrkvW3NugO79S1ZeT:-NNb7Ax88rSw4DOji3P_:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/web/api/users.py#L101)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Get SALT > Get the SALT
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 102 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMrdyG6kNbwXl90ruZ:-NNb7FLD79rv4EEiTAnH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/web/api/users.py#L102)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

get_users > get_salt_astronomers
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 103 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNMrwiFDm1Xbda4L-NZ:-NNb7pYu5xl_XongTkpg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/web/api/users.py#L103)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The user is not needed.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/158)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/users.py` line 104 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNbAQXH3G4XMPCtkKSe:-NNbAQXH3G4XMPCtkKSf:baviojg) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/web/api/users.py#L104)):*
> ```Python
> def get_users(
>         user: _User = Depends(get_current_user),
> ) -> List[Dict[str, Any]]:
> ```

I would suggest that you add at least a test that non-authenticated users may request the list of SALT Astronomers.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/158)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/api/users.py` line 104 at r1](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNbAQXH3G4XMPCtkKSe:-NNc6T459S-QglUxIVEI:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/30af034d0878ab49b4889dc7509fa1114e447165/saltapi/web/api/users.py#L104)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest that you add at least a test that non-authenticated users may request the list of SALT Astronomers.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/158)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`tests/integration/users/test_get_user.py` line 149 at r3](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNfaaWP-xFWesnkm6LX:-NNfaaWP-xFWesnkm6LY:b-k58xm9) ([raw file](https://github.com/saltastroops/salt-api/blob/ff3da4446b3440a24e7f898430ac4f42d33655f7/tests/integration/users/test_get_user.py#L149)):*
> ```Python
>     ],
> )
> def test_any_user_can_view_list_of_salt_astronomers(
> ```

I'm not sure this test is necessary, give that yo are testing that unauthenticated users can request the list?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/158)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/integration/users/test_get_user.py` line 149 at r3](https://reviewable.io/reviews/saltastroops/salt-api/158#-NNfaaWP-xFWesnkm6LX:-NNfs6TN6tML3VYpTvhr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/ff3da4446b3440a24e7f898430ac4f42d33655f7/tests/integration/users/test_get_user.py#L149)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure this test is necessary, give that yo are testing that unauthenticated users can request the list? 
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
