### PR TITLE
MOS Mask bug fix

### PR DESCRIPTION
**Pull request by Eb-Zeero**
BUG fixed

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/223)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/223)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/repository/rss_repository.py` line 427 at r1](https://reviewable.io/reviews/saltastroops/salt-api/223#-NV-efEh8nN0COjDgFDP:-NV-efEh8nN0COjDgFDQ:bc5hupy) ([raw file](https://github.com/saltastroops/salt-api/blob/b7bf67e5968be9bf24363e69160ba04997470182/saltapi/repository/rss_repository.py#L427)):*
> ```Python
> 
>         results = self.connection.execute(
>             text(stmt), {"mask_types": tuple([m.value for m in mask_types])}
> ```

Just wondering: Do you really need to convert to a `tuple`?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/223)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/repository/rss_repository.py` line 427 at r1](https://reviewable.io/reviews/saltastroops/salt-api/223#-NV-efEh8nN0COjDgFDP:-NV0b8-Z70YNeKzmKUdw:b-a2860a) ([raw file](https://github.com/saltastroops/salt-api/blob/b7bf67e5968be9bf24363e69160ba04997470182/saltapi/repository/rss_repository.py#L427)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Just wondering: Do you really need to convert to a `tuple`?
</blockquote></details>

yes fixed

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/223)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/instruments.py` line 119 at r3](https://reviewable.io/reviews/saltastroops/salt-api/223#-NV0ca__2wv8hVBzYiZz:-NV0ca_aEjgHJN6uwdG7:bwm4dv7) ([raw file](https://github.com/saltastroops/salt-api/blob/743d87369fdd039ca86a5beb7c884aed609da1e6/saltapi/web/api/instruments.py#L119)):*
> ```Python
>         [],
>         title="Mask types",
>         description="The mask to types to include.",
> ```

Maybe better "The mask types to check." ?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/223)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/web/api/instruments.py` line 119 at r3](https://reviewable.io/reviews/saltastroops/salt-api/223#-NV0ca__2wv8hVBzYiZz:-NV5Xj5PBTdRtjEVx_HM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/743d87369fdd039ca86a5beb7c884aed609da1e6/saltapi/web/api/instruments.py#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better "The mask types to check." ?
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
