### PR TITLE
Slit mask table

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/329)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/329)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/instrument_repository.py` line 66 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARFP1Y4z2yLP-0Ke3s:-OARFP1Y4z2yLP-0Ke3t:bddux1y) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/repository/instrument_repository.py#L66)):*
> ```Python
>         return self.rss_repository.get_obsolete_rss_masks_in_magazine(mask_types)
> 
>     def get_rss_slit_mask(self, exclude_mask_types: List[RssMaskType]) -> List[Dict[str, Any]]:
> ```

`get_rss_slit_mask` > `get_rss_slit_masks`
___
*[`saltapi/service/instrument_service.py` line 37 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARFYMU1B01uGzvlmp9:-OARFYMU1B01uGzvlmpA:bddux1y) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/service/instrument_service.py#L37)):*
> ```Python
>         return self.instrument_repository.get_obsolete_rss_masks_in_magazine(mask_types)
> 
>     def get_rss_slit_mask(self, exclude_mask_types: List[RssMaskType]) -> List[Dict[str, Any]]:
> ```

`get_rss_slit_mask` > `get_rss_slit_masks`
___
*[`saltapi/service/instrument_service.py` line 38 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARFal67igELir_y5q5:-OARFal67igELir_y5q6:b9po9e0) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/service/instrument_service.py#L38)):*
> ```Python
> 
>     def get_rss_slit_mask(self, exclude_mask_types: List[RssMaskType]) -> List[Dict[str, Any]]:
>         """The list of the  RSS slit masks."""
> ```

Too much space between "the" and "RSS"
___
*[`saltapi/web/api/instruments.py` line 151 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARDTBxD-56pLSGuN9X:-OARDTBy4itbz8-I42nC:bu76148) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/web/api/instruments.py#L151)):*
> ```Python
>             [],
>             title="Mask types",
>             description="The mask types to exclude.",
> ```

For consistency, there should be no full stop after "exclude" in the summary.
___
*[`saltapi/web/api/instruments.py` line 161 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARENLh7P526E_45srf:-OARENLh7P526E_45srg:b-5a98sl) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/web/api/instruments.py#L161)):*
> ```Python
>     with UnitOfWork() as unit_of_work:
>         permission_service = services.permission_service(unit_of_work.connection)
>         permission_service.check_permission_to_view_obsolete_masks_in_magazine(user)
> ```

The naming of the permission looks a bit odd... Maybe the "obsolete" should be removed?
___
*[`saltapi/web/api/instruments.py` line 164 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARDwSf0UtTmTt6yNnq:-OARDwSf0UtTmTt6yNnr:b5mwr65) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/web/api/instruments.py#L164)):*
> ```Python
> 
>         instrument_service = services.instrument_service(unit_of_work.connection)
>         return [RssMask(**mask) for mask in instrument_service.get_rss_slit_mask(exclude_mask_types)]
> ```

Do yo have to explicitly do the conversion into RssMask? FastAPI might do this for you out of the box?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/329)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/instrument_repository.py` line 66 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARFP1Y4z2yLP-0Ke3s:-OAXsToJEvifEuCDLaqs:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/repository/instrument_repository.py#L66)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`get_rss_slit_mask` > `get_rss_slit_masks`
</blockquote></details>

Done.
___
*[`saltapi/service/instrument_service.py` line 37 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARFYMU1B01uGzvlmp9:-OAXsfpE2Et8FSZpCvID:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/service/instrument_service.py#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`get_rss_slit_mask` > `get_rss_slit_masks`
</blockquote></details>

Done.
___
*[`saltapi/service/instrument_service.py` line 38 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARFal67igELir_y5q5:-OAXsgAr1vUQCRtM3uOY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/service/instrument_service.py#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Too much space between "the" and "RSS"
</blockquote></details>

Done.
___
*[`saltapi/web/api/instruments.py` line 151 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARDTBxD-56pLSGuN9X:-OAXsoDqDq_mMrKgJY_y:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/web/api/instruments.py#L151)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency, there should be no full stop after "exclude" in the summary.
</blockquote></details>

Done.
___
*[`saltapi/web/api/instruments.py` line 161 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARENLh7P526E_45srf:-OAXtHW_Bc6hpB-e4rax:b-bpgn3f) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/web/api/instruments.py#L161)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The naming of the permission looks a bit odd... Maybe the "obsolete" should be removed?
</blockquote></details>

there are no permissions for this reuse other permissions...
added one now
___
*[`saltapi/web/api/instruments.py` line 164 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARDwSf0UtTmTt6yNnq:-OAXtfgl2aFQ3DL3puOF:bkncukq) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/web/api/instruments.py#L164)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do yo have to explicitly do the conversion into RssMask? FastAPI might do this for you out of the box?
</blockquote></details>

yes it does but give a warning for  Dict[str, any] not being of type RssMask

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/329)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/instruments.py` line 161 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARENLh7P526E_45srf:-OBAqt6x5hv5RzQqTBT8:b-9vy4c7) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/web/api/instruments.py#L161)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

there are no permissions for this reuse other permissions...
added one now
</blockquote></details>

I didn't mean to say that you shouldn't reuse the existing permission, but rather that the existing permission name would have to be updated to reflect its broader use. But I guess having a separate permission is perfectly fine as well.
___
*[`saltapi/web/api/instruments.py` line 164 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARDwSf0UtTmTt6yNnq:-OBArj6b3v0FtZ4fg8of:b-oo0nro) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/web/api/instruments.py#L164)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

yes it does but give a warning for  Dict[str, any] not being of type RssMask
</blockquote></details>

Yes, but that is because your type hint is requesting a list of `RssMask`s.
___
*[`saltapi/service/permission_service.py` line 371 at r2](https://reviewable.io/reviews/saltastroops/salt-api/329#-OBAqauE5pFh5Nh_nfj8:-OBAqauE5pFh5Nh_nfj9:bxt3065) ([raw file](https://github.com/saltastroops/salt-api/blob/b18704e731dfe2ce9482dbeb0f8efd6fe45c0671/saltapi/service/permission_service.py#L371)):*
> ```Python
>     def check_permission_to_view_rss_masks(self, user: User) -> None:
>         """
>         Check that the user can view the rss slit masks.
> ```

rss > RSS

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/329)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 371 at r2](https://reviewable.io/reviews/saltastroops/salt-api/329#-OBAqauE5pFh5Nh_nfj8:-OCXv_9eA5sGecx-Z68v:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b18704e731dfe2ce9482dbeb0f8efd6fe45c0671/saltapi/service/permission_service.py#L371)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

rss > RSS
</blockquote></details>

Done.
___
*[`saltapi/web/api/instruments.py` line 161 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARENLh7P526E_45srf:-OCXy68m8pi0K07D36BA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/web/api/instruments.py#L161)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I didn't mean to say that you shouldn't reuse the existing permission, but rather that the existing permission name would have to be updated to reflect its broader use. But I guess having a separate permission is perfectly fine as well.
</blockquote></details>

Done.
___
*[`saltapi/web/api/instruments.py` line 164 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARDwSf0UtTmTt6yNnq:-OCXwjJK41mOENKUGNEK:b-b2v4r9) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/web/api/instruments.py#L164)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes, but that is because your type hint is requesting a list of `RssMask`s.
</blockquote></details>

just forgot to mention the "list" part but it 

the whole file is implemented like this.

one of your comments some time back was not to use Schema types above the service level
what is returned by `instrument\_service.get\_rss\_slit\_masks(exclude\_mask\_types)` is List[Dict[str, Any]]
!= List List[RssMask]  returned by this function
hence the type error

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/329)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/api/instruments.py` line 161 at r1](https://reviewable.io/reviews/saltastroops/salt-api/329#-OARENLh7P526E_45srf:-OCXyJot-w54mYEyq2hq:bg5x439) ([raw file](https://github.com/saltastroops/salt-api/blob/c9f6c894de93cc2d4d4a3ef95e4ea507fc24e968/saltapi/web/api/instruments.py#L161)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Already implemented

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/329)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
