### PR TITLE
A flag to determine if filter is available

### LINKED ISSUE #317: All the salticam filter are unavailable
Add a flag to determine if salticam filter is available

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/318)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/318)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/salticam_repository.py` line 131 at r1](https://reviewable.io/reviews/saltastroops/salt-api/318#-O2Uo0LP7ZMSOIx9Y_c5:-O2Uo0LQ4ecnhtY_cFdZ:b7rhgme) ([raw file](https://github.com/saltastroops/salt-api/blob/306a73530cc1ed7ebeb71b20252fcefb50cfee6b/saltapi/repository/salticam_repository.py#L131)):*
> ```Python
>        SF.DescriptiveName                   AS filter_description,
>        SFPD.ExposureTime / 1000             AS exposure_time,
>        IF(SCF.SalticamSlot IS NULL, 0, 1)   AS is_installed
> ```

I would suggest to use `is_in_magazine` rather than `is_installed`.
___
*[`saltapi/repository/salticam_repository.py` line 145 at r1](https://reviewable.io/reviews/saltastroops/salt-api/318#-O2UoDFA8qaSok3DeHTK:-O2UoDFA8qaSok3DeHTL:b7rhgme) ([raw file](https://github.com/saltastroops/salt-api/blob/306a73530cc1ed7ebeb71b20252fcefb50cfee6b/saltapi/repository/salticam_repository.py#L145)):*
> ```Python
>                     "name": row.filter_name,
>                     "description": row.filter_description,
>                     "is_installed": row.is_installed
> ```

I would suggest to use `is_in_magazine` rather than `is_installed`.
___
*[`saltapi/web/schema/salticam.py` line 104 at r1](https://reviewable.io/reviews/saltastroops/salt-api/318#-O2UoG814fINgvBuj_hc:-O2UoG814fINgvBuj_hd:b-hjc2yg) ([raw file](https://github.com/saltastroops/salt-api/blob/306a73530cc1ed7ebeb71b20252fcefb50cfee6b/saltapi/web/schema/salticam.py#L104)):*
> ```Python
>     )
>     is_installed: bool = Field(
>         ..., title="Is installed", description="Indicated weather the filter is installed or not."
> ```

I would suggest:

```
title="Is in magazine", description="Indicates whether the filter currently is in the magazine"
```

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/318)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/salticam_repository.py` line 131 at r1](https://reviewable.io/reviews/saltastroops/salt-api/318#-O2Uo0LP7ZMSOIx9Y_c5:-O2V-h8_19lf6ex7MRAY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/306a73530cc1ed7ebeb71b20252fcefb50cfee6b/saltapi/repository/salticam_repository.py#L131)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest to use `is_in_magazine` rather than `is_installed`.
</blockquote></details>

Done.
___
*[`saltapi/repository/salticam_repository.py` line 145 at r1](https://reviewable.io/reviews/saltastroops/salt-api/318#-O2UoDFA8qaSok3DeHTK:-O2V-heX8uZ0nbc0Ee5E:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/306a73530cc1ed7ebeb71b20252fcefb50cfee6b/saltapi/repository/salticam_repository.py#L145)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest to use `is_in_magazine` rather than `is_installed`.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/salticam.py` line 104 at r1](https://reviewable.io/reviews/saltastroops/salt-api/318#-O2UoG814fINgvBuj_hc:-O2V-oc566Mt0yIUTjkR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/306a73530cc1ed7ebeb71b20252fcefb50cfee6b/saltapi/web/schema/salticam.py#L104)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest:

```
title="Is in magazine", description="Indicates whether the filter currently is in the magazine"
```
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/318)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/web/schema/salticam.py` line 104 at r1](https://reviewable.io/reviews/saltastroops/salt-api/318#-O2UoG814fINgvBuj_hc:-O2_RrZxEkfCZ2VVeJjW:bp8kk0g) ([raw file](https://github.com/saltastroops/salt-api/blob/306a73530cc1ed7ebeb71b20252fcefb50cfee6b/saltapi/web/schema/salticam.py#L104)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd suggest:

```
description="Indicates whether the filter currently is in the magazine"
```

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/318)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/web/schema/salticam.py` line 104 at r1](https://reviewable.io/reviews/saltastroops/salt-api/318#-O2UoG814fINgvBuj_hc:-O36jhh-7P-15zSEhuM6:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/306a73530cc1ed7ebeb71b20252fcefb50cfee6b/saltapi/web/schema/salticam.py#L104)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest:

```
description="Indicates whether the filter currently is in the magazine"
```
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/318)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
