### PR TITLE
backend error logging

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/13)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/13)* status: all files reviewed, 7 unresolved discussions (waiting on @mofokeng-chaka)

___
*[.gitignore, line 105 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIbkU-6LXbljnwVkxW:-MhIbkU0CzqDJtUfqLFx:bnyk8tt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/.gitignore#L105)):*
> ```ignore
> 
> # Environments
> saltapi/.env
> ```

This change shouldn't be necessary...
___
*[saltapi/logging_config.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIrCTU-9lh2rz0otgb:-MhIrCTU-9lh2rz0otgc:bp8ya6f) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L17)):*
> ```Python
> load_dotenv()
> 
> LOG_LEVEL = logging.getLevelName(os.environ.get("LOG_LEVEL", "DEBUG"))
> ```

Environment variables should preferably handled in settings.py.

Also do you use these variables anywhere?
___
*[saltapi/logging_config.py, line 21 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIsv_F2XRYJyxhsX2G:-MhIsv_F2XRYJyxhsX2H:be5fjcp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L21)):*
> ```Python
> 
> 
> class InterceptHandler(logging.Handler):
> ```

Maybe include a reference ce to https://loguru.readthedocs.io/en/stable/overview.html#customizable-levels
___
*[saltapi/logging_config.py, line 32 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIsjGq0nCh31SOMb6m:-MhIsjGq0nCh31SOMb6n:b-ti7mgt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L32)):*
> ```Python
>             level = record.levelno
> 
>         # find calle from where the message originated
> ```

find call ---> Find caller
___
*[saltapi/logging_config.py, line 42 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIovAkAizFHqA2x9NV:-MhIovAkAizFHqA2x9NW:bkw3evq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L42)):*
> ```Python
> 
> def setup_logging():
>     if os.getenv('SENTRY_DSN'):
> ```

You might consider logging a warning if the SENTRY_DSN variable is not set.
___
*[saltapi/logging_config.py, line 43 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIrKKa-Oelz9dHwUwc:-MhIrKKa-Oelz9dHwUwd:buae0sj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L43)):*
> ```Python
> def setup_logging():
>     if os.getenv('SENTRY_DSN'):
>         _ = logger.add(
> ```

Why the "_ ="?
___
*[saltapi/logging_config.py, line 58 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIrPol2fZTikG-saXp:-MhIrPol2fZTikG-saXq:b-cky4by) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L58)):*
> ```Python
>                         ])
> 
>     # enable inteceptor
> ```

inteceptor ---> interceptor

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/13)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[.gitignore, line 105 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIbkU-6LXbljnwVkxW:-MhJAa0M5t_Ev6MBUABd:b-tx0xdj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/.gitignore#L105)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This change shouldn't be necessary...
</blockquote></details>

I may have mixed things up when I was trying to fix some conflicts I was facing. It's a taken care of now.
___
*[saltapi/logging_config.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIrCTU-9lh2rz0otgb:-MhJCEotCDXEn9PMym3d:b7812b2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Environment variables should preferably handled in settings.py.

Also do you use these variables anywhere?
</blockquote></details>

I am not using them, I just forgot to remove them. Removed now.
___
*[saltapi/logging_config.py, line 21 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIsv_F2XRYJyxhsX2G:-MhJCty53Bnk9joofad8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe include a reference ce to https://loguru.readthedocs.io/en/stable/overview.html#customizable-levels
</blockquote></details>

Done.
___
*[saltapi/logging_config.py, line 32 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIsjGq0nCh31SOMb6m:-MhJCskPDix6KPYfrVdN:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

find call ---> Find caller
</blockquote></details>

Done.
___
*[saltapi/logging_config.py, line 42 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIovAkAizFHqA2x9NV:-MhJCDbX5Zk8_Z_Aqqbu:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might consider logging a warning if the SENTRY_DSN variable is not set.
</blockquote></details>

Done.
___
*[saltapi/logging_config.py, line 43 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIrKKa-Oelz9dHwUwc:-MhJCwSS9Q2-rYoaateI:b-j23zvf) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the "_ ="?
</blockquote></details>

It's a mistake, that shouldn't be there.
___
*[saltapi/logging_config.py, line 58 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIrPol2fZTikG-saXp:-MhJCsKf6UQvjOH1hP_O:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L58)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

inteceptor ---> interceptor
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/13)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[saltapi/logging_config.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIrCTU-9lh2rz0otgb:-MhJOQPvE8tWBmZGx8zM:b-pi40h8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L17)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I am not using them, I just forgot to remove them. Removed now.
</blockquote></details>

But note that the comment about handling environment variables still is relevant for the SENTRY_DSN variable... :)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/13)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[saltapi/logging_config.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIrCTU-9lh2rz0otgb:-MhMYtdC88B8OWwC_L4_:b305epd) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But note that the comment about handling environment variables still is relevant for the SENTRY_DSN variable... :)
</blockquote></details>

Oh yes, thanks. I have updated it.
___
*[saltapi/logging_config.py, line 42 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIovAkAizFHqA2x9NV:-MhMbMgK20L4SDgVvtew:b-ycoxv2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L42)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Handling this environment variable under settings.py makes the if statement unnecessary because validation exists for variables defined in settings.py.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/13)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[saltapi/logging_config.py, line 42 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIovAkAizFHqA2x9NV:-MhN9iju27z_udQ9F44p:bpub5ke) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L42)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Handling this environment variable under settings.py makes the if statement unnecessary because validation exists for variables defined in settings.py.
</blockquote></details>

You may still consider making the variable optional, and then you should (I think) still issue a warning.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/13)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[saltapi/logging_config.py, line 42 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhIovAkAizFHqA2x9NV:-MhNCWpM5YAO09L4rmmz:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/8aa64bc1f8b7c17b152ab316123ae4004c6ebcb5/saltapi/logging_config.py#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You may still consider making the variable optional, and then you should (I think) still issue a warning.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r2, 20 of 21 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/13)* status: all files reviewed, 7 unresolved discussions (waiting on @mofokeng-chaka)

___
*[docker-compose.yml, line 16 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhObVpK3eEmoVFqsnw9:-MhObVpK3eEmoVFqsnwA:b9nudy2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/docker-compose.yml#L16)):*
> ```YAML
>       - PROPOSALS_DIR=/proposals
>     ports:
>       - 8001:80
> ```

Is there a reason why you changed the port?
___
*[pyproject.toml, line 26 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhObjSyEe5h8Nvgeb--:-MhObjSyEe5h8Nvgeb-0:b-khhco) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/pyproject.toml#L26)):*
> ```TOML
> pytz = "^2021.1"
> freezegun = "^1.1.0"
> loguru = "0.5.3"
> ```

Is there a reason why you changed the version requirement?
___
*[saltapi/logging_config.py, line 41 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhOcAlj1WkSqKL6kI8i:-MhOcAlj1WkSqKL6kI8j:b-fds15m) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/saltapi/logging_config.py#L41)):*
> ```Python
> 
> def setup_logging(app):
>     if Settings().sentry_dsn:
> ```

Given that you need it twice, I'd suggest to assign Settings().sentry_dsn to a variable.
___
*[saltapi/main.py, line 1 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhOdEd652tTg1sGj_wz:-MhOdEd652tTg1sGj_x-:blgisdm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/saltapi/main.py#L1)):*
> ```Python
> import logging
> ```

Unused import
___
*[saltapi/main.py, line 4 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhOd-8fCP2z9aNl2j8M:-MhOd-8fCP2z9aNl2j8N:b-vmkeul) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/saltapi/main.py#L4)):*
> ```Python
> import os
> import sys
> sys.path.append(os.path.dirname(os.path.abspath('.')))
> ```

Why are you tweaking the path variable?
___
*[saltapi/service/authentication.py, line 1 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhOe9mU74EvN18BpudG:-MhOe9mU74EvN18BpudH:b4pvjwq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/saltapi/service/authentication.py#L1)):*
> ```Python
> from datetime import date
> ```

date --> datetime
___
*[saltapi/service/authentication.py, line 9 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhOeC722T34QDlGKg2W:-MhOeC722T34QDlGKg2X:b-dxhgoz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/saltapi/service/authentication.py#L9)):*
> ```Python
>     access_token: str
>     token_type: str
>     expires_at: date
> ```

date ---> datetime

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/13)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[docker-compose.yml, line 16 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhObVpK3eEmoVFqsnw9:-MhOoc2uDeR3r05c827C:b-g0o7mg) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/docker-compose.yml#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is there a reason why you changed the port?
</blockquote></details>

No, I think I had a problem fixing some of the conflicts I had. So some of these changes were introduced when I was trying to rebase my branch. 
___
*[pyproject.toml, line 26 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhObjSyEe5h8Nvgeb--:-MhOoygjE_HskBKX0hQj:b2nreh6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/pyproject.toml#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is there a reason why you changed the version requirement?
</blockquote></details>

Same as above.
___
*[saltapi/logging_config.py, line 41 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhOcAlj1WkSqKL6kI8i:-MhOp0B94gtZDoSbumRd:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/saltapi/logging_config.py#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that you need it twice, I'd suggest to assign Settings().sentry_dsn to a variable.
</blockquote></details>

Done.
___
*[saltapi/main.py, line 1 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhOdEd652tTg1sGj_wz:-MhOpcnt6w5mzqvskEDt:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/saltapi/main.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unused import
</blockquote></details>

Done.
___
*[saltapi/main.py, line 4 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhOd-8fCP2z9aNl2j8M:-MhOpM305HNw3MqNWany:b-4y1hih) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/saltapi/main.py#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why are you tweaking the path variable?
</blockquote></details>

See my comment about the changed port number.
___
*[saltapi/service/authentication.py, line 1 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhOe9mU74EvN18BpudG:-MhOpgF2-GddiwIuOC8S:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/saltapi/service/authentication.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

date --> datetime
</blockquote></details>

Done.
___
*[saltapi/service/authentication.py, line 9 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/13#-MhOeC722T34QDlGKg2W:-MhOpgoQ55tmeR3kPUuV:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c2951e49d3b123a7ae3dad080fc5b155ca8be80f/saltapi/service/authentication.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

date ---> datetime
</blockquote></details>

Done.

**Pull request merged**
