### PR TITLE
progress-report-pdf

### LINKED ISSUE #89: Missing proposal progress report tests
Tests for getting proposal progress report pdf files still missing

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Test get progress report pdf file

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/107)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/107)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 1701 at r3](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFQIA8e0YonOvtFyakM:-NFQIA8f6P-xpklcTZfz:bwt86c3) ([raw file](https://github.com/saltastroops/salt-api/blob/5ba9dda852c2f4e7c3eb78babb4fd7bab3cc6a2f/saltapi/repository/proposal_repository.py#L1701)):*
> ```Python
>             progress_report[
>                 "partner_requested_percentages"
>             ] = self._get_partner_requested_percentages(proposal_code, _next_semester)
> ```

I think it has to be `_next_semester`, but I'm happy to discuss this.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/107)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1701 at r3](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFQIA8e0YonOvtFyakM:-NFSOjWS2FU8Ol8B0p81:blfvbl1) ([raw file](https://github.com/saltastroops/salt-api/blob/5ba9dda852c2f4e7c3eb78babb4fd7bab3cc6a2f/saltapi/repository/proposal_repository.py#L1701)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think it has to be `_next_semester`, but I'm happy to discuss this.
</blockquote></details>

I think I know why, but I don't mind discussing it.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/107)* status: all files reviewed, 6 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/proposal_service.py` line 6 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFT7_cO0bxS5qdwDuKS:-NFT7_cO0bxS5qdwDuKT:b-s5dchc) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/saltapi/service/proposal_service.py#L6)):*
> ```Python
> from typing import Any, Dict, List, Optional
> 
> import pdfkit  # type: ignore
> ```

I don't think ignoring this line is the right approach. You should exclude the package in the mypy configuration instead.
___
*[`saltapi/service/proposal_service.py` line 279 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFT6x0H4-BKDoZAK20R:-NFT6x0I5SpdF_8u-P7D:b-zgw124) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/saltapi/service/proposal_service.py#L279)):*
> ```Python
>             with PdfMerger(strict=False) as merger:
>                 merger.append(
>                     base_dir + progress_report_pdfs["proposal_progress_filename"]  # type: ignore # noqa: E501
> ```

I'd rather cast to str than ignoring.
___
*[`saltapi/service/proposal_service.py` line 283 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFT93EQBvMjEk-wjUzR:-NFT93EQBvMjEk-wjUzS:b-zgw124) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/saltapi/service/proposal_service.py#L283)):*
> ```Python
>                 if progress_report_pdfs["additional_pdf_filename"]:
>                     merger.append(
>                         base_dir + progress_report_pdfs["additional_pdf_filename"]  # type: ignore # noqa: E501
> ```

I'd rather cast to str than ignoring.
___
*[`tests/integration/progress_report/test_get_progress_report.py` line 124 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFT9nOZ2lGhTEzt82q4:-NFT9nOZ2lGhTEzt82q5:b-6830v4) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/tests/integration/progress_report/test_get_progress_report.py#L124)):*
> ```Python
>             "saltapi.service.proposal_service.get_settings", mock_get_settings
>         )
>         pathlib.Path(mock_get_settings().proposals_dir).joinpath(proposal_code).mkdir()
> ```

Arguably unnecessary; see next comment,
___
*[`tests/integration/progress_report/test_get_progress_report.py` line 125 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTAPBTDop1Pe_7H748:-NFTAPBTDop1Pe_7H749:b-33uydr) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/tests/integration/progress_report/test_get_progress_report.py#L125)):*
> ```Python
>         )
>         pathlib.Path(mock_get_settings().proposals_dir).joinpath(proposal_code).mkdir()
>         pathlib.Path(mock_get_settings().proposals_dir).joinpath(
> ```

Arguably easier:

```
(tmp_path / proposal_code / "Included").mkdir(parents=True)
```
___
*[`saltapi/service/create_proposal_progress_html.py` line 97 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTChDA3VbFKb-IlH_s:-NFTChDA3VbFKb-IlH_t:bwyv2hb) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/saltapi/service/create_proposal_progress_html.py#L97)):*
> ```Python
>                       </tr>
> """
>     for p in sorted(previous_requests, key=lambda i: i["semester"]):  # type: ignore
> ```

I'd suggest to cast `i["semester"]` to str rather than ignoring typing.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/107)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/proposal_service.py` line 6 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFT7_cO0bxS5qdwDuKS:-NFTG6JeA9B0NbXum7lc:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/saltapi/service/proposal_service.py#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think ignoring this line is the right approach. You should exclude the package in the mypy configuration instead.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 279 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFT6x0H4-BKDoZAK20R:-NFTGtl-C7cwZU3i4H61:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/saltapi/service/proposal_service.py#L279)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd rather cast to str than ignoring.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 283 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFT93EQBvMjEk-wjUzR:-NFTGuZr21g4RAkZQ72Y:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/saltapi/service/proposal_service.py#L283)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd rather cast to str than ignoring.
</blockquote></details>

Done.
___
*[`tests/integration/progress_report/test_get_progress_report.py` line 124 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFT9nOZ2lGhTEzt82q4:-NFTJTfBD9W7EIZdbWEt:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/tests/integration/progress_report/test_get_progress_report.py#L124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Arguably unnecessary; see next comment,
</blockquote></details>

Done.
___
*[`tests/integration/progress_report/test_get_progress_report.py` line 125 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTAPBTDop1Pe_7H748:-NFTJU6K41T7Rnm_-Mgd:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/tests/integration/progress_report/test_get_progress_report.py#L125)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Arguably easier:

```
(tmp_path / proposal_code / "Included").mkdir(parents=True)
```
</blockquote></details>

Done.
___
*[`saltapi/service/create_proposal_progress_html.py` line 97 at r4](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTChDA3VbFKb-IlH_s:-NFTJpb61gyPLUA601PB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5a7fb4eb5854a47c6514ea788e862069d01de798/saltapi/service/create_proposal_progress_html.py#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to cast `i["semester"]` to str rather than ignoring typing.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/107)* status: all files reviewed, 7 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/proposal_service.py` line 282 at r5](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTL0Wr3NuX3zFIpdUQ:-NFTL0Wr3NuX3zFIpdUR:bh68b6e) ([raw file](https://github.com/saltastroops/salt-api/blob/161a10f7bc74528d57b0cf7bb331664f7a685033/saltapi/service/proposal_service.py#L282)):*
> ```Python
>                     + cast(
>                         str, progress_report_pdfs["proposal_progress_filename"]
>                     )  # noqa: E501
> ```

I guess you don't need the noqa any longer?
___
*[`saltapi/service/proposal_service.py` line 289 at r5](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTL5FA0xbLV6k1W6ob:-NFTL5FA0xbLV6k1W6oc:bh68b6e) ([raw file](https://github.com/saltastroops/salt-api/blob/161a10f7bc74528d57b0cf7bb331664f7a685033/saltapi/service/proposal_service.py#L289)):*
> ```Python
>                         + cast(
>                             str, progress_report_pdfs["additional_pdf_filename"]
>                         )  # noqa: E501
> ```

I guess you don't need the noqa any longer?
___
*[`tests/integration/progress_report/test_get_progress_report.py` line 124 at r5](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTLEDm1BXc56JlEGry:-NFTLEDm1BXc56JlEGrz:b23lw95) ([raw file](https://github.com/saltastroops/salt-api/blob/161a10f7bc74528d57b0cf7bb331664f7a685033/tests/integration/progress_report/test_get_progress_report.py#L124)):*
> ```Python
>             "saltapi.service.proposal_service.get_settings", mock_get_settings
>         )
>         proposals_dir = f"{mock_get_settings().proposals_dir}/{proposal_code}/Included/"
> ```

Isn't `mock_get_settings().proposals_dir` a `Path`. Then you don't need to go via strings; 
___
*[`tests/integration/progress_report/test_get_progress_report.py` line 124 at r5](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTLhGG8S-tabNB0nmR:-NFTLhGG8S-tabNB0nmS:b-iwdrma) ([raw file](https://github.com/saltastroops/salt-api/blob/161a10f7bc74528d57b0cf7bb331664f7a685033/tests/integration/progress_report/test_get_progress_report.py#L124)):*
> ```Python
>             "saltapi.service.proposal_service.get_settings", mock_get_settings
>         )
>         proposals_dir = f"{mock_get_settings().proposals_dir}/{proposal_code}/Included/"
> ```

You don't need the strings:

```
        proposals_dir = mock_get_settings().proposals_dir / proposal_code / "Included/"
        proposals_dir.mkdir(parents=True)
```

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/107)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[`tests/integration/progress_report/test_get_progress_report.py` line 124 at r5](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTLhGG8S-tabNB0nmR:-NFTN1nJCuNurJeLjh34:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/161a10f7bc74528d57b0cf7bb331664f7a685033/tests/integration/progress_report/test_get_progress_report.py#L124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You don't need the strings:

```
        proposals_dir = mock_get_settings().proposals_dir / proposal_code / "Included/"
        proposals_dir.mkdir(parents=True)
```
</blockquote></details>

Done.
___
*[`tests/integration/progress_report/test_get_progress_report.py` line 124 at r5](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTLEDm1BXc56JlEGry:-NFTN2Y17odYmMaUGmqa:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/161a10f7bc74528d57b0cf7bb331664f7a685033/tests/integration/progress_report/test_get_progress_report.py#L124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't `mock_get_settings().proposals_dir` a `Path`. Then you don't need to go via strings; 
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/107)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`tests/integration/progress_report/test_get_progress_report.py` line 124 at r5](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTLhGG8S-tabNB0nmR:-NFTSKt23rqDfnk7eJrR:b-sbz8ny) ([raw file](https://github.com/saltastroops/salt-api/blob/161a10f7bc74528d57b0cf7bb331664f7a685033/tests/integration/progress_report/test_get_progress_report.py#L124)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any change?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/107)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/integration/progress_report/test_get_progress_report.py` line 124 at r5](https://reviewable.io/reviews/saltastroops/salt-api/107#-NFTLhGG8S-tabNB0nmR:-NFTUg5i8KQDBw1wdUPO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/161a10f7bc74528d57b0cf7bb331664f7a685033/tests/integration/progress_report/test_get_progress_report.py#L124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see any change?
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
