### PR TITLE
Progress report semesters

### LINKED ISSUE #163: Incorrect list of progress report pdfs
The proposal repository uses the `list_semesters` method to generate the list of progress report URLs. This means that a URL is generated even if there is no progress report.

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/164)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/164)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/repository/test_proposal_repository.py` line 761 at r3](https://reviewable.io/reviews/saltastroops/salt-api/164#-NNknbzD29SM6ZsjdUr9:-NNknbzD29SM6ZsjdUrA:b-wa9jse) ([raw file](https://github.com/saltastroops/salt-api/blob/2e7bde35dbe48a765b3a5294626ac8ca172ed4d3/tests/repository/test_proposal_repository.py#L761)):*
> ```Python
>     ],
> )
> def test_get_progress_report_semesters(
> ```

Wouldn't this test fail when progress reports are submitted in the future?

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/164)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`tests/repository/test_proposal_repository.py` line 761 at r3](https://reviewable.io/reviews/saltastroops/salt-api/164#-NNknbzD29SM6ZsjdUr9:-NNkxiyj5N2OJu2nfrMO:b-bwz2qc) ([raw file](https://github.com/saltastroops/salt-api/blob/2e7bde35dbe48a765b3a5294626ac8ca172ed4d3/tests/repository/test_proposal_repository.py#L761)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Wouldn't this test fail when progress reports are submitted in the future?
</blockquote></details>

Yes -- but given none has been submitted since 2020-2, this is extremely unlikely.

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/164)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/repository/test_proposal_repository.py` line 761 at r3](https://reviewable.io/reviews/saltastroops/salt-api/164#-NNknbzD29SM6ZsjdUr9:-NNkybX33v3c-JXswJpH:b-fvgxwn) ([raw file](https://github.com/saltastroops/salt-api/blob/2e7bde35dbe48a765b3a5294626ac8ca172ed4d3/tests/repository/test_proposal_repository.py#L761)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes -- but given none has been submitted since 2020-2, this is extremely unlikely.
</blockquote></details>

Alright, I see. Thanks for the clarification.

**Review by mofokeng-chaka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/164)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
