### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Authentication and integration tests

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/32)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 12 of 16 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/32)* status: all files reviewed, 12 unresolved discussions (waiting on @mofokeng-chaka)

___
*[.gitignore, line 106 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-MsaVEfjHGVgIqXKu:-Mm-MsaVEfjHGVgIqXKv:bcohvtu) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/.gitignore#L106)):*
> ```ignore
> # Environments
> .env
> tests/.env.test
> ```

.env.test should be in the project root directory.
___
*[saltapi/service/permission_service.py, line 37 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-NC1rDZwCkkRnR28P:-Mm-NC1rDZwCkkRnR28Q:b8bmwmt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/saltapi/service/permission_service.py#L37)):*
> ```Python
>                 self.user_repository.is_salt_astronomer(username)
>                 or self.user_repository.is_investigator(username, proposal_code)
>                 or self.user_repository.is_tac_member_for_proposal(
> ```

Isn't that the same condition as in the following line?
___
*[saltapi/web/api/proposals.py, line 84 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-NLS62LJsfKOMZcOG:-Mm-NLS62LJsfKOMZcOH:b-ks2fo3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/saltapi/web/api/proposals.py#L84)):*
> ```Python
> 
>     with UnitOfWork() as unit_of_work:
>         print(to_semester)
> ```

Unnecessary print statement
___
*[tests/conftest.py, line 8 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-NRBY6okZC2MwYtHG:-Mm-NRBZ-HPgwKICoNKQ:bpivzmm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/conftest.py#L8)):*
> ```Python
> # IMPORTANT: These lines must be executed before any server-related package is imported.
> 
> os.environ["DOTENV_FILE"] = "tests/.env.test"
> ```

The value should be ".env.test".
___
*[tests/conftest.py, line 28 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-Nb6T4-xp7IXYYC0S:-Mm-Nb6T4-xp7IXYYC0T:bgvk5tb) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/conftest.py#L28)):*
> ```Python
> from fastapi.testclient import TestClient
> 
> # from pytest_bdd import given, parsers, then
> ```

I would;d suggest to remove unused imports rather than commenting them out, so that cluttering is avoided.
___
*[tests/integration/authentication/test_authentication.py, line 1 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-ULIg8ezGlPsA3l0v:-Mm-ULIg8ezGlPsA3l0w:b-fc1mow) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/authentication/test_authentication.py#L1)):*
> ```Python
> from fastapi.testclient import TestClient
> ```

I would suggest to use more explicit names, such as

`test_should_return_401_if_you_login_with_an_incorrect_username`

(And this might make the comments unnecessary. :-) )
___
*[tests/integration/proposals/test_get_proposal.py, line 1 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-V4_t4dZpQ9O3gZQN:-Mm-V4_t4dZpQ9O3gZQO:b-fc1mow) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/proposals/test_get_proposal.py#L1)):*
> ```Python
> from typing import Dict, Any
> ```

I would suggest to use more explicit names, such as

`test_should_return_401_if_you_login_with_an_incorrect_username`

(And this might make the comments unnecessary. :-) )
___
*[tests/integration/proposals/test_get_proposal.py, line 8 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-Woz51NMkno08A3Bm:-Mm-Woz51NMkno08A3Bn:b-j0ztsz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/proposals/test_get_proposal.py#L8)):*
> ```Python
> 
> from saltapi.settings import Settings
> from tests.conftest import read_testdata, TEST_DATA, authenticate, not_authenticated
> ```

This seemingly innocuous import statement opens an interesting can of worms, which we should discuss with everyone.
___
*[tests/integration/proposals/test_get_proposal.py, line 12 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-_9qm5PCmvj8DLlO_:-Mm-_9qm5PCmvj8DLlOa:bh2nwio) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/proposals/test_get_proposal.py#L12)):*
> ```Python
> PROPOSALS_URL = "/proposals"
> 
> USERS = read_testdata(TEST_DATA)
> ```


TEST_DATA is very ambiguous, in particular as chances are that you might want to use other test data files somewhere.
___
*[tests/integration/proposals/test_get_proposal.py, line 18 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-Zu8s6Jru3HpEN5fp:-Mm-Zu8s6Jru3HpEN5fq:b8b81gs) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/proposals/test_get_proposal.py#L18)):*
> ```Python
> # Unauthenticated user cannot request a proposal
> def test_get_proposal_for_nonpermitted_user(client: TestClient) -> None:
>     proposal_code = list(USERS["investigators"].keys())[0]
> ```

You could just choose any proposal code, rather than using USERS["investigators"]...
___
*[tests/integration/proposals/test_get_proposal.py, line 51 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-eV7yEQ6Wh-C6i3v2:-Mm-eV7yEQ6Wh-C6i3v3:b-kgqfzn) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/proposals/test_get_proposal.py#L51)):*
> ```Python
> )
> def test_get_proposal_for_permitted_users(user_type: str, client: TestClient) -> None:
>     data: Dict[Any, Any] = {"proposal_code": [], "username": []}
> ```

I see two problems:

1. The test is too complicated.
2. It (and the next test) do not adequately test cases where users may not access proposals.

It might be better to use dedicated test data.
___
*[tests/integration/proposals/test_get_proposals.py, line 36 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-kMHI1URi8WGGR_ZF:-Mm-kMHI1URi8WGGR_ZG:b1von6k) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/proposals/test_get_proposals.py#L36)):*
> ```Python
>         authenticate(username, client)
>         response = client.get(PROPOSALS_URL + "/")
>         assert response.status_code == status.HTTP_200_OK
> ```

This tests that the request returns something, but not that it returns the right content.

I'd suggest to implement all the test( case)s defined in the former BDD feature files,

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/32)* status: all files reviewed, 12 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[.gitignore, line 106 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-MsaVEfjHGVgIqXKu:-MmCksyT2Pwk0JrkyyPd:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/.gitignore#L106)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

.env.test should be in the project root directory.
</blockquote></details>

Done.
___
*[saltapi/service/permission_service.py, line 37 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-NC1rDZwCkkRnR28P:-MmCmFQTBjEQoUIlZiXL:bud01ln) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/saltapi/service/permission_service.py#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't that the same condition as in the following line?
</blockquote></details>

That's true, thanks.
___
*[saltapi/web/api/proposals.py, line 84 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-NLS62LJsfKOMZcOG:-MmCmghCCcOimgFTRuJE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/saltapi/web/api/proposals.py#L84)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary print statement
</blockquote></details>

Done.
___
*[tests/conftest.py, line 8 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-NRBY6okZC2MwYtHG:-MmCmyuQ1ZyzIzC8QIcx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/conftest.py#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The value should be ".env.test".
</blockquote></details>

Done.
___
*[tests/conftest.py, line 28 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-Nb6T4-xp7IXYYC0S:-MmCnUTB1OLk8oy6E2hY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/conftest.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would;d suggest to remove unused imports rather than commenting them out, so that cluttering is avoided.
</blockquote></details>

Done.
___
*[tests/integration/authentication/test_authentication.py, line 1 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-ULIg8ezGlPsA3l0v:-MmCoP3o9meRUb20lYqO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/authentication/test_authentication.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest to use more explicit names, such as

`test_should_return_401_if_you_login_with_an_incorrect_username`

(And this might make the comments unnecessary. :-) )
</blockquote></details>

Done.
___
*[tests/integration/proposals/test_get_proposal.py, line 1 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-V4_t4dZpQ9O3gZQN:-MmHfyR44WToWw471Xte:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/proposals/test_get_proposal.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest to use more explicit names, such as

`test_should_return_401_if_you_login_with_an_incorrect_username`

(And this might make the comments unnecessary. :-) )
</blockquote></details>

Done.
___
*[tests/integration/proposals/test_get_proposal.py, line 12 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-_9qm5PCmvj8DLlO_:-MmHfrF5AVhMJ8YcaB3k:b-9p3sb2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/proposals/test_get_proposal.py#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

TEST_DATA is very ambiguous, in particular as chances are that you might want to use other test data files somewhere.
</blockquote></details>

I see what you mean, it is changed now.
___
*[tests/integration/proposals/test_get_proposal.py, line 18 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-Zu8s6Jru3HpEN5fp:-MmCrGrc0ypW-v3qZ9wA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/proposals/test_get_proposal.py#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could just choose any proposal code, rather than using USERS["investigators"]...
</blockquote></details>

Done.
___
*[tests/integration/proposals/test_get_proposal.py, line 51 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-eV7yEQ6Wh-C6i3v2:-MmHvZY7EvAEV5c_iMzA:b-2xwpt7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/proposals/test_get_proposal.py#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I see two problems:

1. The test is too complicated.
2. It (and the next test) do not adequately test cases where users may not access proposals.

It might be better to use dedicated test data.
</blockquote></details>

I agree with you, and I was not sure how to go about this. But choosing a proposal code made things simple. I changed the code and also added test cases where users may not access proposals.
___
*[tests/integration/proposals/test_get_proposals.py, line 36 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-Mm-kMHI1URi8WGGR_ZF:-MmHwG0bEamOTJAwjCBP:b-505eg3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/6e0eb7cfcebe34cd8248dabe9d310e5fb545bdc4/tests/integration/proposals/test_get_proposals.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This tests that the request returns something, but not that it returns the right content.

I'd suggest to implement all the test( case)s defined in the former BDD feature files,
</blockquote></details>

I see what you mean by saying the request might not return the right content, so I have added a few assert statements to check whether that's the case.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r3, 11 of 11 files at r4, 7 of 10 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/32)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[saltapi/web/schema/block.py, line 30 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-MmdUeHY5qZpXjr9-hEx:-MmdUeHZB9uYafmx5BQH:b-pjqzww) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/744aed1eb924e9b7dea8d45f4949927b2c5f2cc6/saltapi/web/schema/block.py#L30)):*
> ```Python
>     EXPIRED = "Expired"
>     NOT_SET = "Not set"
>     ON_HOLD = "On hold"
> ```

"On hold" was correct. (Yes, the database contains "On Hold", but this is inconsistent with "Not set".)

**Review by mofokeng-chaka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-:-MmlRD-u92KXf0KfZEhw:bnfp4nl)* status: 19 of 39 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[saltapi/web/schema/block.py, line 30 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/32#-MmdUeHY5qZpXjr9-hEx:-MmlQ6_-78qXrBCUMvUT:b-4v3dj6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/744aed1eb924e9b7dea8d45f4949927b2c5f2cc6/saltapi/web/schema/block.py#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"On hold" was correct. (Yes, the database contains "On Hold", but this is inconsistent with "Not set".)
</blockquote></details>

I was unsure where the problem was because I was getting a pydantic error related to the status. And after changing this status, it worked.

**Pull request merged**
