### PR TITLE
Adding user statistics.

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/228)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/228)* status: 0 of 5 files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/user_repository.py` line 893 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb6Y0LB0FPz52dOers:-NWb6Y0M3lEZQF2dliX8:bwmtx2d) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/repository/user_repository.py#L893)):*
> ```Python
>         self, pipt_user_id: int, user_information: Union[NewUserDetails, UserUpdate]
>     ) -> None:
>         if user_information.legal_status in [
> ```

I think the validation part should be implemented in the service method.
___
*[`saltapi/service/user.py` line 67 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb42Lv6irKigKr5u47:-NWb42Lw-ApIrp9VWGTf:b-47fnxn) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/service/user.py#L67)):*
> ```Python
> 
> @dataclass()
> class NewUserDetails:
> ```

This class has a subset of properties from UserUpdate class. Maybe you could make this class inherit from the other class? 
___
*[`saltapi/service/user.py` line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb5fpm6VaOo7ShtYoY:-NWb5fpr4UyaqQuNsmOO:b8azof5) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/service/user.py#L78)):*
> ```Python
>     gender: Optional[str]
>     race: Optional[str]
>     is_phd: bool
> ```

I think this property should also be optional?
___
*[`saltapi/service/user.py` line 89 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb8QoVE73uqG_OmiB8:-NWb8QoVE73uqG_OmiB9:btorcbu) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/service/user.py#L89)):*
> ```Python
>     # email: Optional[str]
>     password: Optional[str]
>     legal_status: str
> ```

I would suggest implementing another class with these new properties "UserStatistics" and inheriting from it. Like you did in the schema file.
___
*[`saltapi/service/user.py` line 92 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb5swS3PeHAO-N0Hhr:-NWb5swS3PeHAO-N0Hhs:b8azof5) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/service/user.py#L92)):*
> ```Python
>     gender: Optional[str]
>     race: Optional[str]
>     is_phd: bool
> ```

I think this property should also be optional?
___
*[`saltapi/web/schema/user.py` line 77 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWbAY8J6pV1yYy041ot:-NWbAY8L4ip8s8BhG76e:b-whwmzu) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L77)):*
> ```Python
>         ..., title="Legal status", description="The legal status in South Africa"
>     )
>     gender: Optional[str] = Field(..., title="Gender", description="The gender.")
> ```

Why not just "Gender"?
___
*[`saltapi/web/schema/user.py` line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWbAcleAgRMp0OyUBA0:-NWbAclfDqy-2mX1A-j9:b-bite8q) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L78)):*
> ```Python
>     )
>     gender: Optional[str] = Field(..., title="Gender", description="The gender.")
>     race: Optional[str] = Field(..., title="Race", description="The race.")
> ```

Why not just "Race"?
___
*[`saltapi/web/schema/user.py` line 79 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb7jChARvKNGxg-sbX:-NWb7jChARvKNGxg-sbY:b-87wsdn) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L79)):*
> ```Python
>     gender: Optional[str] = Field(..., title="Gender", description="The gender.")
>     race: Optional[str] = Field(..., title="Race", description="The race.")
>     is_phd: Optional[bool] = Field(
> ```

How about `has_phd` or `has_phd_degree`?
___
*[`saltapi/web/schema/user.py` line 80 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb7eBSBP4_JHHaVeR5:-NWb7eBSBP4_JHHaVeR6:buj33ss) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L80)):*
> ```Python
>     race: Optional[str] = Field(..., title="Race", description="The race.")
>     is_phd: Optional[bool] = Field(
>         ..., title="PhD", description="Whether the user have a PhD"
> ```

Does the user has a PhD?
___
*[`saltapi/web/schema/user.py` line 82 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb74Dj1nSWCgFpLwH5:-NWb74Dj1nSWCgFpLwH6:b-xye6ic) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L82)):*
> ```Python
>         ..., title="PhD", description="Whether the user have a PhD"
>     )
>     year_of_phd: Optional[int] = Field(
> ```

How about `year_of_phd_completion`?
___
*[`saltapi/web/schema/user.py` line 83 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWbB21j6zPgeUpI2GTH:-NWbB21k2s1aUgLZOaEI:bnpm0g1) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L83)):*
> ```Python
>     )
>     year_of_phd: Optional[int] = Field(
>         ..., title="Year of PhD", description="The year the PhD was completed."
> ```

Year of PhD >> Year of PhD degree completion.

The year the PhD was completed >> The year the PhD degree was completed

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/228)* status: 0 of 6 files reviewed, 11 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/user_repository.py` line 893 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb6Y0LB0FPz52dOers:-NWgYlFj6wdBWfJpGJbX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/repository/user_repository.py#L893)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I think the validation part should be implemented in the service method.
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 67 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb42Lv6irKigKr5u47:-NWgesfE0YlyM9cv1FiA:b-xm6rug) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/service/user.py#L67)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

This class has a subset of properties from UserUpdate class. Maybe you could make this class inherit from the other class? 
</blockquote></details>

properties are actually different, other is optional others are not... 
also one extends NamedTuple the other extend @dataclass
not sure why is it like that but will require additional research should I open a new PR
___
*[`saltapi/service/user.py` line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb5fpm6VaOo7ShtYoY:-NWgemkPCRF8kIJ9RNeM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/service/user.py#L78)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I think this property should also be optional?
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 89 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb8QoVE73uqG_OmiB8:-NWgf9Dh8NXBsOUVdzGh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/service/user.py#L89)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I would suggest implementing another class with these new properties "UserStatistics" and inheriting from it. Like you did in the schema file.
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 92 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb5swS3PeHAO-N0Hhr:-NWgfAeVBH1nWZmOrnaO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/service/user.py#L92)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I think this property should also be optional?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/user.py` line 77 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWbAY8J6pV1yYy041ot:-NWgfV0H-S2uL88_lueN:bdlv1n8) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L77)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Why not just "Gender"?
</blockquote></details>

i am lost here
___
*[`saltapi/web/schema/user.py` line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWbAcleAgRMp0OyUBA0:-NWgfX58CLBVQF-x19XU:bdlv1n8) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L78)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Why not just "Race"?
</blockquote></details>

i am lost here
___
*[`saltapi/web/schema/user.py` line 79 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb7jChARvKNGxg-sbX:-NWgfYSv54QVpyBWzfw_:b-fazzzc) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L79)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

How about `has_phd` or `has_phd_degree`?
</blockquote></details>

has_phd won
___
*[`saltapi/web/schema/user.py` line 80 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb7eBSBP4_JHHaVeR5:-NWgfp4fDEXXkYzFLYS7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L80)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Does the user has a PhD?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/user.py` line 82 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb74Dj1nSWCgFpLwH5:-NWgg1HzB7aMY-DoUKCA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L82)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

How about `year_of_phd_completion`?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/user.py` line 83 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWbB21j6zPgeUpI2GTH:-NWggC-RDClWqQNeb6kV:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L83)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Year of PhD >> Year of PhD degree completion.

The year the PhD was completed >> The year the PhD degree was completed
</blockquote></details>

Done.

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
Repository and integration tests are failing.

> Reviewed 1 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/228#-:-NXA-wDLB6O8MTPTTgRl:bk1obf)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/service/user.py` line 67 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb42Lv6irKigKr5u47:-NX9sdSe12ZFP4enfPiu:box8oz) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/service/user.py#L67)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

properties are actually different, other is optional others are not... 
also one extends NamedTuple the other extend @dataclass
not sure why is it like that but will require additional research should I open a new PR
</blockquote></details>

They are not really different. The four fields, legal_status, gender, race and has_phd, are always the same in both classes.

I did a bit of digging on this, NamedTuple and Dataclass are similar, the differences being that one behaves like a tuple and the other like a regular Python class, implying the attributes are not immutable and can be accessed by name and index for the tuple like object while the attributes are mutable and can only be accessed by name for the regular class. 

With that being said, I think if we care about mutability, we can use `@dataclass(frozen=True)`. Also, Tuple based objects are generally large as such they consume a lot of resources when compared to dataclass objects.

Maybe having a class like the one in the code snippets below and having the two classes inherit (using `@dataclass(frozen=True)` decorator) from it:



_Code snippet:_
```Python
@dataclass(frozen=True)
class UserStatistics:
    legal_status: str
    gender: Optional[str]
    race: Optional[str]
    has_phd: Optional[bool]
    year_of_phd_completion: Optional[int]
```
___
*[`saltapi/web/schema/user.py` line 77 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWbAY8J6pV1yYy041ot:-NX9ylu-9Rqg6bEUvw4T:b-5bvqm2) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L77)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

i am lost here
</blockquote></details>

I am suggesting that you change the description, and remove the article "the".
___
*[`saltapi/web/schema/user.py` line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWbAcleAgRMp0OyUBA0:-NX9zFRp759wHvekFQPD:b-5bvqm2) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L78)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

i am lost here
</blockquote></details>

I am suggesting that you change the description, and remove the article "the".

**Review by Eb-Zeero — COMMENTED** [review]
are now fine after fixing schema

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/228#-:-NXjE0--El0HMTQdFlxx:b-73mod7)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/user.py` line 67 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWb42Lv6irKigKr5u47:-NXjDzIS2GE95EptYu6G:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/service/user.py#L67)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

They are not really different. The four fields, legal_status, gender, race and has_phd, are always the same in both classes.

I did a bit of digging on this, NamedTuple and Dataclass are similar, the differences being that one behaves like a tuple and the other like a regular Python class, implying the attributes are not immutable and can be accessed by name and index for the tuple like object while the attributes are mutable and can only be accessed by name for the regular class. 

With that being said, I think if we care about mutability, we can use `@dataclass(frozen=True)`. Also, Tuple based objects are generally large as such they consume a lot of resources when compared to dataclass objects.

Maybe having a class like the one in the code snippets below and having the two classes inherit (using `@dataclass(frozen=True)` decorator) from it:

</blockquote></details>

Done.
___
*[`saltapi/web/schema/user.py` line 77 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWbAY8J6pV1yYy041ot:-NXiqoPvBpn0g7eUqazj:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L77)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I am suggesting that you change the description, and remove the article "the".
</blockquote></details>

Done.
___
*[`saltapi/web/schema/user.py` line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api/228#-NWbAcleAgRMp0OyUBA0:-NXiqp072tytbUXiM0hi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3a462aa169e49df322139b9e09e1941d2e6e9f94/saltapi/web/schema/user.py#L78)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I am suggesting that you change the description, and remove the article "the".
</blockquote></details>

Done.

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
Tests are still failing on my side. For instance, tests in tests/integration/users/ directory are failing.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/228#-:-NXjWd7R3o8uRvMqPSWI:bolm55p)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/repository/user_repository.py` line 891 at r3](https://reviewable.io/reviews/saltastroops/salt-api/228#-NXjLpBl0CpQDxBWWaed:-NXjLlu87b78meo7Natg:b-8i3ufj) ([raw file](https://github.com/saltastroops/salt-api/blob/c157c975835f9c2514c4ef732e0427e48a7578a1/saltapi/repository/user_repository.py#L891)):*
> ```Python
> 
>     def update_user_statistic(
>         self, pipt_user_id: int, user_information: Union[NewUserDetails, UserUpdate]
> ```

I think there's no need to use the Union type now.  User_information should be updated as shown by the code below



_Code snippet:_
```Python
user_information: UserUpdate
```

**Review by Eb-Zeero — COMMENTED** [review]
other tests are not affected by this PR

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/228#-:-NXt1Cph4GmbA1juoc0A:bnycl0a)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/user_repository.py` line 891 at r3](https://reviewable.io/reviews/saltastroops/salt-api/228#-NXjLpBl0CpQDxBWWaed:-NXoK9paEEB5Uu4I_2xL:b-hkjb6l) ([raw file](https://github.com/saltastroops/salt-api/blob/c157c975835f9c2514c4ef732e0427e48a7578a1/saltapi/repository/user_repository.py#L891)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I think there's no need to use the Union type now.  User_information should be updated as shown by the code below
</blockquote></details>

Now using a dict much better

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/228)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`tests/integration/users/test_patch_user.py` line 38 at r4](https://reviewable.io/reviews/saltastroops/salt-api/228#-NXtDS0K56_eCCqSNZ7G:-NXtDS0Q8ElfOXLGUAkD:b-psqklk) ([raw file](https://github.com/saltastroops/salt-api/blob/287d42b4807b0cd45bcb209affa19b0bb0f6aa25/tests/integration/users/test_patch_user.py#L38)):*
> ```Python
> 
> 
> def _update_user(new_username: str) -> Dict[str, any]:
> ```

I think the two helper functions are the same. 

Maybe you can achieve the same result by using the first one and providing a different username and password when needed?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/228)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`tests/integration/users/test_patch_user.py` line 38 at r4](https://reviewable.io/reviews/saltastroops/salt-api/228#-NXtDS0K56_eCCqSNZ7G:-NXyEaV757CB5gHIg0sT:b-e96wds) ([raw file](https://github.com/saltastroops/salt-api/blob/287d42b4807b0cd45bcb209affa19b0bb0f6aa25/tests/integration/users/test_patch_user.py#L38)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I think the two helper functions are the same. 

Maybe you can achieve the same result by using the first one and providing a different username and password when needed?
</blockquote></details>

nice one good catch

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/228)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
