### PR TITLE
Clean up schemas

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/9)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/9)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[saltapi/web/schema/proposal.py, line 58 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgHDd1C71X1_aimEbVe:-MgHDd1EDyfFSEAl5dHM:bzgak26) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd994c95b7fc6b6304d33a84858427c934de4df4/saltapi/web/schema/proposal.py#L58)):*
> ```Python
> 
>     COMMISSIONING = "Commissioning"
>     DIRECTOR_DISCRETIONARY_TIME = "Director’s Discretionary Time"
> ```

it should map to "Director Discretionary Time (DDT)"

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/9)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[saltapi/web/schema/proposal.py, line 58 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgHDd1C71X1_aimEbVe:-MgHQ4n_9MaAvXJ3VKUl:b-iii3d0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd994c95b7fc6b6304d33a84858427c934de4df4/saltapi/web/schema/proposal.py#L58)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

it should map to "Director Discretionary Time (DDT)"
</blockquote></details>

I disagree. This is what the database contains, but I don't think it should be what the API serves, in particular because of the missing apostrophe.

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/9)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[saltapi/web/schema/proposal.py, line 58 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgHDd1C71X1_aimEbVe:-MgJsFLc6DM9sLrmZx1T:bcz9nt4) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd994c95b7fc6b6304d33a84858427c934de4df4/saltapi/web/schema/proposal.py#L58)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I disagree. This is what the database contains, but I don't think it should be what the API serves, in particular because of the missing apostrophe.
</blockquote></details>

I tried getting live data using this branch, I couldn't. I get this "value is not a valid enumeration member; ..." error.
But when I add the changes I suggested everything works well, I can get live data.

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/9)* status: 0 of 32 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[saltapi/web/schema/proposal.py, line 58 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgHDd1C71X1_aimEbVe:-MgN1RkN7kRbqsbi9q0G:b6td81u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd994c95b7fc6b6304d33a84858427c934de4df4/saltapi/web/schema/proposal.py#L58)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I tried getting live data using this branch, I couldn't. I get this "value is not a valid enumeration member; ..." error.
But when I add the changes I suggested everything works well, I can get live data.
</blockquote></details>

Hmm, true. But the solution was to fix the code for extracting information from the database... :-) It should work now.

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 8 of 24 files at r1, 12 of 20 files at r4, 1 of 1 files at r5, 1 of 5 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/9)* status: 26 of 32 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[saltapi/main.py, line 26 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgnWBW7BZe5Cmf2-hsu:-MgnWBW7BZe5Cmf2-hsv:bu0ryx5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f7b847b36056d5809c9a4a660f92670e6539c6f7/saltapi/main.py#L26)):*
> ```Python
> 
> @app.get("/{block_id}")
> def home(block_id: int) -> Any:
> ```

this should be removed now
___
*[saltapi/repository/block_repository.py, line 177 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgnWXMYDaXUbvbgrvq8:-MgnWXMYDaXUbvbgrvq9:boo13q7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f7b847b36056d5809c9a4a660f92670e6539c6f7/saltapi/repository/block_repository.py#L177)):*
> ```Python
>         ]
> 
>     def _finder_charts(self, pointing_id: int) -> List[Dict[str, Any]]:
> ```

not sure if this i sthe right plaform bu we need tio discuss chats file path.
seee it missing here that is why
___
*[saltapi/repository/rss_repository.py, line 24 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgnXf9c3RF5udJ5_tfX:-MgnXf9d8RHK0wtf7Tgq:b-f5tcm2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f7b847b36056d5809c9a4a660f92670e6539c6f7/saltapi/repository/rss_repository.py#L24)):*
> ```Python
>        IF(RC.RssFabryPerot_Id IS NOT NULL, 1, 0)         AS has_fp,
>        IF(RC.RssPolarimetry_Id IS NOT NULL, 1, 0)        AS has_polarimetry,
>        IF(RC.RssMask_Id IS NOT NULL, 1, 0)                  has_mask,
> ```

missing AS
has_mask -> AS has_mask
___
*[saltapi/service/instrument.py, line 3 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgnYR1mAafB8tYtrXBr:-MgnYR1mAafB8tYtrXBs:b-1h9t3m) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f7b847b36056d5809c9a4a660f92670e6539c6f7/saltapi/service/instrument.py#L3)):*
> ```Python
> from typing import Any
> 
> Salticam = Any
> ```

this any still hits me but is fine.
___
*[saltapi/service/proposal.py, line 10 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgnYkU76Zv1HkL7Iks_:-MgnYkU76Zv1HkL7Iksa:b-2whpaj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d6b6d4bd407eeb98146dea828e29f81dc34bff2b/saltapi/service/proposal.py#L10)):*
> ```Python
> 
> 
> class ProposalSummary(NamedTuple):
> ```

is this another rename or moved?

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/9)* status: 26 of 32 files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/main.py, line 26 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgnWBW7BZe5Cmf2-hsu:-MgpbXG1-UK7rn7nVbkn:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f7b847b36056d5809c9a4a660f92670e6539c6f7/saltapi/main.py#L26)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this should be removed now
</blockquote></details>

Done.
___
*[saltapi/repository/block_repository.py, line 177 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgnWXMYDaXUbvbgrvq8:-Mgpb_9669gbopKQaXVe:b3lnyz2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f7b847b36056d5809c9a4a660f92670e6539c6f7/saltapi/repository/block_repository.py#L177)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

not sure if this i sthe right plaform bu we need tio discuss chats file path.
seee it missing here that is why
</blockquote></details>

Yes, that had hit my mind as well. But it is not required. You can get the path from the id, so all the API user needs to know is the id.
___
*[saltapi/repository/rss_repository.py, line 24 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgnXf9c3RF5udJ5_tfX:-MgpcMO16eBpR_1MnwJv:ba7mpxn) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f7b847b36056d5809c9a4a660f92670e6539c6f7/saltapi/repository/rss_repository.py#L24)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

missing AS
has_mask -> AS has_mask
</blockquote></details>

Added. Thanks!
___
*[saltapi/service/instrument.py, line 3 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgnYR1mAafB8tYtrXBr:-Mgpc-dd7xular3aewzL:bmjr0v5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f7b847b36056d5809c9a4a660f92670e6539c6f7/saltapi/service/instrument.py#L3)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this any still hits me but is fine.
</blockquote></details>

It's called "I pretend there is a Salticam type"...
___
*[saltapi/service/proposal.py, line 10 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/9#-MgnYkU76Zv1HkL7Iks_:-MgpcdAw4jiMXSOaFRA2:b-mc9zpf) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d6b6d4bd407eeb98146dea828e29f81dc34bff2b/saltapi/service/proposal.py#L10)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

is this another rename or moved?
</blockquote></details>

I'm not sure what you are referring to. (Maybe Reviewable is showing your comment in the wrong place?)

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 2 of 24 files at r1, 3 of 20 files at r4, 1 of 5 files at r6, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
