### PR TITLE
minor-updates

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Fix for broken API docs

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/87)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/87)* status: all files reviewed, 19 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/block_repository.py` line 9 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84HihO9gCfnGRe2naD:-N84HihP1cKcRCzeAhjC:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/block_repository.py#L9)):*
> ```Python
> from sqlalchemy.engine.base import Connection
> from sqlalchemy.exc import IntegrityError
> from sqlalchemy.orm.exc import NoResultFound
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/bvit_repository.py` line 2 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84MSe231SZuuQ08Ko_:-N84MSe231SZuuQ08Koa:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/bvit_repository.py#L2)):*
> ```Python
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/finder_chart_repository.py` line 5 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84HyOp5C9JWC_KHRL-:-N84HyOp5C9JWC_KHRL0:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/finder_chart_repository.py#L5)):*
> ```Python
> 
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/finder_chart_repository.py` line 6 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84HzFK30EYskW0U7YO:-N84HzFK30EYskW0U7YP:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/finder_chart_repository.py#L6)):*
> ```Python
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> from sqlalchemy.orm.exc import NoResultFound
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/hrs_repository.py` line 5 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I0P55jF1mJbwxS1O:-N84I0P55jF1mJbwxS1P:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/hrs_repository.py#L5)):*
> ```Python
> 
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/institution_repository.py` line 4 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I1sr7A5JlelvUjSz:-N84I1sr7A5JlelvUjT-:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/institution_repository.py#L4)):*
> ```Python
> 
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/instrument_repository.py` line 3 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I4TE80XWijEtjEtP:-N84I4TE80XWijEtjEtQ:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/instrument_repository.py#L3)):*
> ```Python
> from typing import Any, Dict, List
> 
> from sqlalchemy.engine.base import Connection
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/proposal_repository.py` line 9 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I6Np-Ec55T8Xy9bb:-N84I6Np-Ec55T8Xy9bc:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/proposal_repository.py#L9)):*
> ```Python
> from dateutil.relativedelta import relativedelta
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/proposal_repository.py` line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I76FEF92BbjOMwe5:-N84I76FEF92BbjOMwe6:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/proposal_repository.py#L10)):*
> ```Python
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> from sqlalchemy.orm.exc import NoResultFound
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/rss_repository.py` line 6 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84IGQzBMXW-NC9bBoo:-N84IGQzBMXW-NC9bBop:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/rss_repository.py#L6)):*
> ```Python
> 
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/salticam_repository.py` line 4 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84II9HEXZTrEPB184X:-N84II9HEXZTrEPB184Y:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/salticam_repository.py#L4)):*
> ```Python
> 
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/submission_repository.py` line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84IJxz1c1eDHmgBD7t:-N84IJxz1c1eDHmgBD7u:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/submission_repository.py#L7)):*
> ```Python
> import pytz
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/submission_repository.py` line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84IL2kEtD2WuEOfCR7:-N84IL2kEtD2WuEOfCR8:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/submission_repository.py#L8)):*
> ```Python
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> from sqlalchemy.orm.exc import NoResultFound
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/target_repository.py` line 6 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84INtn5limDBpnoW5M:-N84INtn5limDBpnoW5N:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/target_repository.py#L6)):*
> ```Python
> from astropy.coordinates import Angle
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/repository/user_repository.py` line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84IPHL1WFSZhfU3BFX:-N84IPHL1WFSZhfU3BFY:bphd0u7) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/user_repository.py#L8)):*
> ```Python
> from passlib.context import CryptContext
> from sqlalchemy import text
> from sqlalchemy.engine.base import Connection
> ```

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
___
*[`saltapi/service/create_html.py` line 13 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84JMJK2an8INGrPrHH:-N84JMJK2an8INGrPrHI:b5hkr3h) ([raw file](https://github.com/saltastroops/salt-api/blob/5a5ed63fe9eba23c5449a82ca3dc46f0cb11b787/saltapi/service/create_html.py#L13)):*
> ```Python
>         new_request: Dict[str, any]
> ):
>     html_content = '''
> ```

It seems that yiu are not using the version of black specified in `pyproject.toml`?
___
*[`saltapi/web/api/proposal_progress.py` line 28 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84N4IdAQFiv1zULZzy:-N84N4IdAQFiv1zULZzz:b-2biu1n) ([raw file](https://github.com/saltastroops/salt-api/blob/5a5ed63fe9eba23c5449a82ca3dc46f0cb11b787/saltapi/web/api/proposal_progress.py#L28)):*
> ```Python
>     "/{proposal_code}/{semester}",
>     summary="Get a progress report",
>     response_model=ProposalProgress,
> ```

I don't think the response model should be removed. (If you are concerned about duplication, you could have the methods return a dict instead of a ProposalProgress.)
___
*[`saltapi/web/api/proposal_progress.py` line 31 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84MeV-BL8XSS3auFD8:-N84MeV-BL8XSS3auFD9:b-64xfxv) ([raw file](https://github.com/saltastroops/salt-api/blob/5a5ed63fe9eba23c5449a82ca3dc46f0cb11b787/saltapi/web/api/proposal_progress.py#L31)):*
> ```Python
>     responses={200: {"content": {"application/pdf": {}}}},
> )
> def get_progress_report(
> ```

The names are somewhat inconsistent; sometimes it's "proposal progress", sometimes "progress report".
___
*[`saltapi/web/api/proposals.py` line 435 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84OxkC9J-TEn8HA5TO:-N84OxkC9J-TEn8HA5TP:b-78gqkf) ([raw file](https://github.com/saltastroops/salt-api/blob/5a5ed63fe9eba23c5449a82ca3dc46f0cb11b787/saltapi/web/api/proposals.py#L435)):*
> ```Python
>     response_model=ProposalProgress,
> )
> def put_progress_report(
> ```

If you upload details and files at the same time, you'd have to use Form parameters.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/87)* status: 6 of 22 files reviewed, 19 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/block_repository.py` line 9 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84HihO9gCfnGRe2naD:-N88bLie3QukVG89aJUt:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/block_repository.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/finder_chart_repository.py` line 5 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84HyOp5C9JWC_KHRL-:-N88bTgnDzzPM3N3Y--H:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/finder_chart_repository.py#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/finder_chart_repository.py` line 6 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84HzFK30EYskW0U7YO:-N88bUAp2hPrv8EgNANK:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/finder_chart_repository.py#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/proposal_repository.py` line 9 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I6Np-Ec55T8Xy9bb:-N88bXs4A-C_nSD22tYD:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/proposal_repository.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/proposal_repository.py` line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I76FEF92BbjOMwe5:-N88bYSq9sE1sTbhV26n:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/proposal_repository.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/submission_repository.py` line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84IJxz1c1eDHmgBD7t:-N88b_qT627qR-1y7LGD:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/submission_repository.py#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/submission_repository.py` line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84IL2kEtD2WuEOfCR7:-N88baSWCA1k3FadPB5Z:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/submission_repository.py#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/service/create_html.py` line 13 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84JMJK2an8INGrPrHH:-N88bdK38Norgc-AtgZP:b-962x05) ([raw file](https://github.com/saltastroops/salt-api/blob/5a5ed63fe9eba23c5449a82ca3dc46f0cb11b787/saltapi/service/create_html.py#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems that yiu are not using the version of black specified in `pyproject.toml`?
</blockquote></details>

I have updated it, and I think I ended up updating other packages as well. 
___
*[`saltapi/web/api/proposal_progress.py` line 28 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84N4IdAQFiv1zULZzy:-N88lOxc8InahPwqoxcO:b-kfvznt) ([raw file](https://github.com/saltastroops/salt-api/blob/5a5ed63fe9eba23c5449a82ca3dc46f0cb11b787/saltapi/web/api/proposal_progress.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the response model should be removed. (If you are concerned about duplication, you could have the methods return a dict instead of a ProposalProgress.)
</blockquote></details>

I removed it previously because the API docs were breaking complaining and it only worked when I removed the response model. However, I stand corrected, it is now working with the response model specified.
___
*[`saltapi/web/api/proposal_progress.py` line 31 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84MeV-BL8XSS3auFD8:-N88kVI67vDKsEROdFF5:bajzb81) ([raw file](https://github.com/saltastroops/salt-api/blob/5a5ed63fe9eba23c5449a82ca3dc46f0cb11b787/saltapi/web/api/proposal_progress.py#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The names are somewhat inconsistent; sometimes it's "proposal progress", sometimes "progress report".
</blockquote></details>

I have tried to address this.
___
*[`saltapi/web/api/proposals.py` line 435 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84OxkC9J-TEn8HA5TO:-N88aqmc6QvzqYBszi-6:buz89j7) ([raw file](https://github.com/saltastroops/salt-api/blob/5a5ed63fe9eba23c5449a82ca3dc46f0cb11b787/saltapi/web/api/proposals.py#L435)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you upload details and files at the same time, you'd have to use Form parameters.
</blockquote></details>

I don't think this comment belongs to this PR. This PR is for fixing the API docs that were broken by some response models. Maybe it should be for the progress report endpoint PR?
___
*[`saltapi/repository/bvit_repository.py` line 2 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84MSe231SZuuQ08Ko_:-N88bSuWBbjFJeWcc68t:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/bvit_repository.py#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/hrs_repository.py` line 5 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I0P55jF1mJbwxS1O:-N88bUwc1h3Iwas8Zk1G:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/hrs_repository.py#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/institution_repository.py` line 4 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I1sr7A5JlelvUjSz:-N88bVZO7GI-cc_yyA9j:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/institution_repository.py#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/instrument_repository.py` line 3 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I4TE80XWijEtjEtP:-N88bWCq2XaZswi0t5TT:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/instrument_repository.py#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/rss_repository.py` line 6 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84IGQzBMXW-NC9bBoo:-N88bZDj7PEQVz9tjMJV:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/rss_repository.py#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/salticam_repository.py` line 4 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84II9HEXZTrEPB184X:-N88bZsoA12Gyw3gTG_N:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/salticam_repository.py#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/target_repository.py` line 6 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84INtn5limDBpnoW5M:-N88bbFG0ufCkX8-0uy2:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/target_repository.py#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.
___
*[`saltapi/repository/user_repository.py` line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84IPHL1WFSZhfU3BFX:-N88bckt0V0gbY55S0G6:b-utuljd) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/user_repository.py#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that's right. Is this still from your SQLAlchemy version 1.0.1 days?
</blockquote></details>

That's probably true, i have fixed it now.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/87)* status: all files reviewed, 7 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/block_repository.py` line 9 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84HihO9gCfnGRe2naD:-N8K7cJI3IGIPRgpFOKi:b-2mk3t6) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/block_repository.py#L9)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

That's probably true, i have fixed it now.
</blockquote></details>

Nope, I don't think you've fixed this one... :)
___
*[`saltapi/repository/finder_chart_repository.py` line 6 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84HzFK30EYskW0U7YO:-N8K5VMZEUNPWRUJ9Dyl:b-2mk3t6) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/finder_chart_repository.py#L6)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

That's probably true, i have fixed it now.
</blockquote></details>

Nope, I don't think you've fixed this one... :)
___
*[`saltapi/repository/proposal_repository.py` line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I76FEF92BbjOMwe5:-N8K5gvD-7MyHlLkXMLo:b-2mk3t6) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/proposal_repository.py#L10)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

That's probably true, i have fixed it now.
</blockquote></details>

Nope, I don't think you've fixed this one... :)
___
*[`saltapi/repository/submission_repository.py` line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84IL2kEtD2WuEOfCR7:-N8K5q9o6IypehxHRl_6:b-2mk3t6) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/submission_repository.py#L8)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

That's probably true, i have fixed it now.
</blockquote></details>

Nope, I don't think you've fixed this one... :)
___
*[`saltapi/web/api/proposals.py` line 435 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84OxkC9J-TEn8HA5TO:-N8K7Z630Yl53WFXyjT1:bw63w0l) ([raw file](https://github.com/saltastroops/salt-api/blob/5a5ed63fe9eba23c5449a82ca3dc46f0cb11b787/saltapi/web/api/proposals.py#L435)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I don't think this comment belongs to this PR. This PR is for fixing the API docs that were broken by some response models. Maybe it should be for the progress report endpoint PR?
</blockquote></details>

Fair point.
___
*[`saltapi/web/schema/proposal.py` line 556 at r2](https://reviewable.io/reviews/saltastroops/salt-api/87#-N8K6Soz4ZevAPcsojkO:-N8K6Soz4ZevAPcsojkP:b-tq14wo) ([raw file](https://github.com/saltastroops/salt-api/blob/383734ba8ac4bf46a0674ed712949ab916c1e012/saltapi/web/schema/proposal.py#L556)):*
> ```Python
>     )
> 
>     proposal_progress_pdf: Optional[pathlib.Path] = Field(
> ```

This should be a URL, not a file path.
___
*[`saltapi/web/schema/proposal.py` line 562 at r2](https://reviewable.io/reviews/saltastroops/salt-api/87#-N8K6Y3ODTC_LU6gOnRB:-N8K6Y3ODTC_LU6gOnRC:b-tq14wo) ([raw file](https://github.com/saltastroops/salt-api/blob/383734ba8ac4bf46a0674ed712949ab916c1e012/saltapi/web/schema/proposal.py#L562)):*
> ```Python
>     )
> 
>     additional_pdf: Optional[pathlib.Path] = Field(
> ```

This should be a URL, not a file path.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/87)* status: 17 of 22 files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/block_repository.py` line 9 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84HihO9gCfnGRe2naD:-N8S6WUGA5d5LvvEmwH2:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/block_repository.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nope, I don't think you've fixed this one... :)
</blockquote></details>

Done.
___
*[`saltapi/repository/finder_chart_repository.py` line 6 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84HzFK30EYskW0U7YO:-N8S6XI17KpOk1kmHDZQ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/finder_chart_repository.py#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nope, I don't think you've fixed this one... :)
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84I76FEF92BbjOMwe5:-N8S6XwzEYQ1ivXMNGNC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/proposal_repository.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nope, I don't think you've fixed this one... :)
</blockquote></details>

Done.
___
*[`saltapi/repository/submission_repository.py` line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84IL2kEtD2WuEOfCR7:-N8S6YVwE2_xJ2-ZVD7M:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1485a501e6bb1b2def9ef5b11965b8be43ddbedb/saltapi/repository/submission_repository.py#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nope, I don't think you've fixed this one... :)
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 435 at r1](https://reviewable.io/reviews/saltastroops/salt-api/87#-N84OxkC9J-TEn8HA5TO:-N8SAncoELlQIqW4DDWf:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5a5ed63fe9eba23c5449a82ca3dc46f0cb11b787/saltapi/web/api/proposals.py#L435)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Fair point.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 556 at r2](https://reviewable.io/reviews/saltastroops/salt-api/87#-N8K6Soz4ZevAPcsojkO:-N8SAmXC82JtsJYGpzpG:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/383734ba8ac4bf46a0674ed712949ab916c1e012/saltapi/web/schema/proposal.py#L556)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be a URL, not a file path.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 562 at r2](https://reviewable.io/reviews/saltastroops/salt-api/87#-N8K6Y3ODTC_LU6gOnRB:-N8SAm9J6ajMEjnk30iM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/383734ba8ac4bf46a0674ed712949ab916c1e012/saltapi/web/schema/proposal.py#L562)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be a URL, not a file path.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
